// Auto-Journal Engine — generates accounting entries from financial operations
// RULE: Silent failure — never break the original operation due to accounting errors

import { type PrismaClient, Prisma } from "@repo/database/prisma/generated/client";
import { createJournalEntry, EXPENSE_CATEGORY_TO_ACCOUNT_CODE } from "@repo/database";

const ZERO = new Prisma.Decimal(0);

// ========================================
// Helper: Is accounting enabled for this org?
// ========================================
async function isAccountingEnabled(db: PrismaClient, organizationId: string): Promise<boolean> {
	const count = await db.chartAccount.count({ where: { organizationId }, take: 1 });
	return count > 0;
}

// ========================================
// Helper: Get account by code
// ========================================
async function getAccountByCode(db: PrismaClient, organizationId: string, code: string): Promise<string | null> {
	const account = await db.chartAccount.findUnique({
		where: { organizationId_code: { organizationId, code } },
		select: { id: true },
	});
	return account?.id ?? null;
}

// ========================================
// Helper: Get bank's chart account
// ========================================
async function getBankChartAccountId(db: PrismaClient, organizationId: string, bankId: string): Promise<string | null> {
	const bank = await db.organizationBank.findUnique({
		where: { id: bankId },
		select: { chartAccountId: true },
	});
	if (bank?.chartAccountId) return bank.chartAccountId;
	// Fallback to generic Cash & Banks account
	return getAccountByCode(db, organizationId, "1110");
}

// ========================================
// 1. Invoice Issued → DR: Receivable / CR: Revenue + VAT
// ========================================
export async function onInvoiceIssued(db: PrismaClient, invoice: {
	id: string;
	organizationId: string;
	number: string;
	issueDate: Date;
	clientName: string;
	totalAmount: Prisma.Decimal;
	vatAmount: Prisma.Decimal;
	projectId?: string | null;
}) {
	if (!(await isAccountingEnabled(db, invoice.organizationId))) return;

	const receivableId = await getAccountByCode(db, invoice.organizationId, "1120");
	const revenueId = await getAccountByCode(db, invoice.organizationId, "4100");
	const vatPayableId = await getAccountByCode(db, invoice.organizationId, "2130");

	if (!receivableId || !revenueId || !vatPayableId) return;

	const netAmount = invoice.totalAmount.sub(invoice.vatAmount);
	const lines: any[] = [
		{ accountId: receivableId, debit: invoice.totalAmount, credit: ZERO, description: `فاتورة ${invoice.number} — ${invoice.clientName}`, projectId: invoice.projectId },
		{ accountId: revenueId, debit: ZERO, credit: netAmount, description: `إيراد فاتورة ${invoice.number}`, projectId: invoice.projectId },
	];

	if (invoice.vatAmount.greaterThan(0)) {
		lines.push({ accountId: vatPayableId, debit: ZERO, credit: invoice.vatAmount, description: `ضريبة فاتورة ${invoice.number}` });
	}

	await createJournalEntry(db, {
		organizationId: invoice.organizationId,
		date: invoice.issueDate,
		description: `إصدار فاتورة ${invoice.number} — ${invoice.clientName}`,
		referenceType: "INVOICE",
		referenceId: invoice.id,
		referenceNo: invoice.number,
		isAutoGenerated: true,
		lines,
	});
}

// ========================================
// 2. Invoice Payment → DR: Bank / CR: Receivable
// ========================================
export async function onInvoicePaymentReceived(db: PrismaClient, payment: {
	organizationId: string;
	invoiceId: string;
	invoiceNumber: string;
	clientName: string;
	amount: Prisma.Decimal;
	date: Date;
	sourceAccountId: string;
	projectId?: string | null;
}) {
	if (!(await isAccountingEnabled(db, payment.organizationId))) return;

	const bankAccId = await getBankChartAccountId(db, payment.organizationId, payment.sourceAccountId);
	const receivableId = await getAccountByCode(db, payment.organizationId, "1120");
	if (!bankAccId || !receivableId) return;

	await createJournalEntry(db, {
		organizationId: payment.organizationId,
		date: payment.date,
		description: `تحصيل دفعة — فاتورة ${payment.invoiceNumber} — ${payment.clientName}`,
		referenceType: "INVOICE_PAYMENT",
		referenceId: payment.invoiceId,
		referenceNo: payment.invoiceNumber,
		isAutoGenerated: true,
		lines: [
			{ accountId: bankAccId, debit: payment.amount, credit: ZERO, projectId: payment.projectId },
			{ accountId: receivableId, debit: ZERO, credit: payment.amount, projectId: payment.projectId },
		],
	});
}

// ========================================
// 3. Expense Completed → DR: Expense / CR: Bank
// ========================================
export async function onExpenseCompleted(db: PrismaClient, expense: {
	id: string;
	organizationId: string;
	category: string;
	amount: Prisma.Decimal;
	date: Date;
	description: string;
	sourceAccountId?: string | null;
	projectId?: string | null;
}) {
	if (!(await isAccountingEnabled(db, expense.organizationId))) return;

	const expenseCode = EXPENSE_CATEGORY_TO_ACCOUNT_CODE[expense.category] || "6900";
	const expenseAccId = await getAccountByCode(db, expense.organizationId, expenseCode);

	let bankAccId: string | null = null;
	if (expense.sourceAccountId) {
		bankAccId = await getBankChartAccountId(db, expense.organizationId, expense.sourceAccountId);
	} else {
		bankAccId = await getAccountByCode(db, expense.organizationId, "1110");
	}

	if (!expenseAccId || !bankAccId) return;

	await createJournalEntry(db, {
		organizationId: expense.organizationId,
		date: expense.date,
		description: `مصروف: ${expense.description}`,
		referenceType: "EXPENSE",
		referenceId: expense.id,
		isAutoGenerated: true,
		lines: [
			{ accountId: expenseAccId, debit: expense.amount, credit: ZERO, projectId: expense.projectId },
			{ accountId: bankAccId, debit: ZERO, credit: expense.amount, projectId: expense.projectId },
		],
	});
}

// ========================================
// 4. Transfer → DR: Destination Bank / CR: Source Bank
// ========================================
export async function onTransferCompleted(db: PrismaClient, transfer: {
	id: string;
	organizationId: string;
	amount: Prisma.Decimal;
	date: Date;
	fromAccountId: string;
	toAccountId: string;
	description?: string;
}) {
	if (!(await isAccountingEnabled(db, transfer.organizationId))) return;

	const fromAccId = await getBankChartAccountId(db, transfer.organizationId, transfer.fromAccountId);
	const toAccId = await getBankChartAccountId(db, transfer.organizationId, transfer.toAccountId);
	if (!fromAccId || !toAccId) return;

	await createJournalEntry(db, {
		organizationId: transfer.organizationId,
		date: transfer.date,
		description: transfer.description || "تحويل بين حسابات",
		referenceType: "TRANSFER",
		referenceId: transfer.id,
		isAutoGenerated: true,
		lines: [
			{ accountId: toAccId, debit: transfer.amount, credit: ZERO },
			{ accountId: fromAccId, debit: ZERO, credit: transfer.amount },
		],
	});
}

// ========================================
// 5. Subcontract Payment → DR: Subcontractors / CR: Bank
// ========================================
export async function onSubcontractPayment(db: PrismaClient, payment: {
	id: string;
	organizationId: string;
	contractorName: string;
	amount: Prisma.Decimal;
	date: Date;
	sourceAccountId: string;
	projectId?: string | null;
}) {
	if (!(await isAccountingEnabled(db, payment.organizationId))) return;

	const subAccId = await getAccountByCode(db, payment.organizationId, "5200");
	const bankAccId = await getBankChartAccountId(db, payment.organizationId, payment.sourceAccountId);
	if (!subAccId || !bankAccId) return;

	await createJournalEntry(db, {
		organizationId: payment.organizationId,
		date: payment.date,
		description: `دفعة مقاول باطن — ${payment.contractorName}`,
		referenceType: "SUBCONTRACT_PAYMENT",
		referenceId: payment.id,
		isAutoGenerated: true,
		lines: [
			{ accountId: subAccId, debit: payment.amount, credit: ZERO, projectId: payment.projectId },
			{ accountId: bankAccId, debit: ZERO, credit: payment.amount },
		],
	});
}

// ========================================
// 6. Payroll Approved → DR: Salaries / CR: Bank + GOSI
// ========================================
export async function onPayrollApproved(db: PrismaClient, payroll: {
	id: string;
	organizationId: string;
	month: number;
	year: number;
	totalNet: Prisma.Decimal;
	totalGosi: Prisma.Decimal;
	sourceAccountId?: string | null;
}) {
	if (!(await isAccountingEnabled(db, payroll.organizationId))) return;

	const salaryAccId = await getAccountByCode(db, payroll.organizationId, "6100");
	const gosiAccId = await getAccountByCode(db, payroll.organizationId, "2170");
	let bankAccId: string | null = null;
	if (payroll.sourceAccountId) {
		bankAccId = await getBankChartAccountId(db, payroll.organizationId, payroll.sourceAccountId);
	} else {
		bankAccId = await getAccountByCode(db, payroll.organizationId, "1110");
	}

	if (!salaryAccId || !bankAccId) return;

	const lines: any[] = [
		{ accountId: salaryAccId, debit: payroll.totalNet.add(payroll.totalGosi), credit: ZERO, description: `رواتب ${payroll.month}/${payroll.year}` },
		{ accountId: bankAccId, debit: ZERO, credit: payroll.totalNet, description: `صرف رواتب ${payroll.month}/${payroll.year}` },
	];

	if (gosiAccId && payroll.totalGosi.greaterThan(0)) {
		lines.push({ accountId: gosiAccId, debit: ZERO, credit: payroll.totalGosi, description: `تأمينات اجتماعية ${payroll.month}/${payroll.year}` });
	}

	await createJournalEntry(db, {
		organizationId: payroll.organizationId,
		date: new Date(payroll.year, payroll.month - 1, 28),
		description: `مسير رواتب ${payroll.month}/${payroll.year}`,
		referenceType: "PAYROLL",
		referenceId: payroll.id,
		isAutoGenerated: true,
		lines,
	});
}

// ========================================
// 7. Direct Payment (FinancePayment) → DR: Bank / CR: Revenue
// ========================================
export async function onOrganizationPaymentReceived(db: PrismaClient, payment: {
	id: string;
	organizationId: string;
	amount: Prisma.Decimal;
	date: Date;
	description: string;
	destinationAccountId: string;
	projectId?: string | null;
}) {
	if (!(await isAccountingEnabled(db, payment.organizationId))) return;

	const bankAccId = await getBankChartAccountId(db, payment.organizationId, payment.destinationAccountId);
	const revenueAccId = await getAccountByCode(db, payment.organizationId, "4300");
	if (!bankAccId || !revenueAccId) return;

	await createJournalEntry(db, {
		organizationId: payment.organizationId,
		date: payment.date,
		description: `مقبوضات: ${payment.description}`,
		referenceType: "ORG_PAYMENT",
		referenceId: payment.id,
		isAutoGenerated: true,
		lines: [
			{ accountId: bankAccId, debit: payment.amount, credit: ZERO, projectId: payment.projectId },
			{ accountId: revenueAccId, debit: ZERO, credit: payment.amount, projectId: payment.projectId },
		],
	});
}

// ========================================
// 8. Credit Note → DR: Revenue + VAT / CR: Receivable
// ========================================
export async function onCreditNoteIssued(db: PrismaClient, creditNote: {
	id: string;
	organizationId: string;
	number: string;
	issueDate: Date;
	clientName: string;
	totalAmount: Prisma.Decimal;
	vatAmount: Prisma.Decimal;
	projectId?: string | null;
}) {
	if (!(await isAccountingEnabled(db, creditNote.organizationId))) return;

	const receivableId = await getAccountByCode(db, creditNote.organizationId, "1120");
	const revenueId = await getAccountByCode(db, creditNote.organizationId, "4100");
	const vatPayableId = await getAccountByCode(db, creditNote.organizationId, "2130");
	if (!receivableId || !revenueId || !vatPayableId) return;

	const netAmount = creditNote.totalAmount.sub(creditNote.vatAmount);
	const lines: any[] = [
		{ accountId: revenueId, debit: netAmount, credit: ZERO, description: `إشعار دائن ${creditNote.number}`, projectId: creditNote.projectId },
		{ accountId: receivableId, debit: ZERO, credit: creditNote.totalAmount, projectId: creditNote.projectId },
	];

	if (creditNote.vatAmount.greaterThan(0)) {
		lines.push({ accountId: vatPayableId, debit: creditNote.vatAmount, credit: ZERO });
	}

	await createJournalEntry(db, {
		organizationId: creditNote.organizationId,
		date: creditNote.issueDate,
		description: `إشعار دائن ${creditNote.number} — ${creditNote.clientName}`,
		referenceType: "CREDIT_NOTE",
		referenceId: creditNote.id,
		referenceNo: creditNote.number,
		isAutoGenerated: true,
		lines,
	});
}
