import type { CategorySpecConfig } from "../spec-types";

export const DOORS_WINDOWS_CATALOG: Record<string, CategorySpecConfig> = {
	// ══════════════════════════════════════════════════════════════
	// الفئة 11: أبواب داخلية
	// ══════════════════════════════════════════════════════════════
	FINISHING_INTERIOR_DOORS: {
		categoryKey: "FINISHING_INTERIOR_DOORS",
		specTypes: [
			{
				key: "wpc",
				label: "WPC",
				labelEn: "WPC Door",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "door_leaf",
						name: "ضلفة WPC",
						nameEn: "WPC Door Leaf",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "frame",
						name: "حلق",
						nameEn: "Frame",
						unit: "طقم",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "lock",
						name: "كالون",
						nameEn: "Lock",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "hinges",
						name: "مفصلات",
						nameEn: "Hinges",
						unit: "عدد",
						ratePerUnit: 3,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handle",
						name: "مقبض",
						nameEn: "Handle",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "stopper",
						name: "وقّاف",
						nameEn: "Door Stopper",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 5,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "fixing_kit",
						name: "مسامير/فيشر",
						nameEn: "Fixing Kit",
						unit: "طقم",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "hdf",
				label: "HDF مضغوط",
				labelEn: "HDF Door",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "door_leaf",
						name: "ضلفة HDF",
						nameEn: "HDF Door Leaf",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "frame",
						name: "حلق",
						nameEn: "Frame",
						unit: "طقم",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "lock",
						name: "كالون",
						nameEn: "Lock",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "hinges",
						name: "مفصلات",
						nameEn: "Hinges",
						unit: "عدد",
						ratePerUnit: 3,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handle",
						name: "مقبض",
						nameEn: "Handle",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "stopper",
						name: "وقّاف",
						nameEn: "Door Stopper",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 5,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "fixing_kit",
						name: "مسامير/فيشر",
						nameEn: "Fixing Kit",
						unit: "طقم",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "solid_wood",
				label: "خشب طبيعي",
				labelEn: "Solid Wood Door",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "door_leaf",
						name: "ضلفة خشب",
						nameEn: "Wood Door Leaf",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "wood_frame",
						name: "حلق خشب",
						nameEn: "Wood Frame",
						unit: "طقم",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "lock",
						name: "كالون",
						nameEn: "Lock",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "brass_hinges",
						name: "مفصلات نحاس",
						nameEn: "Brass Hinges",
						unit: "عدد",
						ratePerUnit: 3,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handle",
						name: "مقبض",
						nameEn: "Handle",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "stopper",
						name: "وقّاف",
						nameEn: "Door Stopper",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "molding",
						name: "برواز",
						nameEn: "Molding",
						unit: "م.ط",
						ratePerUnit: 5,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "aluminum",
				label: "ألمنيوم",
				labelEn: "Aluminum Door",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "aluminum_door",
						name: "باب ألمنيوم كامل",
						nameEn: "Complete Aluminum Door",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "lock",
						name: "كالون",
						nameEn: "Lock",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handle",
						name: "مقبض",
						nameEn: "Handle",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 5,
						category: "filler",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{
						value: "AlRajhi",
						label: "الراجحي",
						labelEn: "Al Rajhi",
					},
					{
						value: "Turkish",
						label: "تركي",
						labelEn: "Turkish",
					},
					{
						value: "Chinese",
						label: "صيني",
						labelEn: "Chinese",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "AlRajhi",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "hdf",
				options: {},
			},
			{
				quality: "STANDARD",
				specTypeKey: "wpc",
				options: {},
			},
			{
				quality: "PREMIUM",
				specTypeKey: "wpc",
				options: {},
			},
			{
				quality: "LUXURY",
				specTypeKey: "solid_wood",
				options: {},
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 12: أبواب خارجية
	// ══════════════════════════════════════════════════════════════
	FINISHING_EXTERIOR_DOORS: {
		categoryKey: "FINISHING_EXTERIOR_DOORS",
		specTypes: [
			{
				key: "steel_security",
				label: "فولاذ أمني",
				labelEn: "Steel Security Door",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "steel_door",
						name: "باب فولاذ أمني كامل",
						nameEn: "Steel Security Door",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "lock",
						name: "كالون أمني",
						nameEn: "Security Lock",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handle",
						name: "مقبض",
						nameEn: "Handle",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "fixing_kit",
						name: "طقم تثبيت",
						nameEn: "Fixing Kit",
						unit: "طقم",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "solid_wood_exterior",
				label: "خشب طبيعي خارجي",
				labelEn: "Exterior Solid Wood Door",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "wood_door",
						name: "باب خشب خارجي كامل",
						nameEn: "Exterior Wood Door",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "lock",
						name: "كالون",
						nameEn: "Lock",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "brass_hinges",
						name: "مفصلات نحاس",
						nameEn: "Brass Hinges",
						unit: "عدد",
						ratePerUnit: 3,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handle",
						name: "مقبض",
						nameEn: "Handle",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "wpc_exterior",
				label: "WPC خارجي",
				labelEn: "Exterior WPC Door",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "wpc_door",
						name: "باب WPC خارجي كامل",
						nameEn: "Exterior WPC Door",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "lock",
						name: "كالون",
						nameEn: "Lock",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handle",
						name: "مقبض",
						nameEn: "Handle",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 5,
						category: "filler",
						isOptional: false,
					},
				],
			},
			{
				key: "aluminum_glass",
				label: "ألمنيوم + زجاج",
				labelEn: "Aluminum + Glass Door",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "aluminum_glass_door",
						name: "باب ألمنيوم + زجاج كامل",
						nameEn: "Aluminum + Glass Door",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "lock",
						name: "كالون",
						nameEn: "Lock",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handle",
						name: "مقبض",
						nameEn: "Handle",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 6,
						category: "filler",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{
						value: "Turkish",
						label: "تركي",
						labelEn: "Turkish",
					},
					{
						value: "Chinese",
						label: "صيني",
						labelEn: "Chinese",
					},
					{
						value: "Local",
						label: "محلي",
						labelEn: "Local",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Turkish",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "steel_security",
				options: {},
			},
			{
				quality: "STANDARD",
				specTypeKey: "steel_security",
				options: {},
			},
			{
				quality: "PREMIUM",
				specTypeKey: "solid_wood_exterior",
				options: {},
			},
			{
				quality: "LUXURY",
				specTypeKey: "solid_wood_exterior",
				options: {},
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 13: نوافذ
	// ══════════════════════════════════════════════════════════════
	FINISHING_WINDOWS: {
		categoryKey: "FINISHING_WINDOWS",
		specTypes: [
			{
				key: "aluminum_thermal_break",
				label: "ألمنيوم قطع حراري",
				labelEn: "Aluminum Thermal Break",
				defaultOptions: { hasInsectScreen: true },
				subItemRates: [
					{
						subItemKey: "aluminum_frame",
						name: "إطار ألمنيوم قطع حراري",
						nameEn: "Thermal Break Aluminum Frame",
						unit: "م.ط",
						ratePerUnit: 4.5,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "dgu_glass",
						name: "زجاج مزدوج DGU",
						nameEn: "Double Glazed Unit",
						unit: "م²",
						ratePerUnit: 0.85,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "rubber_seal",
						name: "مطاط عازل",
						nameEn: "Rubber Seal",
						unit: "م.ط",
						ratePerUnit: 8,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handle",
						name: "يد فتح",
						nameEn: "Handle",
						unit: "عدد",
						ratePerUnit: 0.5,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 4,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "screws",
						name: "مسامير",
						nameEn: "Screws",
						unit: "عدد",
						ratePerUnit: 8,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "insect_screen",
						name: "شبكة حشرات",
						nameEn: "Insect Screen",
						unit: "م²",
						ratePerUnit: 1.0,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasInsectScreen",
					},
				],
			},
			{
				key: "aluminum_standard",
				label: "ألمنيوم عادي",
				labelEn: "Standard Aluminum",
				defaultOptions: { hasInsectScreen: false },
				subItemRates: [
					{
						subItemKey: "aluminum_frame",
						name: "إطار ألمنيوم",
						nameEn: "Aluminum Frame",
						unit: "م.ط",
						ratePerUnit: 4.5,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "single_glass",
						name: "زجاج مفرد 6مم",
						nameEn: "Single Glass 6mm",
						unit: "م²",
						ratePerUnit: 0.9,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "rubber_seal",
						name: "مطاط",
						nameEn: "Rubber Seal",
						unit: "م.ط",
						ratePerUnit: 6,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handle",
						name: "يد فتح",
						nameEn: "Handle",
						unit: "عدد",
						ratePerUnit: 0.5,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 4,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "screws",
						name: "مسامير",
						nameEn: "Screws",
						unit: "عدد",
						ratePerUnit: 8,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "upvc",
				label: "UPVC",
				labelEn: "UPVC",
				defaultOptions: { hasInsectScreen: true },
				subItemRates: [
					{
						subItemKey: "upvc_frame",
						name: "إطار UPVC",
						nameEn: "UPVC Frame",
						unit: "م.ط",
						ratePerUnit: 4.5,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "dgu_glass",
						name: "زجاج مزدوج",
						nameEn: "Double Glazed Unit",
						unit: "م²",
						ratePerUnit: 0.85,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "rubber_seal",
						name: "مطاط عازل",
						nameEn: "Rubber Seal",
						unit: "م.ط",
						ratePerUnit: 8,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handle",
						name: "يد فتح",
						nameEn: "Handle",
						unit: "عدد",
						ratePerUnit: 0.5,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 4,
						category: "filler",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "hasInsectScreen",
				label: "شبكة حشرات",
				labelEn: "Insect Screen",
				type: "boolean",
				defaultValue: true,
				affectsSubItems: true,
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{
						value: "AlTayseer",
						label: "التيسير",
						labelEn: "Al Tayseer",
					},
					{
						value: "Schuco",
						label: "Schuco",
						labelEn: "Schuco",
					},
					{
						value: "Rehau",
						label: "Rehau",
						labelEn: "Rehau",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "AlTayseer",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "aluminum_standard",
				options: { hasInsectScreen: false },
			},
			{
				quality: "STANDARD",
				specTypeKey: "aluminum_thermal_break",
				options: { hasInsectScreen: true },
			},
			{
				quality: "PREMIUM",
				specTypeKey: "aluminum_thermal_break",
				options: { hasInsectScreen: true },
				suggestedBrands: ["Schuco"],
			},
			{
				quality: "LUXURY",
				specTypeKey: "upvc",
				options: { hasInsectScreen: true },
				suggestedBrands: ["Rehau"],
			},
		],
	},
};
