import type { CategorySpecConfig } from "../spec-types";

export const EXTERIOR_CATALOG: Record<string, CategorySpecConfig> = {
	// ══════════════════════════════════════════════════════════════
	// الفئة 17: درج داخلي
	// ══════════════════════════════════════════════════════════════
	FINISHING_INTERNAL_STAIRS: {
		categoryKey: "FINISHING_INTERNAL_STAIRS",
		specTypes: [
			{
				key: "marble",
				label: "رخام",
				labelEn: "Marble Stairs",
				defaultOptions: { hasNosing: false },
				subItemRates: [
					{
						subItemKey: "tread",
						name: "رخام نائمة (30سم)",
						nameEn: "Marble Tread (30cm)",
						unit: "م.ط",
						ratePerUnit: 16,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "riser",
						name: "رخام قائمة (17سم)",
						nameEn: "Marble Riser (17cm)",
						unit: "م.ط",
						ratePerUnit: 16,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "landing",
						name: "بسطة",
						nameEn: "Landing",
						unit: "م²",
						ratePerUnit: 2.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "side_skirting",
						name: "وزرة جانبية",
						nameEn: "Side Skirting",
						unit: "م.ط",
						ratePerUnit: 11,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "adhesive_mix",
						name: "لاصق (أسمنت أبيض + رمل)",
						nameEn: "Adhesive (White Cement + Sand)",
						unit: "كجم",
						ratePerUnit: 35,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "stair_nosing",
						name: "نف ستانلس",
						nameEn: "Stainless Nosing",
						unit: "م.ط",
						ratePerUnit: 16,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasNosing",
					},
				],
			},
			{
				key: "granite",
				label: "جرانيت",
				labelEn: "Granite Stairs",
				defaultOptions: { hasNosing: false },
				subItemRates: [
					{
						subItemKey: "tread",
						name: "جرانيت نائمة",
						nameEn: "Granite Tread",
						unit: "م.ط",
						ratePerUnit: 16,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "riser",
						name: "جرانيت قائمة",
						nameEn: "Granite Riser",
						unit: "م.ط",
						ratePerUnit: 16,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "landing",
						name: "بسطة",
						nameEn: "Landing",
						unit: "م²",
						ratePerUnit: 2.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "side_skirting",
						name: "وزرة جانبية",
						nameEn: "Side Skirting",
						unit: "م.ط",
						ratePerUnit: 11,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "adhesive_mix",
						name: "لاصق",
						nameEn: "Adhesive",
						unit: "كجم",
						ratePerUnit: 35,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "stair_nosing",
						name: "نف ستانلس",
						nameEn: "Stainless Nosing",
						unit: "م.ط",
						ratePerUnit: 16,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasNosing",
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "hasNosing",
				label: "نف ستانلس",
				labelEn: "Stainless Nosing",
				type: "boolean",
				defaultValue: false,
				affectsSubItems: true,
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{
						value: "Local",
						label: "محلي",
						labelEn: "Local",
					},
					{
						value: "Imported",
						label: "مستورد",
						labelEn: "Imported",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Local",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "granite",
				options: { hasNosing: false },
			},
			{
				quality: "STANDARD",
				specTypeKey: "marble",
				options: { hasNosing: false },
			},
			{
				quality: "PREMIUM",
				specTypeKey: "marble",
				options: { hasNosing: true },
			},
			{
				quality: "LUXURY",
				specTypeKey: "marble",
				options: { hasNosing: true },
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 18: درج خارجي
	// ══════════════════════════════════════════════════════════════
	FINISHING_EXTERNAL_STAIRS: {
		categoryKey: "FINISHING_EXTERNAL_STAIRS",
		specTypes: [
			{
				key: "granite",
				label: "جرانيت",
				labelEn: "Granite Stairs",
				defaultOptions: { hasNosing: false },
				subItemRates: [
					{
						subItemKey: "tread",
						name: "جرانيت نائمة",
						nameEn: "Granite Tread",
						unit: "م.ط",
						ratePerUnit: 16,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "riser",
						name: "جرانيت قائمة",
						nameEn: "Granite Riser",
						unit: "م.ط",
						ratePerUnit: 16,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "landing",
						name: "بسطة",
						nameEn: "Landing",
						unit: "م²",
						ratePerUnit: 2.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "side_skirting",
						name: "وزرة جانبية",
						nameEn: "Side Skirting",
						unit: "م.ط",
						ratePerUnit: 11,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "adhesive_mix",
						name: "لاصق",
						nameEn: "Adhesive",
						unit: "كجم",
						ratePerUnit: 35,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "stair_nosing",
						name: "نف ستانلس",
						nameEn: "Stainless Nosing",
						unit: "م.ط",
						ratePerUnit: 16,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasNosing",
					},
				],
			},
			{
				key: "stone",
				label: "حجر",
				labelEn: "Stone Stairs",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "stone_tread",
						name: "حجر نائمة",
						nameEn: "Stone Tread",
						unit: "م.ط",
						ratePerUnit: 16,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "stone_riser",
						name: "حجر قائمة",
						nameEn: "Stone Riser",
						unit: "م.ط",
						ratePerUnit: 16,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "adhesive_mix",
						name: "لاصق",
						nameEn: "Adhesive",
						unit: "كجم",
						ratePerUnit: 35,
						category: "adhesive",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "hasNosing",
				label: "نف ستانلس",
				labelEn: "Stainless Nosing",
				type: "boolean",
				defaultValue: false,
				affectsSubItems: true,
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "granite",
				options: {},
			},
			{
				quality: "STANDARD",
				specTypeKey: "granite",
				options: {},
			},
			{
				quality: "PREMIUM",
				specTypeKey: "granite",
				options: { hasNosing: true },
			},
			{
				quality: "LUXURY",
				specTypeKey: "granite",
				options: { hasNosing: true },
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 19: درابزين
	// ══════════════════════════════════════════════════════════════
	FINISHING_RAILINGS: {
		categoryKey: "FINISHING_RAILINGS",
		specTypes: [
			{
				key: "wrought_iron",
				label: "حديد مشغول",
				labelEn: "Wrought Iron",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "wrought_iron",
						name: "حديد مشغول",
						nameEn: "Wrought Iron",
						unit: "م.ط",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "iron_paint",
						name: "دهان حديد",
						nameEn: "Iron Paint",
						unit: "لتر",
						ratePerUnit: 0.3,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "wood_caps",
						name: "كابات خشب",
						nameEn: "Wood Caps",
						unit: "م.ط",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "stainless_steel",
				label: "ستانلس ستيل",
				labelEn: "Stainless Steel",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "ss_tubes",
						name: "أنابيب ستانلس",
						nameEn: "Stainless Tubes",
						unit: "م.ط",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "ss_caps",
						name: "كابات ستانلس",
						nameEn: "Stainless Caps",
						unit: "م.ط",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "fixing_screws",
						name: "مسامير تثبيت",
						nameEn: "Fixing Screws",
						unit: "عدد",
						ratePerUnit: 4,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "glass_stainless",
				label: "زجاج + ستانلس",
				labelEn: "Glass + Stainless",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "tempered_glass",
						name: "زجاج سيكوريت 10مم",
						nameEn: "10mm Tempered Glass",
						unit: "م²",
						ratePerUnit: 0.9,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "ss_caps",
						name: "كابات ستانلس",
						nameEn: "Stainless Caps",
						unit: "م.ط",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "clips",
						name: "مشابك",
						nameEn: "Clips",
						unit: "عدد",
						ratePerUnit: 6,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "aluminum",
				label: "ألمنيوم",
				labelEn: "Aluminum",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "aluminum_sections",
						name: "قطاعات ألمنيوم",
						nameEn: "Aluminum Sections",
						unit: "م.ط",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "screws",
						name: "مسامير",
						nameEn: "Screws",
						unit: "عدد",
						ratePerUnit: 4,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "wood",
				label: "خشب",
				labelEn: "Wood",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "wood_railing",
						name: "درابزين خشب",
						nameEn: "Wood Railing",
						unit: "م.ط",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "varnish",
						name: "برنيش",
						nameEn: "Varnish",
						unit: "لتر",
						ratePerUnit: 0.2,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "screws",
						name: "مسامير",
						nameEn: "Screws",
						unit: "عدد",
						ratePerUnit: 6,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{
						value: "Local",
						label: "محلي",
						labelEn: "Local",
					},
					{
						value: "Imported",
						label: "مستورد",
						labelEn: "Imported",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Local",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "wrought_iron",
				options: {},
			},
			{
				quality: "STANDARD",
				specTypeKey: "wrought_iron",
				options: {},
			},
			{
				quality: "PREMIUM",
				specTypeKey: "stainless_steel",
				options: {},
			},
			{
				quality: "LUXURY",
				specTypeKey: "glass_stainless",
				options: {},
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 20: واجهات حجرية
	// ══════════════════════════════════════════════════════════════
	FINISHING_STONE_FACADE: {
		categoryKey: "FINISHING_STONE_FACADE",
		specTypes: [
			{
				key: "natural_riyadh",
				label: "حجر رياضي طبيعي",
				labelEn: "Natural Riyadh Stone",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "stone",
						name: "حجر",
						nameEn: "Stone",
						unit: "م²",
						ratePerUnit: 1.1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "adhesive_mix",
						name: "خلطة لصق",
						nameEn: "Adhesive Mix",
						unit: "كجم",
						ratePerUnit: 18,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "fixing_pins",
						name: "مسامير تثبيت",
						nameEn: "Fixing Pins",
						unit: "عدد",
						ratePerUnit: 5,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "tie_wire",
						name: "سلك ربط",
						nameEn: "Tie Wire",
						unit: "كجم",
						ratePerUnit: 0.1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "joint_mortar",
						name: "مونة فواصل",
						nameEn: "Joint Mortar",
						unit: "كجم",
						ratePerUnit: 1.0,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "protection_material",
						name: "مادة حماية",
						nameEn: "Protection Material",
						unit: "لتر",
						ratePerUnit: 0.15,
						category: "protection",
						isOptional: false,
					},
					{
						subItemKey: "scaffolding",
						name: "سقالات",
						nameEn: "Scaffolding",
						unit: "م²",
						ratePerUnit: 1.0,
						category: "tool",
						isOptional: false,
					},
				],
			},
			{
				key: "natural_imported",
				label: "حجر طبيعي مستورد",
				labelEn: "Natural Imported Stone",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "stone",
						name: "حجر مستورد",
						nameEn: "Imported Stone",
						unit: "م²",
						ratePerUnit: 1.1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "adhesive_mix",
						name: "خلطة لصق",
						nameEn: "Adhesive Mix",
						unit: "كجم",
						ratePerUnit: 18,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "fixing_pins",
						name: "مسامير تثبيت",
						nameEn: "Fixing Pins",
						unit: "عدد",
						ratePerUnit: 5,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "tie_wire",
						name: "سلك ربط",
						nameEn: "Tie Wire",
						unit: "كجم",
						ratePerUnit: 0.1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "joint_mortar",
						name: "مونة فواصل",
						nameEn: "Joint Mortar",
						unit: "كجم",
						ratePerUnit: 1.0,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "protection_material",
						name: "مادة حماية",
						nameEn: "Protection Material",
						unit: "لتر",
						ratePerUnit: 0.15,
						category: "protection",
						isOptional: false,
					},
					{
						subItemKey: "scaffolding",
						name: "سقالات",
						nameEn: "Scaffolding",
						unit: "م²",
						ratePerUnit: 1.0,
						category: "tool",
						isOptional: false,
					},
				],
			},
			{
				key: "manufactured",
				label: "حجر صناعي",
				labelEn: "Manufactured Stone",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "manufactured_stone",
						name: "حجر صناعي",
						nameEn: "Manufactured Stone",
						unit: "م²",
						ratePerUnit: 1.1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "stone_adhesive",
						name: "غراء حجر",
						nameEn: "Stone Adhesive",
						unit: "كجم",
						ratePerUnit: 5,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "grout",
						name: "فواصل",
						nameEn: "Grout",
						unit: "كجم",
						ratePerUnit: 0.5,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "protection_material",
						name: "مادة حماية",
						nameEn: "Protection Material",
						unit: "لتر",
						ratePerUnit: 0.15,
						category: "protection",
						isOptional: false,
					},
					{
						subItemKey: "scaffolding",
						name: "سقالات",
						nameEn: "Scaffolding",
						unit: "م²",
						ratePerUnit: 1.0,
						category: "tool",
						isOptional: false,
					},
				],
			},
			{
				key: "grc",
				label: "GRC",
				labelEn: "GRC Panels",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "grc_panels",
						name: "ألواح GRC",
						nameEn: "GRC Panels",
						unit: "م²",
						ratePerUnit: 1.1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "fixing_structure",
						name: "هيكل تثبيت",
						nameEn: "Fixing Structure",
						unit: "م²",
						ratePerUnit: 1.0,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "screws",
						name: "مسامير",
						nameEn: "Screws",
						unit: "عدد",
						ratePerUnit: 8,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "silicone_joints",
						name: "سيليكون فواصل",
						nameEn: "Silicone Joints",
						unit: "م.ط",
						ratePerUnit: 0.5,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "scaffolding",
						name: "سقالات",
						nameEn: "Scaffolding",
						unit: "م²",
						ratePerUnit: 1.0,
						category: "tool",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{
						value: "Local",
						label: "محلي",
						labelEn: "Local",
					},
					{
						value: "Syrian",
						label: "سوري",
						labelEn: "Syrian",
					},
					{
						value: "Jordanian",
						label: "أردني",
						labelEn: "Jordanian",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Local",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "manufactured",
				options: {},
			},
			{
				quality: "STANDARD",
				specTypeKey: "natural_riyadh",
				options: {},
			},
			{
				quality: "PREMIUM",
				specTypeKey: "natural_riyadh",
				options: {},
			},
			{
				quality: "LUXURY",
				specTypeKey: "natural_imported",
				options: {},
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 21: ديكور واجهات — مقطوعية
	// ══════════════════════════════════════════════════════════════
	FINISHING_FACADE_DECOR: {
		categoryKey: "FINISHING_FACADE_DECOR",
		specTypes: [
			{
				key: "grc_decor",
				label: "ديكور GRC",
				labelEn: "GRC Decor",
				defaultOptions: {},
				subItemRates: [],
			},
			{
				key: "gypsum_decor",
				label: "ديكور جبس",
				labelEn: "Gypsum Decor",
				defaultOptions: {},
				subItemRates: [],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [],
		qualityPresets: [
			{ quality: "ECONOMY", specTypeKey: "gypsum_decor", options: {} },
			{ quality: "STANDARD", specTypeKey: "grc_decor", options: {} },
			{ quality: "PREMIUM", specTypeKey: "grc_decor", options: {} },
			{ quality: "LUXURY", specTypeKey: "grc_decor", options: {} },
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 22: أرضيات حوش
	// ══════════════════════════════════════════════════════════════
	FINISHING_YARD_PAVING: {
		categoryKey: "FINISHING_YARD_PAVING",
		specTypes: [
			{
				key: "interlock_6cm",
				label: "إنترلوك 6سم",
				labelEn: "6cm Interlock",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "interlock",
						name: "إنترلوك",
						nameEn: "Interlock",
						unit: "م²",
						ratePerUnit: 1.08,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "leveling_sand",
						name: "رمل تسوية",
						nameEn: "Leveling Sand",
						unit: "م³",
						ratePerUnit: 0.04,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "base_course",
						name: "حصمة (بيس كورس)",
						nameEn: "Base Course",
						unit: "م³",
						ratePerUnit: 0.12,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "joint_sand",
						name: "رمل فواصل",
						nameEn: "Joint Sand",
						unit: "كجم",
						ratePerUnit: 5,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "curbs",
						name: "بردورات",
						nameEn: "Curbs",
						unit: "م.ط",
						ratePerUnit: 0.2,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "interlock_8cm",
				label: "إنترلوك 8سم",
				labelEn: "8cm Interlock",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "interlock",
						name: "إنترلوك 8سم",
						nameEn: "8cm Interlock",
						unit: "م²",
						ratePerUnit: 1.08,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "leveling_sand",
						name: "رمل تسوية",
						nameEn: "Leveling Sand",
						unit: "م³",
						ratePerUnit: 0.04,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "base_course",
						name: "حصمة (بيس كورس)",
						nameEn: "Base Course",
						unit: "م³",
						ratePerUnit: 0.15,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "joint_sand",
						name: "رمل فواصل",
						nameEn: "Joint Sand",
						unit: "كجم",
						ratePerUnit: 5,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "curbs",
						name: "بردورات",
						nameEn: "Curbs",
						unit: "م.ط",
						ratePerUnit: 0.2,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "outdoor_tiles",
				label: "بلاط خارجي",
				labelEn: "Outdoor Tiles",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "outdoor_tiles",
						name: "بلاط خارجي",
						nameEn: "Outdoor Tiles",
						unit: "م²",
						ratePerUnit: 1.08,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "outdoor_adhesive",
						name: "غراء خارجي",
						nameEn: "Outdoor Adhesive",
						unit: "كجم",
						ratePerUnit: 5,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "grout",
						name: "فواصل",
						nameEn: "Grout",
						unit: "كجم",
						ratePerUnit: 0.5,
						category: "filler",
						isOptional: false,
					},
				],
			},
			{
				key: "stamped_concrete",
				label: "خرسانة مطبوعة",
				labelEn: "Stamped Concrete",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "concrete",
						name: "خرسانة",
						nameEn: "Concrete",
						unit: "م³",
						ratePerUnit: 0.08,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "pigment",
						name: "صبغة",
						nameEn: "Pigment",
						unit: "كجم",
						ratePerUnit: 0.5,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "stamp_material",
						name: "مادة طبع",
						nameEn: "Stamp Material",
						unit: "كجم",
						ratePerUnit: 0.1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "protection_varnish",
						name: "ورنيش حماية",
						nameEn: "Protection Varnish",
						unit: "لتر",
						ratePerUnit: 0.15,
						category: "protection",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{
						value: "Local",
						label: "محلي",
						labelEn: "Local",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Local",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "interlock_6cm",
				options: {},
			},
			{
				quality: "STANDARD",
				specTypeKey: "interlock_8cm",
				options: {},
			},
			{
				quality: "PREMIUM",
				specTypeKey: "outdoor_tiles",
				options: {},
			},
			{
				quality: "LUXURY",
				specTypeKey: "stamped_concrete",
				options: {},
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 23: سور وبوابات
	// ══════════════════════════════════════════════════════════════
	FINISHING_FENCE_GATES: {
		categoryKey: "FINISHING_FENCE_GATES",
		specTypes: [
			{
				key: "iron_gate",
				label: "بوابة حديد",
				labelEn: "Iron Gate",
				defaultOptions: { hasMotor: false, hasRemote: false },
				subItemRates: [
					{
						subItemKey: "iron_gate",
						name: "بوابة حديد",
						nameEn: "Iron Gate",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "electric_motor",
						name: "محرك كهربائي",
						nameEn: "Electric Motor",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasMotor",
					},
					{
						subItemKey: "remote",
						name: "ريموت",
						nameEn: "Remote Control",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasRemote",
					},
				],
			},
			{
				key: "aluminum_gate",
				label: "بوابة ألمنيوم",
				labelEn: "Aluminum Gate",
				defaultOptions: { hasMotor: false, hasRemote: false },
				subItemRates: [
					{
						subItemKey: "aluminum_gate",
						name: "بوابة ألمنيوم",
						nameEn: "Aluminum Gate",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "electric_motor",
						name: "محرك كهربائي",
						nameEn: "Electric Motor",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasMotor",
					},
					{
						subItemKey: "remote",
						name: "ريموت",
						nameEn: "Remote Control",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasRemote",
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "hasMotor",
				label: "محرك كهربائي",
				labelEn: "Electric Motor",
				type: "boolean",
				defaultValue: false,
				affectsSubItems: true,
			},
			{
				key: "hasRemote",
				label: "ريموت",
				labelEn: "Remote Control",
				type: "boolean",
				defaultValue: false,
				affectsSubItems: true,
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "iron_gate",
				options: { hasMotor: false },
			},
			{
				quality: "STANDARD",
				specTypeKey: "iron_gate",
				options: { hasMotor: true, hasRemote: true },
			},
			{
				quality: "PREMIUM",
				specTypeKey: "aluminum_gate",
				options: { hasMotor: true, hasRemote: true },
			},
			{
				quality: "LUXURY",
				specTypeKey: "aluminum_gate",
				options: { hasMotor: true, hasRemote: true },
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 24: تنسيق حدائق
	// ══════════════════════════════════════════════════════════════
	FINISHING_LANDSCAPING: {
		categoryKey: "FINISHING_LANDSCAPING",
		specTypes: [
			{
				key: "artificial_grass",
				label: "عشب صناعي",
				labelEn: "Artificial Grass",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "artificial_grass",
						name: "عشب صناعي",
						nameEn: "Artificial Grass",
						unit: "م²",
						ratePerUnit: 1.05,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "natural_grass",
				label: "عشب طبيعي",
				labelEn: "Natural Grass",
				defaultOptions: { hasIrrigation: false },
				subItemRates: [
					{
						subItemKey: "natural_grass",
						name: "عشب طبيعي",
						nameEn: "Natural Grass",
						unit: "م²",
						ratePerUnit: 1.05,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "soil",
						name: "تربة زراعية",
						nameEn: "Agricultural Soil",
						unit: "م³",
						ratePerUnit: 0.15,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "irrigation",
						name: "شبكة ري",
						nameEn: "Irrigation Network",
						unit: "م²",
						ratePerUnit: 1.0,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasIrrigation",
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "hasIrrigation",
				label: "شبكة ري",
				labelEn: "Irrigation Network",
				type: "boolean",
				defaultValue: false,
				affectsSubItems: true,
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "artificial_grass",
				options: {},
			},
			{
				quality: "STANDARD",
				specTypeKey: "artificial_grass",
				options: {},
			},
			{
				quality: "PREMIUM",
				specTypeKey: "natural_grass",
				options: { hasIrrigation: true },
			},
			{
				quality: "LUXURY",
				specTypeKey: "natural_grass",
				options: { hasIrrigation: true },
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 25: سطح — عزل مائي + بلاط
	// ══════════════════════════════════════════════════════════════
	FINISHING_ROOF: {
		categoryKey: "FINISHING_ROOF",
		specTypes: [
			{
				key: "waterproof_tiles",
				label: "عزل مائي + بلاط",
				labelEn: "Waterproofing + Tiles",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "primer",
						name: "برايمر",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.25,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "waterproofing",
						name: "مادة عزل",
						nameEn: "Waterproofing Material",
						unit: "كجم",
						ratePerUnit: 1.75,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "roof_tiles",
						name: "بلاط سطح",
						nameEn: "Roof Tiles",
						unit: "م²",
						ratePerUnit: 1.08,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "adhesive",
						name: "غراء",
						nameEn: "Adhesive",
						unit: "كجم",
						ratePerUnit: 4.5,
						category: "adhesive",
						isOptional: false,
					},
				],
			},
			{
				key: "waterproof_only",
				label: "عزل مائي فقط",
				labelEn: "Waterproofing Only",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "primer",
						name: "برايمر",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.25,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "waterproofing",
						name: "مادة عزل",
						nameEn: "Waterproofing Material",
						unit: "كجم",
						ratePerUnit: 1.75,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "waterproof_only",
				options: {},
			},
			{
				quality: "STANDARD",
				specTypeKey: "waterproof_tiles",
				options: {},
			},
			{
				quality: "PREMIUM",
				specTypeKey: "waterproof_tiles",
				options: {},
			},
			{
				quality: "LUXURY",
				specTypeKey: "waterproof_tiles",
				options: {},
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 26: ديكور داخلي — مقطوعية
	// ══════════════════════════════════════════════════════════════
	FINISHING_INTERIOR_DECOR: {
		categoryKey: "FINISHING_INTERIOR_DECOR",
		specTypes: [
			{
				key: "gypsum_decor",
				label: "ديكور جبس",
				labelEn: "Gypsum Decor",
				defaultOptions: {},
				subItemRates: [],
			},
			{
				key: "wood_decor",
				label: "ديكور خشب",
				labelEn: "Wood Decor",
				defaultOptions: {},
				subItemRates: [],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [],
		qualityPresets: [
			{ quality: "ECONOMY", specTypeKey: "gypsum_decor", options: {} },
			{ quality: "STANDARD", specTypeKey: "gypsum_decor", options: {} },
			{ quality: "PREMIUM", specTypeKey: "wood_decor", options: {} },
			{ quality: "LUXURY", specTypeKey: "wood_decor", options: {} },
		],
	},
};
