import type { CategorySpecConfig, SpecTypeOption } from "../spec-types";

// Helper: common tile sub-items for porcelain/ceramic
function tileSubItems(
	tileRate: number,
	adhesiveRate: number,
	adhesiveGrade: string,
	groutRate: number,
	crossCount: number,
): SpecTypeOption["subItemRates"] {
	return [
		{
			subItemKey: "tiles",
			name: "بلاط",
			nameEn: "Tiles",
			unit: "م²",
			ratePerUnit: tileRate,
			category: "main",
			isOptional: false,
		},
		{
			subItemKey: "adhesive",
			name: `غراء ${adhesiveGrade}`,
			nameEn: `${adhesiveGrade} Adhesive`,
			unit: "كجم",
			ratePerUnit: adhesiveRate,
			category: "adhesive",
			isOptional: false,
		},
		{
			subItemKey: "grout",
			name: "فواصل",
			nameEn: "Grout",
			unit: "كجم",
			ratePerUnit: groutRate,
			category: "filler",
			isOptional: false,
		},
		{
			subItemKey: "crosses",
			name: "صلبان",
			nameEn: "Tile Crosses",
			unit: "عدد",
			ratePerUnit: crossCount,
			category: "accessory",
			isOptional: false,
		},
		{
			subItemKey: "skirting",
			name: "وزرات",
			nameEn: "Skirting",
			unit: "م.ط",
			ratePerUnit: 0.3,
			category: "accessory",
			isOptional: true,
			conditionalOn: "hasSkirting",
		},
	];
}

export const FLOORING_CATALOG: Record<string, CategorySpecConfig> = {
	// ══════════════════════════════════════════════════════════════
	// الفئة 8: أرضيات
	// ══════════════════════════════════════════════════════════════
	FINISHING_FLOOR_TILES: {
		categoryKey: "FINISHING_FLOOR_TILES",
		specTypes: [
			{
				key: "porcelain_60x60",
				label: "بورسلان 60×60",
				labelEn: "Porcelain 60x60",
				defaultOptions: {
					installation: "adhesive",
					hasScreed: true,
					groutType: "normal",
					groutSize: 2,
					hasSkirting: "same_tile",
				},
				subItemRates: [
					...tileSubItems(1.1, 4.5, "C1", 0.4, 12),
					{
						subItemKey: "aluminum_corners",
						name: "زوايا ألمنيوم",
						nameEn: "Aluminum Corners",
						unit: "م.ط",
						ratePerUnit: 0.05,
						category: "accessory",
						isOptional: true,
					},
				],
			},
			{
				key: "porcelain_80x80",
				label: "بورسلان 80×80",
				labelEn: "Porcelain 80x80",
				defaultOptions: {
					installation: "adhesive",
					hasScreed: true,
					groutType: "normal",
					groutSize: 2,
					hasSkirting: "same_tile",
				},
				subItemRates: tileSubItems(1.1, 4.5, "C1", 0.3, 8),
			},
			{
				key: "porcelain_120x120",
				label: "بورسلان 120×120",
				labelEn: "Porcelain 120x120",
				defaultOptions: {
					installation: "adhesive",
					hasScreed: true,
					groutType: "normal",
					groutSize: 2,
					hasSkirting: "same_tile",
				},
				subItemRates: tileSubItems(1.08, 5.0, "C2", 0.2, 5),
			},
			{
				key: "porcelain_60x120",
				label: "بورسلان 60×120",
				labelEn: "Porcelain 60x120",
				defaultOptions: {
					installation: "adhesive",
					hasScreed: true,
					groutType: "normal",
					groutSize: 2,
					hasSkirting: "same_tile",
				},
				subItemRates: tileSubItems(1.1, 4.5, "C1", 0.3, 8),
			},
			{
				key: "ceramic_40x40",
				label: "سيراميك 40×40",
				labelEn: "Ceramic 40x40",
				defaultOptions: {
					installation: "adhesive",
					hasScreed: true,
					groutType: "normal",
					groutSize: 3,
					hasSkirting: "same_tile",
				},
				subItemRates: tileSubItems(1.1, 4.0, "C1", 0.5, 15),
			},
			{
				key: "ceramic_30x30",
				label: "سيراميك 30×30",
				labelEn: "Ceramic 30x30",
				defaultOptions: {
					installation: "adhesive",
					hasScreed: true,
					groutType: "normal",
					groutSize: 3,
					hasSkirting: "same_tile",
				},
				subItemRates: tileSubItems(1.12, 4.0, "C1", 0.6, 18),
			},
			{
				key: "marble",
				label: "رخام طبيعي",
				labelEn: "Natural Marble",
				defaultOptions: {
					installation: "cement_mix",
					hasScreed: false,
					hasSkirting: "same_tile",
				},
				subItemRates: [
					{
						subItemKey: "marble_tiles",
						name: "رخام",
						nameEn: "Marble",
						unit: "م²",
						ratePerUnit: 1.1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "cement_mix",
						name: "خلطة لصق (أسمنت أبيض + رمل)",
						nameEn: "Adhesive Mix (White Cement + Sand)",
						unit: "كجم",
						ratePerUnit: 18,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "white_cement_grout",
						name: "فواصل أسمنت أبيض",
						nameEn: "White Cement Grout",
						unit: "كجم",
						ratePerUnit: 0.2,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "polishing",
						name: "مادة تلميع",
						nameEn: "Polishing Material",
						unit: "لتر",
						ratePerUnit: 0.05,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "skirting",
						name: "وزرات",
						nameEn: "Skirting",
						unit: "م.ط",
						ratePerUnit: 0.3,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasSkirting",
					},
				],
			},
			{
				key: "granite",
				label: "جرانيت",
				labelEn: "Granite",
				defaultOptions: {
					installation: "cement_mix",
					hasScreed: false,
					hasSkirting: "same_tile",
				},
				subItemRates: [
					{
						subItemKey: "granite_tiles",
						name: "جرانيت",
						nameEn: "Granite",
						unit: "م²",
						ratePerUnit: 1.1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "cement_mix",
						name: "خلطة لصق",
						nameEn: "Adhesive Mix",
						unit: "كجم",
						ratePerUnit: 18,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "grout",
						name: "فواصل",
						nameEn: "Grout",
						unit: "كجم",
						ratePerUnit: 0.2,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "skirting",
						name: "وزرات",
						nameEn: "Skirting",
						unit: "م.ط",
						ratePerUnit: 0.3,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasSkirting",
					},
				],
			},
			{
				key: "spc",
				label: "SPC/باركيه",
				labelEn: "SPC/Parquet",
				defaultOptions: {
					installation: "click",
					hasScreed: true,
					hasSkirting: "pvc",
				},
				subItemRates: [
					{
						subItemKey: "spc_boards",
						name: "ألواح SPC",
						nameEn: "SPC Boards",
						unit: "م²",
						ratePerUnit: 1.08,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "foam_underlay",
						name: "فوم عازل",
						nameEn: "Foam Underlay",
						unit: "م²",
						ratePerUnit: 1.05,
						category: "protection",
						isOptional: false,
					},
					{
						subItemKey: "pvc_skirting",
						name: "وزرات PVC",
						nameEn: "PVC Skirting",
						unit: "م.ط",
						ratePerUnit: 0.3,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasSkirting",
					},
					{
						subItemKey: "edge_strip",
						name: "شريط حواف",
						nameEn: "Edge Strip",
						unit: "م.ط",
						ratePerUnit: 0.05,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "vinyl",
				label: "فينيل",
				labelEn: "Vinyl",
				defaultOptions: {
					installation: "adhesive",
					hasScreed: true,
					hasSkirting: "pvc",
				},
				subItemRates: [
					{
						subItemKey: "vinyl_sheets",
						name: "فينيل",
						nameEn: "Vinyl",
						unit: "م²",
						ratePerUnit: 1.05,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "vinyl_adhesive",
						name: "لاصق",
						nameEn: "Adhesive",
						unit: "كجم",
						ratePerUnit: 0.3,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "pvc_skirting",
						name: "وزرات PVC",
						nameEn: "PVC Skirting",
						unit: "م.ط",
						ratePerUnit: 0.3,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasSkirting",
					},
				],
			},
			{
				key: "epoxy",
				label: "إيبوكسي",
				labelEn: "Epoxy",
				defaultOptions: { installation: "adhesive", hasScreed: true },
				subItemRates: [
					{
						subItemKey: "epoxy_primer",
						name: "أساس إيبوكسي",
						nameEn: "Epoxy Primer",
						unit: "كجم",
						ratePerUnit: 0.2,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "epoxy_coating",
						name: "إيبوكسي",
						nameEn: "Epoxy Coating",
						unit: "كجم",
						ratePerUnit: 1.5,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "installation",
				label: "طريقة التركيب",
				labelEn: "Installation Method",
				type: "select",
				options: [
					{
						value: "adhesive",
						label: "غراء",
						labelEn: "Adhesive",
					},
					{
						value: "cement_mix",
						label: "خلطة أسمنتية",
						labelEn: "Cement Mix",
					},
					{
						value: "click",
						label: "تعشيق (click)",
						labelEn: "Click",
					},
					{
						value: "glue",
						label: "لصق",
						labelEn: "Glue",
					},
				],
				defaultValue: "adhesive",
			},
			{
				key: "hasScreed",
				label: "بطحة أسمنتية",
				labelEn: "Cement Screed",
				type: "boolean",
				defaultValue: true,
				affectsSubItems: true,
			},
			{
				key: "groutType",
				label: "نوع الفواصل",
				labelEn: "Grout Type",
				type: "select",
				options: [
					{
						value: "normal",
						label: "عادي",
						labelEn: "Normal",
					},
					{
						value: "epoxy",
						label: "إيبوكسي",
						labelEn: "Epoxy",
					},
				],
				defaultValue: "normal",
			},
			{
				key: "groutSize",
				label: "حجم الفاصل (مم)",
				labelEn: "Grout Size (mm)",
				type: "select",
				options: [
					{ value: "1", label: "1 مم", labelEn: "1mm" },
					{ value: "2", label: "2 مم", labelEn: "2mm" },
					{ value: "3", label: "3 مم", labelEn: "3mm" },
					{ value: "5", label: "5 مم", labelEn: "5mm" },
				],
				defaultValue: "2",
			},
			{
				key: "hasSkirting",
				label: "وزرات",
				labelEn: "Skirting",
				type: "select",
				options: [
					{
						value: "same_tile",
						label: "نفس البلاط",
						labelEn: "Same Tile",
					},
					{ value: "pvc", label: "PVC", labelEn: "PVC" },
					{ value: "wood", label: "خشب", labelEn: "Wood" },
					{ value: "none", label: "لا", labelEn: "None" },
				],
				defaultValue: "same_tile",
				affectsSubItems: true,
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{ value: "RAK", label: "RAK", labelEn: "RAK" },
					{
						value: "SaudiCeramics",
						label: "Saudi Ceramics",
						labelEn: "Saudi Ceramics",
					},
					{
						value: "Porcelanosa",
						label: "Porcelanosa",
						labelEn: "Porcelanosa",
					},
					{
						value: "Kajaria",
						label: "Kajaria",
						labelEn: "Kajaria",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "RAK",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "ceramic_40x40",
				options: {
					installation: "adhesive",
					hasScreed: true,
					groutType: "normal",
				},
				suggestedBrands: ["SaudiCeramics"],
			},
			{
				quality: "STANDARD",
				specTypeKey: "porcelain_60x60",
				options: {
					installation: "adhesive",
					hasScreed: true,
					groutType: "normal",
				},
				suggestedBrands: ["RAK", "SaudiCeramics"],
			},
			{
				quality: "PREMIUM",
				specTypeKey: "porcelain_120x120",
				options: {
					installation: "adhesive",
					hasScreed: true,
					groutType: "normal",
				},
				suggestedBrands: ["RAK", "Porcelanosa"],
			},
			{
				quality: "LUXURY",
				specTypeKey: "marble",
				options: {
					installation: "cement_mix",
					hasScreed: false,
				},
				suggestedBrands: ["Porcelanosa"],
			},
		],
	},
};
