import type { CategorySpecConfig } from "../spec-types";

export const INSULATION_CATALOG: Record<string, CategorySpecConfig> = {
	// ══════════════════════════════════════════════════════════════
	// الفئة 1: العزل المائي
	// ══════════════════════════════════════════════════════════════
	FINISHING_WATERPROOFING: {
		categoryKey: "FINISHING_WATERPROOFING",
		specTypes: [
			{
				key: "cement_flexible",
				label: "عزل أسمنتي مرن",
				labelEn: "Flexible Cement Waterproofing",
				defaultOptions: {
					location: "bathrooms",
					layers: 2,
					hasReinforcement: false,
					hasProtection: "none",
				},
				subItemRates: [
					{
						subItemKey: "primer",
						name: "برايمر",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.25,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "component_a",
						name: "مكون A أسمنتي",
						nameEn: "Component A (Cement)",
						unit: "كجم",
						ratePerUnit: 1.75,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "component_b",
						name: "مكون B سائل",
						nameEn: "Component B (Liquid)",
						unit: "لتر",
						ratePerUnit: 0.6,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "reinforcement_tape",
						name: "شريط تقوية",
						nameEn: "Reinforcement Tape",
						unit: "م.ط",
						ratePerUnit: 0.4,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasReinforcement",
					},
					{
						subItemKey: "fiber_mesh",
						name: "شبك فايبر",
						nameEn: "Fiber Mesh",
						unit: "م²",
						ratePerUnit: 1.1,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasReinforcement",
					},
				],
			},
			{
				key: "bitumen_rolls",
				label: "رولات بيتومينية",
				labelEn: "Bitumen Rolls",
				defaultOptions: {
					location: "foundations",
					layers: 2,
					hasReinforcement: false,
					hasProtection: "none",
				},
				subItemRates: [
					{
						subItemKey: "bitumen_primer",
						name: "برايمر بيتوميني",
						nameEn: "Bitumen Primer",
						unit: "لتر",
						ratePerUnit: 0.4,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "roll_4mm",
						name: "رول 4مم",
						nameEn: "4mm Roll",
						unit: "م²",
						ratePerUnit: 1.15,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "roll_3mm",
						name: "رول 3مم",
						nameEn: "3mm Roll",
						unit: "م²",
						ratePerUnit: 1.15,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "mastic",
						name: "ماستك",
						nameEn: "Mastic",
						unit: "كجم",
						ratePerUnit: 0.3,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "protection_plaster",
						name: "لياسة حماية",
						nameEn: "Protection Plaster",
						unit: "م²",
						ratePerUnit: 1.0,
						category: "protection",
						isOptional: true,
						conditionalOn: "hasProtection",
					},
				],
			},
			{
				key: "liquid_bitumen",
				label: "سائل بيتوميني",
				labelEn: "Liquid Bitumen",
				defaultOptions: { location: "bathrooms", layers: 2 },
				subItemRates: [
					{
						subItemKey: "primer",
						name: "برايمر",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.3,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "liquid_bitumen",
						name: "سائل بيتوميني",
						nameEn: "Liquid Bitumen",
						unit: "كجم",
						ratePerUnit: 1.5,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "polyurethane",
				label: "بولي يوريثان (PU)",
				labelEn: "Polyurethane (PU)",
				defaultOptions: { location: "roof", layers: 2 },
				subItemRates: [
					{
						subItemKey: "primer",
						name: "برايمر",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.2,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "pu_liquid",
						name: "PU سائل",
						nameEn: "PU Liquid",
						unit: "كجم",
						ratePerUnit: 1.5,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "epoxy",
				label: "إيبوكسي",
				labelEn: "Epoxy",
				defaultOptions: { location: "tanks", layers: 2 },
				subItemRates: [
					{
						subItemKey: "epoxy_primer",
						name: "برايمر إيبوكسي",
						nameEn: "Epoxy Primer",
						unit: "لتر",
						ratePerUnit: 0.15,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "epoxy_coating",
						name: "طلاء إيبوكسي",
						nameEn: "Epoxy Coating",
						unit: "كجم",
						ratePerUnit: 0.5,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "location",
				label: "موقع التطبيق",
				labelEn: "Application Location",
				type: "select",
				options: [
					{
						value: "foundations",
						label: "أساسات",
						labelEn: "Foundations",
					},
					{
						value: "bathrooms",
						label: "حمامات",
						labelEn: "Bathrooms",
					},
					{ value: "roof", label: "سطح", labelEn: "Roof" },
					{
						value: "planters",
						label: "أحواض زراعية",
						labelEn: "Planters",
					},
					{ value: "pool", label: "مسبح", labelEn: "Pool" },
					{ value: "tank", label: "خزان", labelEn: "Tank" },
				],
				defaultValue: "bathrooms",
			},
			{
				key: "layers",
				label: "عدد الطبقات",
				labelEn: "Number of Layers",
				type: "select",
				options: [
					{ value: "2", label: "2", labelEn: "2" },
					{ value: "3", label: "3", labelEn: "3" },
				],
				defaultValue: "2",
				affectsSubItems: true,
			},
			{
				key: "hasReinforcement",
				label: "هل يوجد شريط تقوية",
				labelEn: "Has Reinforcement Tape",
				type: "boolean",
				defaultValue: false,
				affectsSubItems: true,
			},
			{
				key: "hasProtection",
				label: "طبقة حماية",
				labelEn: "Protection Layer",
				type: "select",
				options: [
					{
						value: "plaster_3cm",
						label: "لياسة 3سم",
						labelEn: "3cm Plaster",
					},
					{ value: "tiles", label: "بلاط", labelEn: "Tiles" },
					{ value: "none", label: "لا", labelEn: "None" },
				],
				defaultValue: "none",
				affectsSubItems: true,
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{ value: "Sika", label: "Sika", labelEn: "Sika" },
					{ value: "BASF", label: "BASF", labelEn: "BASF" },
					{ value: "Index", label: "Index", labelEn: "Index" },
					{ value: "TAMEER", label: "TAMEER", labelEn: "TAMEER" },
					{
						value: "DrFixit",
						label: "Dr.Fixit",
						labelEn: "Dr.Fixit",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Sika",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "cement_flexible",
				options: { layers: 2, hasReinforcement: false },
			},
			{
				quality: "STANDARD",
				specTypeKey: "cement_flexible",
				options: { layers: 2, hasReinforcement: true },
				suggestedBrands: ["Sika", "TAMEER"],
			},
			{
				quality: "PREMIUM",
				specTypeKey: "bitumen_rolls",
				options: {
					layers: 2,
					hasReinforcement: true,
					hasProtection: "plaster_3cm",
				},
				suggestedBrands: ["Sika", "Index"],
			},
			{
				quality: "LUXURY",
				specTypeKey: "bitumen_rolls",
				options: {
					layers: 3,
					hasReinforcement: true,
					hasProtection: "plaster_3cm",
				},
				suggestedBrands: ["Index", "BASF"],
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 2: العزل الحراري
	// ══════════════════════════════════════════════════════════════
	FINISHING_THERMAL_INSULATION: {
		categoryKey: "FINISHING_THERMAL_INSULATION",
		specTypes: [
			{
				key: "xps_50",
				label: "XPS بوليسترين مبثوق 50مم",
				labelEn: "XPS Extruded Polystyrene 50mm",
				defaultOptions: {
					location: "external_walls",
					thickness: 50,
					mounting: "adhesive_mechanical",
					hasVaporBarrier: false,
				},
				subItemRates: [
					{
						subItemKey: "xps_boards",
						name: "ألواح XPS",
						nameEn: "XPS Boards",
						unit: "م²",
						ratePerUnit: 1.05,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "adhesive",
						name: "لاصق",
						nameEn: "Adhesive",
						unit: "كجم",
						ratePerUnit: 3.5,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "fixing_pins",
						name: "مسامير تثبيت",
						nameEn: "Fixing Pins",
						unit: "عدد",
						ratePerUnit: 5,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "joint_tape",
						name: "شريط فواصل",
						nameEn: "Joint Tape",
						unit: "م.ط",
						ratePerUnit: 0.5,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "eps_50",
				label: "EPS بوليسترين ممدد 50مم",
				labelEn: "EPS Expanded Polystyrene 50mm",
				defaultOptions: {
					location: "external_walls",
					thickness: 50,
					mounting: "adhesive_mechanical",
					hasVaporBarrier: false,
				},
				subItemRates: [
					{
						subItemKey: "eps_boards",
						name: "ألواح EPS",
						nameEn: "EPS Boards",
						unit: "م²",
						ratePerUnit: 1.05,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "adhesive",
						name: "لاصق",
						nameEn: "Adhesive",
						unit: "كجم",
						ratePerUnit: 3.5,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "fixing_pins",
						name: "مسامير تثبيت",
						nameEn: "Fixing Pins",
						unit: "عدد",
						ratePerUnit: 5,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "joint_tape",
						name: "شريط فواصل",
						nameEn: "Joint Tape",
						unit: "م.ط",
						ratePerUnit: 0.5,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "rock_wool_50",
				label: "صوف صخري 50مم",
				labelEn: "Rock Wool 50mm",
				defaultOptions: {
					location: "external_walls",
					thickness: 50,
					mounting: "mechanical",
					hasVaporBarrier: true,
				},
				subItemRates: [
					{
						subItemKey: "rock_wool_boards",
						name: "ألواح صوف صخري",
						nameEn: "Rock Wool Boards",
						unit: "م²",
						ratePerUnit: 1.05,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "fixing_pins",
						name: "مسامير تثبيت",
						nameEn: "Fixing Pins",
						unit: "عدد",
						ratePerUnit: 5,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "vapor_film",
						name: "فيلم بخار",
						nameEn: "Vapor Barrier Film",
						unit: "م²",
						ratePerUnit: 1.1,
						category: "protection",
						isOptional: true,
						conditionalOn: "hasVaporBarrier",
					},
					{
						subItemKey: "aluminum_tape",
						name: "شريط ألمنيوم",
						nameEn: "Aluminum Tape",
						unit: "م.ط",
						ratePerUnit: 0.5,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "pu_spray",
				label: "بولي يوريثان رش",
				labelEn: "Polyurethane Spray",
				defaultOptions: {
					location: "roof",
					thickness: 50,
				},
				subItemRates: [
					{
						subItemKey: "pu_spray",
						name: "مادة PU رش",
						nameEn: "PU Spray Material",
						unit: "كجم",
						ratePerUnit: 1.8,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "location",
				label: "موقع التطبيق",
				labelEn: "Application Location",
				type: "select",
				options: [
					{
						value: "external_walls",
						label: "جدران خارجية",
						labelEn: "External Walls",
					},
					{ value: "roof", label: "سطح", labelEn: "Roof" },
					{ value: "cavity", label: "تجويف", labelEn: "Cavity" },
				],
				defaultValue: "external_walls",
			},
			{
				key: "thickness",
				label: "السماكة (مم)",
				labelEn: "Thickness (mm)",
				type: "select",
				options: [
					{ value: "30", label: "30 مم", labelEn: "30mm" },
					{ value: "40", label: "40 مم", labelEn: "40mm" },
					{ value: "50", label: "50 مم", labelEn: "50mm" },
					{ value: "60", label: "60 مم", labelEn: "60mm" },
					{ value: "75", label: "75 مم", labelEn: "75mm" },
					{ value: "100", label: "100 مم", labelEn: "100mm" },
				],
				defaultValue: "50",
				affectsSubItems: true,
			},
			{
				key: "mounting",
				label: "طريقة التثبيت",
				labelEn: "Mounting Method",
				type: "select",
				options: [
					{
						value: "adhesive",
						label: "لصق",
						labelEn: "Adhesive",
					},
					{
						value: "mechanical",
						label: "تثبيت ميكانيكي",
						labelEn: "Mechanical",
					},
					{
						value: "adhesive_mechanical",
						label: "لصق + تثبيت",
						labelEn: "Adhesive + Mechanical",
					},
				],
				defaultValue: "adhesive_mechanical",
			},
			{
				key: "hasVaporBarrier",
				label: "هل يوجد حاجز بخار",
				labelEn: "Has Vapor Barrier",
				type: "boolean",
				defaultValue: false,
				affectsSubItems: true,
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{ value: "SABIC", label: "SABIC", labelEn: "SABIC" },
					{
						value: "AlWatania",
						label: "Al Watania",
						labelEn: "Al Watania",
					},
					{
						value: "Rockwool",
						label: "Rockwool",
						labelEn: "Rockwool",
					},
					{ value: "Knauf", label: "Knauf", labelEn: "Knauf" },
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "SABIC",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "eps_50",
				options: { thickness: 50, hasVaporBarrier: false },
			},
			{
				quality: "STANDARD",
				specTypeKey: "xps_50",
				options: { thickness: 50, hasVaporBarrier: false },
				suggestedBrands: ["SABIC"],
			},
			{
				quality: "PREMIUM",
				specTypeKey: "xps_50",
				options: { thickness: 75, hasVaporBarrier: true },
				suggestedBrands: ["SABIC", "Knauf"],
			},
			{
				quality: "LUXURY",
				specTypeKey: "rock_wool_50",
				options: { thickness: 100, hasVaporBarrier: true },
				suggestedBrands: ["Rockwool"],
			},
		],
	},
};
