import type { CategorySpecConfig } from "../spec-types";

export const PAINT_CATALOG: Record<string, CategorySpecConfig> = {
	// ══════════════════════════════════════════════════════════════
	// الفئة 5: دهان داخلي
	// ══════════════════════════════════════════════════════════════
	FINISHING_INTERIOR_PAINT: {
		categoryKey: "FINISHING_INTERIOR_PAINT",
		specTypes: [
			{
				key: "plastic_matt",
				label: "بلاستيك مطفي",
				labelEn: "Plastic Matt",
				defaultOptions: {
					preparation: "full_putty",
					coats: 2,
					includesCeiling: true,
				},
				subItemRates: [
					{
						subItemKey: "base_putty",
						name: "معجون أساسي",
						nameEn: "Base Putty",
						unit: "كجم",
						ratePerUnit: 1.0,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "fine_putty",
						name: "معجون ناعم",
						nameEn: "Fine Putty",
						unit: "كجم",
						ratePerUnit: 0.6,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "sandpaper",
						name: "صنفرة",
						nameEn: "Sandpaper",
						unit: "ورقة",
						ratePerUnit: 0.1,
						category: "tool",
						isOptional: false,
					},
					{
						subItemKey: "primer",
						name: "أساس (برايمر)",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.11,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "final_paint",
						name: "دهان نهائي",
						nameEn: "Final Paint",
						unit: "لتر",
						ratePerUnit: 0.22,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "masking_tape",
						name: "شريط لاصق",
						nameEn: "Masking Tape",
						unit: "م.ط",
						ratePerUnit: 0.1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "protection_nylon",
						name: "نايلون حماية",
						nameEn: "Protection Nylon",
						unit: "م²",
						ratePerUnit: 0.3,
						category: "protection",
						isOptional: false,
					},
				],
			},
			{
				key: "plastic_satin",
				label: "بلاستيك ساتان",
				labelEn: "Plastic Satin",
				defaultOptions: {
					preparation: "full_putty",
					coats: 2,
					includesCeiling: true,
				},
				subItemRates: [
					{
						subItemKey: "base_putty",
						name: "معجون أساسي",
						nameEn: "Base Putty",
						unit: "كجم",
						ratePerUnit: 1.0,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "fine_putty",
						name: "معجون ناعم",
						nameEn: "Fine Putty",
						unit: "كجم",
						ratePerUnit: 0.6,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "sandpaper",
						name: "صنفرة",
						nameEn: "Sandpaper",
						unit: "ورقة",
						ratePerUnit: 0.1,
						category: "tool",
						isOptional: false,
					},
					{
						subItemKey: "primer",
						name: "أساس (برايمر)",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.11,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "final_paint",
						name: "دهان ساتان نهائي",
						nameEn: "Satin Final Paint",
						unit: "لتر",
						ratePerUnit: 0.22,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "masking_tape",
						name: "شريط لاصق",
						nameEn: "Masking Tape",
						unit: "م.ط",
						ratePerUnit: 0.1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "protection_nylon",
						name: "نايلون حماية",
						nameEn: "Protection Nylon",
						unit: "م²",
						ratePerUnit: 0.3,
						category: "protection",
						isOptional: false,
					},
				],
			},
			{
				key: "plastic_semi_gloss",
				label: "بلاستيك لامع",
				labelEn: "Plastic Semi-Gloss",
				defaultOptions: {
					preparation: "full_putty",
					coats: 2,
					includesCeiling: true,
				},
				subItemRates: [
					{
						subItemKey: "base_putty",
						name: "معجون أساسي",
						nameEn: "Base Putty",
						unit: "كجم",
						ratePerUnit: 1.0,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "fine_putty",
						name: "معجون ناعم",
						nameEn: "Fine Putty",
						unit: "كجم",
						ratePerUnit: 0.6,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "sandpaper",
						name: "صنفرة",
						nameEn: "Sandpaper",
						unit: "ورقة",
						ratePerUnit: 0.1,
						category: "tool",
						isOptional: false,
					},
					{
						subItemKey: "primer",
						name: "أساس (برايمر)",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.11,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "final_paint",
						name: "دهان لامع نهائي",
						nameEn: "Semi-Gloss Final Paint",
						unit: "لتر",
						ratePerUnit: 0.22,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "masking_tape",
						name: "شريط لاصق",
						nameEn: "Masking Tape",
						unit: "م.ط",
						ratePerUnit: 0.1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "protection_nylon",
						name: "نايلون حماية",
						nameEn: "Protection Nylon",
						unit: "م²",
						ratePerUnit: 0.3,
						category: "protection",
						isOptional: false,
					},
				],
			},
			{
				key: "acrylic",
				label: "أكريليك",
				labelEn: "Acrylic",
				defaultOptions: {
					preparation: "full_putty",
					coats: 2,
					includesCeiling: true,
				},
				subItemRates: [
					{
						subItemKey: "base_putty",
						name: "معجون أساسي",
						nameEn: "Base Putty",
						unit: "كجم",
						ratePerUnit: 1.0,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "fine_putty",
						name: "معجون ناعم",
						nameEn: "Fine Putty",
						unit: "كجم",
						ratePerUnit: 0.6,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "sandpaper",
						name: "صنفرة",
						nameEn: "Sandpaper",
						unit: "ورقة",
						ratePerUnit: 0.1,
						category: "tool",
						isOptional: false,
					},
					{
						subItemKey: "acrylic_primer",
						name: "أساس أكريليك",
						nameEn: "Acrylic Primer",
						unit: "لتر",
						ratePerUnit: 0.12,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "acrylic_paint",
						name: "دهان أكريليك",
						nameEn: "Acrylic Paint",
						unit: "لتر",
						ratePerUnit: 0.22,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "masking_tape",
						name: "شريط لاصق",
						nameEn: "Masking Tape",
						unit: "م.ط",
						ratePerUnit: 0.1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "protection_nylon",
						name: "نايلون حماية",
						nameEn: "Protection Nylon",
						unit: "م²",
						ratePerUnit: 0.3,
						category: "protection",
						isOptional: false,
					},
				],
			},
			{
				key: "velvet",
				label: "مخملي",
				labelEn: "Velvet",
				defaultOptions: {
					preparation: "full_putty",
					coats: 2,
				},
				subItemRates: [
					{
						subItemKey: "base_putty",
						name: "معجون",
						nameEn: "Putty",
						unit: "كجم",
						ratePerUnit: 1.0,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "sandpaper",
						name: "صنفرة",
						nameEn: "Sandpaper",
						unit: "ورقة",
						ratePerUnit: 0.1,
						category: "tool",
						isOptional: false,
					},
					{
						subItemKey: "special_primer",
						name: "أساس خاص",
						nameEn: "Special Primer",
						unit: "لتر",
						ratePerUnit: 0.12,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "velvet_paint",
						name: "دهان مخملي",
						nameEn: "Velvet Paint",
						unit: "لتر",
						ratePerUnit: 0.3,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "texture",
				label: "تأثيرات خاصة",
				labelEn: "Texture / Special Effects",
				defaultOptions: { coats: 1 },
				subItemRates: [
					{
						subItemKey: "primer",
						name: "أساس",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.12,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "texture_material",
						name: "مادة تكستشر",
						nameEn: "Texture Material",
						unit: "كجم",
						ratePerUnit: 1.5,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "preparation",
				label: "تحضير السطح",
				labelEn: "Surface Preparation",
				type: "select",
				options: [
					{
						value: "full_putty",
						label: "معجون كامل (طبقتان)",
						labelEn: "Full Putty (2 layers)",
					},
					{
						value: "light_putty",
						label: "معجون خفيف (طبقة)",
						labelEn: "Light Putty (1 layer)",
					},
					{
						value: "no_putty",
						label: "بدون معجون",
						labelEn: "No Putty",
					},
				],
				defaultValue: "full_putty",
				affectsSubItems: true,
			},
			{
				key: "coats",
				label: "عدد الأوجه",
				labelEn: "Number of Coats",
				type: "select",
				options: [
					{ value: "2", label: "2", labelEn: "2" },
					{ value: "3", label: "3", labelEn: "3" },
				],
				defaultValue: "2",
				affectsSubItems: true,
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{ value: "Jotun", label: "Jotun", labelEn: "Jotun" },
					{
						value: "NationalPaints",
						label: "National Paints",
						labelEn: "National Paints",
					},
					{
						value: "Hempel",
						label: "Hempel",
						labelEn: "Hempel",
					},
					{
						value: "Caparol",
						label: "Caparol",
						labelEn: "Caparol",
					},
					{
						value: "Valentine",
						label: "Valentine",
						labelEn: "Valentine",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Jotun",
			},
			{
				key: "includesCeiling",
				label: "هل يشمل السقف",
				labelEn: "Includes Ceiling",
				type: "select",
				options: [
					{
						value: "same",
						label: "نعم — نفس الدهان",
						labelEn: "Yes — Same Paint",
					},
					{
						value: "different",
						label: "نعم — دهان مختلف",
						labelEn: "Yes — Different Paint",
					},
					{ value: "no", label: "لا", labelEn: "No" },
				],
				defaultValue: "same",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "plastic_matt",
				options: { preparation: "light_putty", coats: 2 },
				suggestedBrands: ["NationalPaints"],
			},
			{
				quality: "STANDARD",
				specTypeKey: "plastic_satin",
				options: { preparation: "full_putty", coats: 2 },
				suggestedBrands: ["Jotun"],
			},
			{
				quality: "PREMIUM",
				specTypeKey: "acrylic",
				options: { preparation: "full_putty", coats: 3 },
				suggestedBrands: ["Caparol", "Jotun"],
			},
			{
				quality: "LUXURY",
				specTypeKey: "velvet",
				options: { preparation: "full_putty", coats: 2 },
				suggestedBrands: ["Caparol"],
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 6: دهان واجهات
	// ══════════════════════════════════════════════════════════════
	FINISHING_FACADE_PAINT: {
		categoryKey: "FINISHING_FACADE_PAINT",
		specTypes: [
			{
				key: "acrylic_exterior",
				label: "أكريليك خارجي",
				labelEn: "Exterior Acrylic",
				defaultOptions: { coats: 2 },
				subItemRates: [
					{
						subItemKey: "exterior_primer",
						name: "أساس خارجي",
						nameEn: "Exterior Primer",
						unit: "لتر",
						ratePerUnit: 0.13,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "exterior_paint",
						name: "دهان خارجي",
						nameEn: "Exterior Paint",
						unit: "لتر",
						ratePerUnit: 0.3,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "scaffolding",
						name: "سقالات",
						nameEn: "Scaffolding",
						unit: "م²",
						ratePerUnit: 1.0,
						category: "tool",
						isOptional: false,
					},
				],
			},
			{
				key: "elastomeric",
				label: "إلاستوميري (مرن)",
				labelEn: "Elastomeric (Flexible)",
				defaultOptions: { coats: 2 },
				subItemRates: [
					{
						subItemKey: "primer",
						name: "أساس",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.13,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "elastomeric_paint",
						name: "دهان مرن",
						nameEn: "Elastomeric Paint",
						unit: "لتر",
						ratePerUnit: 0.35,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "scaffolding",
						name: "سقالات",
						nameEn: "Scaffolding",
						unit: "م²",
						ratePerUnit: 1.0,
						category: "tool",
						isOptional: false,
					},
				],
			},
			{
				key: "texture_exterior",
				label: "تكستشر خارجي",
				labelEn: "Exterior Texture",
				defaultOptions: { coats: 1 },
				subItemRates: [
					{
						subItemKey: "primer",
						name: "أساس",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.13,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "texture_material",
						name: "جرافياتو/تكستشر",
						nameEn: "Grafiato/Texture",
						unit: "كجم",
						ratePerUnit: 2.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "scaffolding",
						name: "سقالات",
						nameEn: "Scaffolding",
						unit: "م²",
						ratePerUnit: 1.0,
						category: "tool",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "coats",
				label: "عدد الأوجه",
				labelEn: "Number of Coats",
				type: "select",
				options: [
					{ value: "2", label: "2", labelEn: "2" },
					{ value: "3", label: "3", labelEn: "3" },
				],
				defaultValue: "2",
				affectsSubItems: true,
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{ value: "Jotun", label: "Jotun", labelEn: "Jotun" },
					{
						value: "NationalPaints",
						label: "National Paints",
						labelEn: "National Paints",
					},
					{
						value: "Hempel",
						label: "Hempel",
						labelEn: "Hempel",
					},
					{
						value: "Caparol",
						label: "Caparol",
						labelEn: "Caparol",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Jotun",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "acrylic_exterior",
				options: { coats: 2 },
				suggestedBrands: ["NationalPaints"],
			},
			{
				quality: "STANDARD",
				specTypeKey: "acrylic_exterior",
				options: { coats: 2 },
				suggestedBrands: ["Jotun"],
			},
			{
				quality: "PREMIUM",
				specTypeKey: "elastomeric",
				options: { coats: 2 },
				suggestedBrands: ["Jotun", "Caparol"],
			},
			{
				quality: "LUXURY",
				specTypeKey: "texture_exterior",
				options: { coats: 1 },
				suggestedBrands: ["Caparol"],
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 7: دهان سور (نفس الواجهات بدون سقالات)
	// ══════════════════════════════════════════════════════════════
	FINISHING_BOUNDARY_PAINT: {
		categoryKey: "FINISHING_BOUNDARY_PAINT",
		specTypes: [
			{
				key: "acrylic_exterior",
				label: "أكريليك خارجي",
				labelEn: "Exterior Acrylic",
				defaultOptions: { coats: 2 },
				subItemRates: [
					{
						subItemKey: "exterior_primer",
						name: "أساس خارجي",
						nameEn: "Exterior Primer",
						unit: "لتر",
						ratePerUnit: 0.13,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "exterior_paint",
						name: "دهان خارجي",
						nameEn: "Exterior Paint",
						unit: "لتر",
						ratePerUnit: 0.3,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "elastomeric",
				label: "إلاستوميري (مرن)",
				labelEn: "Elastomeric (Flexible)",
				defaultOptions: { coats: 2 },
				subItemRates: [
					{
						subItemKey: "primer",
						name: "أساس",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.13,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "elastomeric_paint",
						name: "دهان مرن",
						nameEn: "Elastomeric Paint",
						unit: "لتر",
						ratePerUnit: 0.35,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "texture_exterior",
				label: "تكستشر خارجي",
				labelEn: "Exterior Texture",
				defaultOptions: { coats: 1 },
				subItemRates: [
					{
						subItemKey: "primer",
						name: "أساس",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.13,
						category: "primer",
						isOptional: false,
					},
					{
						subItemKey: "texture_material",
						name: "جرافياتو/تكستشر",
						nameEn: "Grafiato/Texture",
						unit: "كجم",
						ratePerUnit: 2.0,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "coats",
				label: "عدد الأوجه",
				labelEn: "Number of Coats",
				type: "select",
				options: [
					{ value: "2", label: "2", labelEn: "2" },
					{ value: "3", label: "3", labelEn: "3" },
				],
				defaultValue: "2",
				affectsSubItems: true,
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{ value: "Jotun", label: "Jotun", labelEn: "Jotun" },
					{
						value: "NationalPaints",
						label: "National Paints",
						labelEn: "National Paints",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Jotun",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "acrylic_exterior",
				options: { coats: 2 },
				suggestedBrands: ["NationalPaints"],
			},
			{
				quality: "STANDARD",
				specTypeKey: "acrylic_exterior",
				options: { coats: 2 },
				suggestedBrands: ["Jotun"],
			},
			{
				quality: "PREMIUM",
				specTypeKey: "elastomeric",
				options: { coats: 2 },
				suggestedBrands: ["Jotun"],
			},
			{
				quality: "LUXURY",
				specTypeKey: "texture_exterior",
				options: { coats: 1 },
				suggestedBrands: ["Caparol"],
			},
		],
	},
};
