import type { CategorySpecConfig } from "../spec-types";

export const PLASTER_CATALOG: Record<string, CategorySpecConfig> = {
	// ══════════════════════════════════════════════════════════════
	// الفئة 3: لياسة داخلية
	// ══════════════════════════════════════════════════════════════
	FINISHING_INTERNAL_PLASTER: {
		categoryKey: "FINISHING_INTERNAL_PLASTER",
		specTypes: [
			{
				key: "cement_manual",
				label: "أسمنتية بؤج وأوتار",
				labelEn: "Manual Cement Plaster",
				defaultOptions: {
					thickness: 20,
					mixRatio: "1:4",
					includesSplash: true,
					meshType: "joints_only",
					hasCornerProtection: true,
				},
				subItemRates: [
					// طرطشة
					{
						subItemKey: "splash_cement",
						name: "طرطشة: أسمنت",
						nameEn: "Splash Coat: Cement",
						unit: "كجم",
						ratePerUnit: 2.0,
						category: "main",
						isOptional: true,
						conditionalOn: "includesSplash",
					},
					{
						subItemKey: "splash_sand",
						name: "طرطشة: رمل خشن",
						nameEn: "Splash Coat: Coarse Sand",
						unit: "كجم",
						ratePerUnit: 2.0,
						category: "main",
						isOptional: true,
						conditionalOn: "includesSplash",
					},
					// لياسة
					{
						subItemKey: "cement",
						name: "أسمنت",
						nameEn: "Cement",
						unit: "كجم",
						ratePerUnit: 6.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "fine_sand",
						name: "رمل ناعم",
						nameEn: "Fine Sand",
						unit: "كجم",
						ratePerUnit: 28,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "water",
						name: "ماء",
						nameEn: "Water",
						unit: "لتر",
						ratePerUnit: 6,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "reinforcement_mesh",
						name: "شبك تقوية",
						nameEn: "Reinforcement Mesh",
						unit: "م²",
						ratePerUnit: 0.3,
						category: "accessory",
						isOptional: true,
						conditionalOn: "meshType",
					},
					{
						subItemKey: "corner_protection",
						name: "زوايا حماية",
						nameEn: "Corner Protection",
						unit: "م.ط",
						ratePerUnit: 0.15,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasCornerProtection",
					},
					{
						subItemKey: "aluminum_beads",
						name: "بؤج ألمنيوم",
						nameEn: "Aluminum Beads",
						unit: "م.ط",
						ratePerUnit: 0.6,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "cement_machine",
				label: "أسمنتية ماكينة",
				labelEn: "Machine Cement Plaster",
				defaultOptions: {
					thickness: 15,
					hasCornerProtection: true,
				},
				subItemRates: [
					{
						subItemKey: "ready_plaster",
						name: "لياسة جاهزة",
						nameEn: "Ready-mix Plaster",
						unit: "كجم",
						ratePerUnit: 15,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "water",
						name: "ماء",
						nameEn: "Water",
						unit: "لتر",
						ratePerUnit: 6,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "aluminum_beads",
						name: "بؤج ألمنيوم",
						nameEn: "Aluminum Beads",
						unit: "م.ط",
						ratePerUnit: 0.6,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "corner_protection",
						name: "زوايا حماية",
						nameEn: "Corner Protection",
						unit: "م.ط",
						ratePerUnit: 0.15,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasCornerProtection",
					},
				],
			},
			{
				key: "gypsum_manual",
				label: "جبسية يدوية",
				labelEn: "Manual Gypsum Plaster",
				defaultOptions: {
					thickness: 15,
					hasCornerProtection: true,
				},
				subItemRates: [
					{
						subItemKey: "gypsum_plaster",
						name: "جبس لياسة",
						nameEn: "Gypsum Plaster",
						unit: "كجم",
						ratePerUnit: 10,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "water",
						name: "ماء",
						nameEn: "Water",
						unit: "لتر",
						ratePerUnit: 7,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "aluminum_beads",
						name: "بؤج ألمنيوم",
						nameEn: "Aluminum Beads",
						unit: "م.ط",
						ratePerUnit: 0.5,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "corner_protection",
						name: "زوايا حماية",
						nameEn: "Corner Protection",
						unit: "م.ط",
						ratePerUnit: 0.1,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasCornerProtection",
					},
					{
						subItemKey: "fiber_mesh",
						name: "شبك فايبر",
						nameEn: "Fiber Mesh",
						unit: "م²",
						ratePerUnit: 0.2,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "gypsum_machine",
				label: "جبسية ماكينة (MP75)",
				labelEn: "Machine Gypsum Plaster (MP75)",
				defaultOptions: {
					thickness: 10,
					hasCornerProtection: true,
				},
				subItemRates: [
					{
						subItemKey: "gypsum_mp75",
						name: "لياسة جبسية MP75 جاهزة",
						nameEn: "MP75 Ready-mix Gypsum",
						unit: "كجم",
						ratePerUnit: 10,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "water",
						name: "ماء",
						nameEn: "Water",
						unit: "لتر",
						ratePerUnit: 7,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "aluminum_beads",
						name: "بؤج ألمنيوم",
						nameEn: "Aluminum Beads",
						unit: "م.ط",
						ratePerUnit: 0.5,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "corner_protection",
						name: "زوايا حماية",
						nameEn: "Corner Protection",
						unit: "م.ط",
						ratePerUnit: 0.1,
						category: "accessory",
						isOptional: true,
						conditionalOn: "hasCornerProtection",
					},
					{
						subItemKey: "fiber_mesh",
						name: "شبك فايبر",
						nameEn: "Fiber Mesh",
						unit: "م²",
						ratePerUnit: 0.2,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "thickness",
				label: "السماكة (مم)",
				labelEn: "Thickness (mm)",
				type: "select",
				options: [
					{ value: "10", label: "10 مم", labelEn: "10mm" },
					{ value: "15", label: "15 مم", labelEn: "15mm" },
					{ value: "20", label: "20 مم", labelEn: "20mm" },
					{ value: "25", label: "25 مم", labelEn: "25mm" },
				],
				defaultValue: "20",
				affectsSubItems: true,
			},
			{
				key: "mixRatio",
				label: "نسبة الخلط",
				labelEn: "Mix Ratio",
				type: "select",
				options: [
					{ value: "1:3", label: "1:3", labelEn: "1:3" },
					{ value: "1:4", label: "1:4", labelEn: "1:4" },
					{ value: "1:6", label: "1:6", labelEn: "1:6" },
				],
				defaultValue: "1:4",
			},
			{
				key: "includesSplash",
				label: "هل تشمل الطرطشة",
				labelEn: "Includes Splash Coat",
				type: "boolean",
				defaultValue: true,
				affectsSubItems: true,
			},
			{
				key: "meshType",
				label: "شبك تقوية",
				labelEn: "Reinforcement Mesh",
				type: "select",
				options: [
					{ value: "full", label: "كامل", labelEn: "Full" },
					{
						value: "joints_only",
						label: "فواصل فقط",
						labelEn: "Joints Only",
					},
					{ value: "none", label: "لا", labelEn: "None" },
				],
				defaultValue: "joints_only",
				affectsSubItems: true,
			},
			{
				key: "hasCornerProtection",
				label: "زوايا حماية",
				labelEn: "Corner Protection",
				type: "boolean",
				defaultValue: true,
				affectsSubItems: true,
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{ value: "Knauf", label: "Knauf", labelEn: "Knauf" },
					{ value: "Gyproc", label: "Gyproc", labelEn: "Gyproc" },
					{
						value: "NationalGypsum",
						label: "National Gypsum",
						labelEn: "National Gypsum",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Knauf",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "cement_manual",
				options: {
					thickness: 20,
					mixRatio: "1:4",
					meshType: "none",
				},
			},
			{
				quality: "STANDARD",
				specTypeKey: "cement_machine",
				options: {
					thickness: 15,
					meshType: "joints_only",
				},
			},
			{
				quality: "PREMIUM",
				specTypeKey: "gypsum_machine",
				options: { thickness: 10 },
				suggestedBrands: ["Knauf"],
			},
			{
				quality: "LUXURY",
				specTypeKey: "gypsum_machine",
				options: { thickness: 10 },
				suggestedBrands: ["Knauf"],
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 4: لياسة خارجية
	// ══════════════════════════════════════════════════════════════
	FINISHING_EXTERNAL_PLASTER: {
		categoryKey: "FINISHING_EXTERNAL_PLASTER",
		specTypes: [
			{
				key: "cement_manual",
				label: "أسمنتية بؤج وأوتار",
				labelEn: "Manual Cement Plaster",
				defaultOptions: {
					thickness: 20,
					mixRatio: "1:3",
				},
				subItemRates: [
					{
						subItemKey: "splash_cement",
						name: "طرطشة: أسمنت",
						nameEn: "Splash Coat: Cement",
						unit: "كجم",
						ratePerUnit: 2.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "splash_sand",
						name: "طرطشة: رمل خشن",
						nameEn: "Splash Coat: Coarse Sand",
						unit: "كجم",
						ratePerUnit: 2.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "cement",
						name: "أسمنت",
						nameEn: "Cement",
						unit: "كجم",
						ratePerUnit: 7.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "fine_sand",
						name: "رمل ناعم",
						nameEn: "Fine Sand",
						unit: "كجم",
						ratePerUnit: 21,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "water",
						name: "ماء",
						nameEn: "Water",
						unit: "لتر",
						ratePerUnit: 6,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "waterproofing_additive",
						name: "مادة مقاومة للماء (Sika-1)",
						nameEn: "Waterproofing Additive",
						unit: "لتر",
						ratePerUnit: 0.15,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "reinforcement_mesh",
						name: "شبك تقوية كامل",
						nameEn: "Full Reinforcement Mesh",
						unit: "م²",
						ratePerUnit: 1.1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "aluminum_beads",
						name: "بؤج ألمنيوم",
						nameEn: "Aluminum Beads",
						unit: "م.ط",
						ratePerUnit: 0.6,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "corner_protection",
						name: "زوايا حماية",
						nameEn: "Corner Protection",
						unit: "م.ط",
						ratePerUnit: 0.15,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "scaffolding",
						name: "سقالات",
						nameEn: "Scaffolding",
						unit: "م²",
						ratePerUnit: 1.0,
						category: "tool",
						isOptional: false,
					},
				],
			},
			{
				key: "cement_machine",
				label: "أسمنتية ماكينة",
				labelEn: "Machine Cement Plaster",
				defaultOptions: {
					thickness: 15,
					mixRatio: "1:3",
				},
				subItemRates: [
					{
						subItemKey: "ready_plaster",
						name: "لياسة جاهزة",
						nameEn: "Ready-mix Plaster",
						unit: "كجم",
						ratePerUnit: 15,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "water",
						name: "ماء",
						nameEn: "Water",
						unit: "لتر",
						ratePerUnit: 6,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "waterproofing_additive",
						name: "مادة مقاومة للماء (Sika-1)",
						nameEn: "Waterproofing Additive",
						unit: "لتر",
						ratePerUnit: 0.15,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "reinforcement_mesh",
						name: "شبك تقوية كامل",
						nameEn: "Full Reinforcement Mesh",
						unit: "م²",
						ratePerUnit: 1.1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "aluminum_beads",
						name: "بؤج ألمنيوم",
						nameEn: "Aluminum Beads",
						unit: "م.ط",
						ratePerUnit: 0.6,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "corner_protection",
						name: "زوايا حماية",
						nameEn: "Corner Protection",
						unit: "م.ط",
						ratePerUnit: 0.15,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "scaffolding",
						name: "سقالات",
						nameEn: "Scaffolding",
						unit: "م²",
						ratePerUnit: 1.0,
						category: "tool",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "thickness",
				label: "السماكة (مم)",
				labelEn: "Thickness (mm)",
				type: "select",
				options: [
					{ value: "15", label: "15 مم", labelEn: "15mm" },
					{ value: "20", label: "20 مم", labelEn: "20mm" },
					{ value: "25", label: "25 مم", labelEn: "25mm" },
				],
				defaultValue: "20",
				affectsSubItems: true,
			},
			{
				key: "mixRatio",
				label: "نسبة الخلط",
				labelEn: "Mix Ratio",
				type: "select",
				options: [
					{ value: "1:3", label: "1:3", labelEn: "1:3" },
					{ value: "1:4", label: "1:4", labelEn: "1:4" },
				],
				defaultValue: "1:3",
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{ value: "Sika", label: "Sika", labelEn: "Sika" },
					{
						value: "NationalCement",
						label: "أسمنت وطني",
						labelEn: "National Cement",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Sika",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "cement_manual",
				options: { thickness: 20, mixRatio: "1:4" },
			},
			{
				quality: "STANDARD",
				specTypeKey: "cement_manual",
				options: { thickness: 20, mixRatio: "1:3" },
			},
			{
				quality: "PREMIUM",
				specTypeKey: "cement_machine",
				options: { thickness: 15, mixRatio: "1:3" },
			},
			{
				quality: "LUXURY",
				specTypeKey: "cement_machine",
				options: { thickness: 20, mixRatio: "1:3" },
			},
		],
	},
};
