import type { CategorySpecConfig } from "../spec-types";

export const SANITARY_KITCHEN_CATALOG: Record<string, CategorySpecConfig> = {
	// ══════════════════════════════════════════════════════════════
	// الفئة 14: أدوات صحية (حمامات)
	// ══════════════════════════════════════════════════════════════
	FINISHING_BATHROOMS: {
		categoryKey: "FINISHING_BATHROOMS",
		specTypes: [
			{
				key: "standard_set",
				label: "طقم عادي",
				labelEn: "Standard Set",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "basin",
						name: "مغسلة",
						nameEn: "Basin",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "basin_mixer",
						name: "خلاط مغسلة",
						nameEn: "Basin Mixer",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "wc",
						name: "كرسي أفرنجي",
						nameEn: "WC",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "bidet_spray",
						name: "شطاف",
						nameEn: "Bidet Spray",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "flush_tank",
						name: "صندوق طرد",
						nameEn: "Flush Tank",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "shower_tray",
						name: "شاور تريه",
						nameEn: "Shower Tray",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "shower_mixer",
						name: "خلاط شاور",
						nameEn: "Shower Mixer",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "mirror",
						name: "مرآة",
						nameEn: "Mirror",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "accessories",
						name: "إكسسوارات",
						nameEn: "Accessories Set",
						unit: "طقم",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "floor_drain",
						name: "سيفون أرضي",
						nameEn: "Floor Drain",
						unit: "عدد",
						ratePerUnit: 2,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "premium_set",
				label: "طقم ممتاز",
				labelEn: "Premium Set",
				defaultOptions: { hasBathtub: false },
				subItemRates: [
					{
						subItemKey: "basin",
						name: "مغسلة",
						nameEn: "Basin",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "basin_mixer",
						name: "خلاط مغسلة",
						nameEn: "Basin Mixer",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "wc",
						name: "كرسي أفرنجي",
						nameEn: "WC",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "bidet_spray",
						name: "شطاف",
						nameEn: "Bidet Spray",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "flush_tank",
						name: "صندوق طرد مخفي",
						nameEn: "Concealed Flush Tank",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "shower_tray",
						name: "شاور تريه",
						nameEn: "Shower Tray",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "shower_mixer",
						name: "خلاط شاور",
						nameEn: "Shower Mixer",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "shower_glass",
						name: "زجاج شاور",
						nameEn: "Shower Glass",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "mirror",
						name: "مرآة",
						nameEn: "Mirror",
						unit: "عدد",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "accessories",
						name: "إكسسوارات",
						nameEn: "Accessories Set",
						unit: "طقم",
						ratePerUnit: 1,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "floor_drain",
						name: "سيفون أرضي",
						nameEn: "Floor Drain",
						unit: "عدد",
						ratePerUnit: 2,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "bathtub",
						name: "بانيو",
						nameEn: "Bathtub",
						unit: "عدد",
						ratePerUnit: 1,
						category: "main",
						isOptional: true,
						conditionalOn: "hasBathtub",
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "hasBathtub",
				label: "بانيو",
				labelEn: "Bathtub",
				type: "boolean",
				defaultValue: false,
				affectsSubItems: true,
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{
						value: "DERA",
						label: "ديرا",
						labelEn: "DERA",
					},
					{
						value: "Duravit",
						label: "Duravit",
						labelEn: "Duravit",
					},
					{
						value: "TOTO",
						label: "TOTO",
						labelEn: "TOTO",
					},
					{
						value: "Grohe",
						label: "Grohe",
						labelEn: "Grohe",
					},
					{
						value: "Hansgrohe",
						label: "Hansgrohe",
						labelEn: "Hansgrohe",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "DERA",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "standard_set",
				options: {},
				suggestedBrands: ["DERA"],
			},
			{
				quality: "STANDARD",
				specTypeKey: "standard_set",
				options: {},
				suggestedBrands: ["DERA", "Duravit"],
			},
			{
				quality: "PREMIUM",
				specTypeKey: "premium_set",
				options: {},
				suggestedBrands: ["Duravit", "Grohe"],
			},
			{
				quality: "LUXURY",
				specTypeKey: "premium_set",
				options: { hasBathtub: true },
				suggestedBrands: ["TOTO", "Hansgrohe"],
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 15: رخام مغاسل
	// ══════════════════════════════════════════════════════════════
	FINISHING_MARBLE_VANITIES: {
		categoryKey: "FINISHING_MARBLE_VANITIES",
		specTypes: [
			{
				key: "marble_local",
				label: "رخام محلي",
				labelEn: "Local Marble",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "marble_top",
						name: "سطح رخام",
						nameEn: "Marble Top",
						unit: "م.ط",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 3,
						category: "filler",
						isOptional: false,
					},
				],
			},
			{
				key: "marble_imported",
				label: "رخام مستورد",
				labelEn: "Imported Marble",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "marble_top",
						name: "سطح رخام مستورد",
						nameEn: "Imported Marble Top",
						unit: "م.ط",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 3,
						category: "filler",
						isOptional: false,
					},
				],
			},
			{
				key: "quartz",
				label: "كوارتز",
				labelEn: "Quartz",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "quartz_top",
						name: "سطح كوارتز",
						nameEn: "Quartz Top",
						unit: "م.ط",
						ratePerUnit: 1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 3,
						category: "filler",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{
						value: "Local",
						label: "محلي",
						labelEn: "Local",
					},
					{
						value: "Turkish",
						label: "تركي",
						labelEn: "Turkish",
					},
					{
						value: "Italian",
						label: "إيطالي",
						labelEn: "Italian",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Local",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "marble_local",
				options: {},
			},
			{
				quality: "STANDARD",
				specTypeKey: "marble_local",
				options: {},
			},
			{
				quality: "PREMIUM",
				specTypeKey: "marble_imported",
				options: {},
			},
			{
				quality: "LUXURY",
				specTypeKey: "quartz",
				options: {},
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 16: مطابخ
	// ══════════════════════════════════════════════════════════════
	FINISHING_KITCHEN: {
		categoryKey: "FINISHING_KITCHEN",
		specTypes: [
			{
				key: "mdf_lacquer",
				label: "MDF مطلي",
				labelEn: "MDF Lacquer",
				defaultOptions: { countertop: "local_granite" },
				subItemRates: [
					{
						subItemKey: "lower_cabinets",
						name: "خزائن سفلية",
						nameEn: "Lower Cabinets",
						unit: "م.ط",
						ratePerUnit: 1.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "upper_cabinets",
						name: "خزائن علوية",
						nameEn: "Upper Cabinets",
						unit: "م.ط",
						ratePerUnit: 0.8,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "countertop",
						name: "سطح عمل",
						nameEn: "Countertop",
						unit: "م.ط",
						ratePerUnit: 1.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "hydraulic_hinges",
						name: "مفصلات هيدروليك",
						nameEn: "Hydraulic Hinges",
						unit: "عدد",
						ratePerUnit: 4,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "drawer_slides",
						name: "سكك أدراج",
						nameEn: "Drawer Slides",
						unit: "عدد",
						ratePerUnit: 2,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handles",
						name: "مقابض",
						nameEn: "Handles",
						unit: "عدد",
						ratePerUnit: 3,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "sink",
						name: "حوض",
						nameEn: "Sink",
						unit: "عدد",
						ratePerUnit: 0.15,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "mixer",
						name: "خلاط",
						nameEn: "Mixer",
						unit: "عدد",
						ratePerUnit: 0.15,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "pvc_membrane",
				label: "PVC ممبرين",
				labelEn: "PVC Membrane",
				defaultOptions: { countertop: "local_granite" },
				subItemRates: [
					{
						subItemKey: "lower_cabinets",
						name: "خزائن سفلية PVC",
						nameEn: "PVC Lower Cabinets",
						unit: "م.ط",
						ratePerUnit: 1.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "upper_cabinets",
						name: "خزائن علوية PVC",
						nameEn: "PVC Upper Cabinets",
						unit: "م.ط",
						ratePerUnit: 0.8,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "countertop",
						name: "سطح عمل",
						nameEn: "Countertop",
						unit: "م.ط",
						ratePerUnit: 1.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "hydraulic_hinges",
						name: "مفصلات هيدروليك",
						nameEn: "Hydraulic Hinges",
						unit: "عدد",
						ratePerUnit: 4,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "drawer_slides",
						name: "سكك أدراج",
						nameEn: "Drawer Slides",
						unit: "عدد",
						ratePerUnit: 2,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handles",
						name: "مقابض",
						nameEn: "Handles",
						unit: "عدد",
						ratePerUnit: 3,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "sink",
						name: "حوض",
						nameEn: "Sink",
						unit: "عدد",
						ratePerUnit: 0.15,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "mixer",
						name: "خلاط",
						nameEn: "Mixer",
						unit: "عدد",
						ratePerUnit: 0.15,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "hpl",
				label: "HPL هاي بريشر",
				labelEn: "HPL (High Pressure Laminate)",
				defaultOptions: { countertop: "local_granite" },
				subItemRates: [
					{
						subItemKey: "lower_cabinets",
						name: "خزائن سفلية HPL",
						nameEn: "HPL Lower Cabinets",
						unit: "م.ط",
						ratePerUnit: 1.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "upper_cabinets",
						name: "خزائن علوية HPL",
						nameEn: "HPL Upper Cabinets",
						unit: "م.ط",
						ratePerUnit: 0.8,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "countertop",
						name: "سطح عمل",
						nameEn: "Countertop",
						unit: "م.ط",
						ratePerUnit: 1.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "hydraulic_hinges",
						name: "مفصلات هيدروليك",
						nameEn: "Hydraulic Hinges",
						unit: "عدد",
						ratePerUnit: 4,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "drawer_slides",
						name: "سكك أدراج",
						nameEn: "Drawer Slides",
						unit: "عدد",
						ratePerUnit: 2,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handles",
						name: "مقابض",
						nameEn: "Handles",
						unit: "عدد",
						ratePerUnit: 3,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "sink",
						name: "حوض",
						nameEn: "Sink",
						unit: "عدد",
						ratePerUnit: 0.15,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "mixer",
						name: "خلاط",
						nameEn: "Mixer",
						unit: "عدد",
						ratePerUnit: 0.15,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "acrylic",
				label: "أكريليك",
				labelEn: "Acrylic",
				defaultOptions: { countertop: "quartz" },
				subItemRates: [
					{
						subItemKey: "lower_cabinets",
						name: "خزائن سفلية أكريليك",
						nameEn: "Acrylic Lower Cabinets",
						unit: "م.ط",
						ratePerUnit: 1.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "upper_cabinets",
						name: "خزائن علوية أكريليك",
						nameEn: "Acrylic Upper Cabinets",
						unit: "م.ط",
						ratePerUnit: 0.8,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "countertop",
						name: "سطح عمل",
						nameEn: "Countertop",
						unit: "م.ط",
						ratePerUnit: 1.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "hydraulic_hinges",
						name: "مفصلات هيدروليك",
						nameEn: "Hydraulic Hinges",
						unit: "عدد",
						ratePerUnit: 4,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "drawer_slides",
						name: "سكك أدراج",
						nameEn: "Drawer Slides",
						unit: "عدد",
						ratePerUnit: 2,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handles",
						name: "مقابض",
						nameEn: "Handles",
						unit: "عدد",
						ratePerUnit: 3,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "sink",
						name: "حوض",
						nameEn: "Sink",
						unit: "عدد",
						ratePerUnit: 0.15,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "mixer",
						name: "خلاط",
						nameEn: "Mixer",
						unit: "عدد",
						ratePerUnit: 0.15,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "aluminum",
				label: "ألمنيوم",
				labelEn: "Aluminum",
				defaultOptions: { countertop: "local_granite" },
				subItemRates: [
					{
						subItemKey: "lower_cabinets",
						name: "خزائن سفلية ألمنيوم",
						nameEn: "Aluminum Lower Cabinets",
						unit: "م.ط",
						ratePerUnit: 1.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "upper_cabinets",
						name: "خزائن علوية ألمنيوم",
						nameEn: "Aluminum Upper Cabinets",
						unit: "م.ط",
						ratePerUnit: 0.8,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "countertop",
						name: "سطح عمل",
						nameEn: "Countertop",
						unit: "م.ط",
						ratePerUnit: 1.0,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "hydraulic_hinges",
						name: "مفصلات هيدروليك",
						nameEn: "Hydraulic Hinges",
						unit: "عدد",
						ratePerUnit: 4,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "drawer_slides",
						name: "سكك أدراج",
						nameEn: "Drawer Slides",
						unit: "عدد",
						ratePerUnit: 2,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "handles",
						name: "مقابض",
						nameEn: "Handles",
						unit: "عدد",
						ratePerUnit: 3,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "sink",
						name: "حوض",
						nameEn: "Sink",
						unit: "عدد",
						ratePerUnit: 0.15,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "mixer",
						name: "خلاط",
						nameEn: "Mixer",
						unit: "عدد",
						ratePerUnit: 0.15,
						category: "main",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "countertop",
				label: "سطح العمل",
				labelEn: "Countertop",
				type: "select",
				options: [
					{
						value: "local_granite",
						label: "جرانيت محلي",
						labelEn: "Local Granite",
					},
					{
						value: "imported_granite",
						label: "جرانيت مستورد",
						labelEn: "Imported Granite",
					},
					{
						value: "quartz",
						label: "كوارتز",
						labelEn: "Quartz",
					},
					{
						value: "marble",
						label: "رخام",
						labelEn: "Marble",
					},
					{
						value: "hpl",
						label: "HPL",
						labelEn: "HPL",
					},
					{
						value: "stainless",
						label: "ستانلس",
						labelEn: "Stainless Steel",
					},
				],
				defaultValue: "local_granite",
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{
						value: "Local",
						label: "محلي",
						labelEn: "Local",
					},
					{
						value: "IKEA",
						label: "IKEA",
						labelEn: "IKEA",
					},
					{
						value: "Turkish",
						label: "تركي",
						labelEn: "Turkish",
					},
					{
						value: "Italian",
						label: "إيطالي",
						labelEn: "Italian",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Local",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "pvc_membrane",
				options: { countertop: "local_granite" },
			},
			{
				quality: "STANDARD",
				specTypeKey: "mdf_lacquer",
				options: { countertop: "local_granite" },
			},
			{
				quality: "PREMIUM",
				specTypeKey: "hpl",
				options: { countertop: "imported_granite" },
			},
			{
				quality: "LUXURY",
				specTypeKey: "acrylic",
				options: { countertop: "quartz" },
			},
		],
	},
};
