import type { CategorySpecConfig } from "../spec-types";

export const WALLS_CEILING_CATALOG: Record<string, CategorySpecConfig> = {
	// ══════════════════════════════════════════════════════════════
	// الفئة 9: تكسيات جدران
	// نفس أنواع الأرضيات البلاطية لكن: C2 بدل C1، هدر أعلى (1.12)
	// إضافة: زوايا PVC + سيليكون
	// ══════════════════════════════════════════════════════════════
	FINISHING_WALL_TILES: {
		categoryKey: "FINISHING_WALL_TILES",
		specTypes: [
			{
				key: "porcelain_60x60",
				label: "بورسلان 60×60",
				labelEn: "Porcelain 60x60",
				defaultOptions: {
					installation: "adhesive",
					groutType: "normal",
					groutSize: 2,
				},
				subItemRates: [
					{
						subItemKey: "tiles",
						name: "بلاط",
						nameEn: "Tiles",
						unit: "م²",
						ratePerUnit: 1.12,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "adhesive",
						name: "غراء C2",
						nameEn: "C2 Adhesive",
						unit: "كجم",
						ratePerUnit: 4.5,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "grout",
						name: "فواصل",
						nameEn: "Grout",
						unit: "كجم",
						ratePerUnit: 0.4,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "crosses",
						name: "صلبان",
						nameEn: "Tile Crosses",
						unit: "عدد",
						ratePerUnit: 12,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "pvc_corners",
						name: "زوايا PVC للحواف",
						nameEn: "PVC Edge Corners",
						unit: "م.ط",
						ratePerUnit: 0.2,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 0.1,
						category: "filler",
						isOptional: false,
					},
				],
			},
			{
				key: "porcelain_80x80",
				label: "بورسلان 80×80",
				labelEn: "Porcelain 80x80",
				defaultOptions: {
					installation: "adhesive",
					groutType: "normal",
					groutSize: 2,
				},
				subItemRates: [
					{
						subItemKey: "tiles",
						name: "بلاط",
						nameEn: "Tiles",
						unit: "م²",
						ratePerUnit: 1.12,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "adhesive",
						name: "غراء C2",
						nameEn: "C2 Adhesive",
						unit: "كجم",
						ratePerUnit: 4.5,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "grout",
						name: "فواصل",
						nameEn: "Grout",
						unit: "كجم",
						ratePerUnit: 0.3,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "crosses",
						name: "صلبان",
						nameEn: "Tile Crosses",
						unit: "عدد",
						ratePerUnit: 8,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "pvc_corners",
						name: "زوايا PVC للحواف",
						nameEn: "PVC Edge Corners",
						unit: "م.ط",
						ratePerUnit: 0.2,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 0.1,
						category: "filler",
						isOptional: false,
					},
				],
			},
			{
				key: "ceramic_30x60",
				label: "سيراميك 30×60",
				labelEn: "Ceramic 30x60",
				defaultOptions: {
					installation: "adhesive",
					groutType: "normal",
					groutSize: 3,
				},
				subItemRates: [
					{
						subItemKey: "tiles",
						name: "بلاط",
						nameEn: "Tiles",
						unit: "م²",
						ratePerUnit: 1.12,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "adhesive",
						name: "غراء C2",
						nameEn: "C2 Adhesive",
						unit: "كجم",
						ratePerUnit: 4.0,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "grout",
						name: "فواصل",
						nameEn: "Grout",
						unit: "كجم",
						ratePerUnit: 0.5,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "crosses",
						name: "صلبان",
						nameEn: "Tile Crosses",
						unit: "عدد",
						ratePerUnit: 12,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "pvc_corners",
						name: "زوايا PVC للحواف",
						nameEn: "PVC Edge Corners",
						unit: "م.ط",
						ratePerUnit: 0.2,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 0.1,
						category: "filler",
						isOptional: false,
					},
				],
			},
			{
				key: "marble",
				label: "رخام طبيعي",
				labelEn: "Natural Marble",
				defaultOptions: { installation: "cement_mix" },
				subItemRates: [
					{
						subItemKey: "marble_tiles",
						name: "رخام",
						nameEn: "Marble",
						unit: "م²",
						ratePerUnit: 1.12,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "cement_mix",
						name: "خلطة لصق (أسمنت أبيض + رمل)",
						nameEn: "Adhesive Mix",
						unit: "كجم",
						ratePerUnit: 18,
						category: "adhesive",
						isOptional: false,
					},
					{
						subItemKey: "grout",
						name: "فواصل أسمنت أبيض",
						nameEn: "White Cement Grout",
						unit: "كجم",
						ratePerUnit: 0.2,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "pvc_corners",
						name: "زوايا PVC",
						nameEn: "PVC Corners",
						unit: "م.ط",
						ratePerUnit: 0.2,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "silicone",
						name: "سيليكون",
						nameEn: "Silicone",
						unit: "م.ط",
						ratePerUnit: 0.1,
						category: "filler",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "installation",
				label: "طريقة التركيب",
				labelEn: "Installation Method",
				type: "select",
				options: [
					{
						value: "adhesive",
						label: "غراء",
						labelEn: "Adhesive",
					},
					{
						value: "cement_mix",
						label: "خلطة أسمنتية",
						labelEn: "Cement Mix",
					},
				],
				defaultValue: "adhesive",
			},
			{
				key: "groutType",
				label: "نوع الفواصل",
				labelEn: "Grout Type",
				type: "select",
				options: [
					{
						value: "normal",
						label: "عادي",
						labelEn: "Normal",
					},
					{
						value: "epoxy",
						label: "إيبوكسي",
						labelEn: "Epoxy",
					},
				],
				defaultValue: "normal",
			},
			{
				key: "groutSize",
				label: "حجم الفاصل (مم)",
				labelEn: "Grout Size (mm)",
				type: "select",
				options: [
					{ value: "1", label: "1 مم", labelEn: "1mm" },
					{ value: "2", label: "2 مم", labelEn: "2mm" },
					{ value: "3", label: "3 مم", labelEn: "3mm" },
				],
				defaultValue: "2",
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{ value: "RAK", label: "RAK", labelEn: "RAK" },
					{
						value: "SaudiCeramics",
						label: "Saudi Ceramics",
						labelEn: "Saudi Ceramics",
					},
					{
						value: "Porcelanosa",
						label: "Porcelanosa",
						labelEn: "Porcelanosa",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "RAK",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "ceramic_30x60",
				options: { installation: "adhesive", groutType: "normal" },
				suggestedBrands: ["SaudiCeramics"],
			},
			{
				quality: "STANDARD",
				specTypeKey: "porcelain_60x60",
				options: { installation: "adhesive", groutType: "normal" },
				suggestedBrands: ["RAK"],
			},
			{
				quality: "PREMIUM",
				specTypeKey: "porcelain_80x80",
				options: { installation: "adhesive", groutType: "epoxy" },
				suggestedBrands: ["RAK", "Porcelanosa"],
			},
			{
				quality: "LUXURY",
				specTypeKey: "marble",
				options: { installation: "cement_mix" },
				suggestedBrands: ["Porcelanosa"],
			},
		],
	},

	// ══════════════════════════════════════════════════════════════
	// الفئة 10: أسقف مستعارة
	// ══════════════════════════════════════════════════════════════
	FINISHING_FALSE_CEILING: {
		categoryKey: "FINISHING_FALSE_CEILING",
		specTypes: [
			{
				key: "gypsum_board_flat",
				label: "جبس بورد مستوي",
				labelEn: "Flat Gypsum Board",
				defaultOptions: {
					boardType: "standard",
					boardThickness: "12.5",
					includesPaint: true,
				},
				subItemRates: [
					{
						subItemKey: "gypsum_boards",
						name: "ألواح جبس بورد 12.5مم",
						nameEn: "Gypsum Boards 12.5mm",
						unit: "م²",
						ratePerUnit: 1.1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "main_profile",
						name: "بروفايل رئيسي",
						nameEn: "Main Profile",
						unit: "م.ط",
						ratePerUnit: 0.8,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "secondary_profile",
						name: "بروفايل ثانوي",
						nameEn: "Secondary Profile",
						unit: "م.ط",
						ratePerUnit: 1.6,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "wall_profile",
						name: "بروفايل حائطي",
						nameEn: "Wall Profile",
						unit: "م.ط",
						ratePerUnit: 0.3,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "hangers",
						name: "حوامل",
						nameEn: "Hangers",
						unit: "عدد",
						ratePerUnit: 1.5,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "drywall_screws",
						name: "مسامير دريوال",
						nameEn: "Drywall Screws",
						unit: "عدد",
						ratePerUnit: 15,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "joint_tape",
						name: "شريط فواصل",
						nameEn: "Joint Tape",
						unit: "م.ط",
						ratePerUnit: 1.5,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "putty",
						name: "معجون",
						nameEn: "Putty",
						unit: "كجم",
						ratePerUnit: 0.5,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "primer",
						name: "أساس",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.1,
						category: "primer",
						isOptional: true,
						conditionalOn: "includesPaint",
					},
					{
						subItemKey: "paint",
						name: "دهان",
						nameEn: "Paint",
						unit: "لتر",
						ratePerUnit: 0.2,
						category: "main",
						isOptional: true,
						conditionalOn: "includesPaint",
					},
				],
			},
			{
				key: "gypsum_board_design",
				label: "جبس بورد مع تصميم",
				labelEn: "Gypsum Board with Design",
				defaultOptions: {
					boardType: "standard",
					boardThickness: "12.5",
					includesPaint: true,
				},
				subItemRates: [
					{
						subItemKey: "gypsum_boards",
						name: "ألواح جبس بورد 12.5مم",
						nameEn: "Gypsum Boards 12.5mm",
						unit: "م²",
						ratePerUnit: 1.32,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "main_profile",
						name: "بروفايل رئيسي",
						nameEn: "Main Profile",
						unit: "م.ط",
						ratePerUnit: 0.96,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "secondary_profile",
						name: "بروفايل ثانوي",
						nameEn: "Secondary Profile",
						unit: "م.ط",
						ratePerUnit: 1.92,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "wall_profile",
						name: "بروفايل حائطي",
						nameEn: "Wall Profile",
						unit: "م.ط",
						ratePerUnit: 0.36,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "hangers",
						name: "حوامل",
						nameEn: "Hangers",
						unit: "عدد",
						ratePerUnit: 1.8,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "drywall_screws",
						name: "مسامير دريوال",
						nameEn: "Drywall Screws",
						unit: "عدد",
						ratePerUnit: 18,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "joint_tape",
						name: "شريط فواصل",
						nameEn: "Joint Tape",
						unit: "م.ط",
						ratePerUnit: 1.8,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "putty",
						name: "معجون",
						nameEn: "Putty",
						unit: "كجم",
						ratePerUnit: 0.6,
						category: "filler",
						isOptional: false,
					},
					{
						subItemKey: "primer",
						name: "أساس",
						nameEn: "Primer",
						unit: "لتر",
						ratePerUnit: 0.12,
						category: "primer",
						isOptional: true,
						conditionalOn: "includesPaint",
					},
					{
						subItemKey: "paint",
						name: "دهان",
						nameEn: "Paint",
						unit: "لتر",
						ratePerUnit: 0.24,
						category: "main",
						isOptional: true,
						conditionalOn: "includesPaint",
					},
				],
			},
			{
				key: "suspended_tiles",
				label: "سقف معلق بلاطات (60×60)",
				labelEn: "Suspended Ceiling Tiles (60x60)",
				defaultOptions: {},
				subItemRates: [
					{
						subItemKey: "ceiling_tiles",
						name: "بلاطات سقف",
						nameEn: "Ceiling Tiles",
						unit: "م²",
						ratePerUnit: 1.1,
						category: "main",
						isOptional: false,
					},
					{
						subItemKey: "t_profile",
						name: "بروفايل T",
						nameEn: "T-Profile",
						unit: "م.ط",
						ratePerUnit: 3.3,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "wall_profile",
						name: "بروفايل حائطي",
						nameEn: "Wall Profile",
						unit: "م.ط",
						ratePerUnit: 0.3,
						category: "accessory",
						isOptional: false,
					},
					{
						subItemKey: "hanging_wire",
						name: "سلك تعليق",
						nameEn: "Hanging Wire",
						unit: "عدد",
						ratePerUnit: 1.5,
						category: "accessory",
						isOptional: false,
					},
				],
			},
			{
				key: "other",
				label: "أخرى",
				labelEn: "Other",
				defaultOptions: {},
				subItemRates: [],
			},
		],
		commonOptions: [
			{
				key: "boardType",
				label: "نوع الجبس بورد",
				labelEn: "Gypsum Board Type",
				type: "select",
				options: [
					{
						value: "standard",
						label: "عادي",
						labelEn: "Standard",
					},
					{
						value: "moisture_resistant",
						label: "مقاوم رطوبة (أخضر)",
						labelEn: "Moisture Resistant (Green)",
					},
					{
						value: "fire_resistant",
						label: "مقاوم حريق (وردي)",
						labelEn: "Fire Resistant (Pink)",
					},
				],
				defaultValue: "standard",
			},
			{
				key: "boardThickness",
				label: "السماكة",
				labelEn: "Thickness",
				type: "select",
				options: [
					{ value: "9.5", label: "9.5 مم", labelEn: "9.5mm" },
					{ value: "12.5", label: "12.5 مم", labelEn: "12.5mm" },
					{ value: "15", label: "15 مم", labelEn: "15mm" },
				],
				defaultValue: "12.5",
			},
			{
				key: "includesPaint",
				label: "هل يشمل الدهان",
				labelEn: "Includes Paint",
				type: "boolean",
				defaultValue: true,
				affectsSubItems: true,
			},
			{
				key: "brand",
				label: "الماركة",
				labelEn: "Brand",
				type: "select",
				options: [
					{ value: "Knauf", label: "Knauf", labelEn: "Knauf" },
					{ value: "Gyproc", label: "Gyproc", labelEn: "Gyproc" },
					{
						value: "NationalGypsum",
						label: "National Gypsum",
						labelEn: "National Gypsum",
					},
					{ value: "other", label: "أخرى", labelEn: "Other" },
				],
				defaultValue: "Knauf",
			},
		],
		qualityPresets: [
			{
				quality: "ECONOMY",
				specTypeKey: "suspended_tiles",
				options: {},
			},
			{
				quality: "STANDARD",
				specTypeKey: "gypsum_board_flat",
				options: { boardType: "standard", includesPaint: true },
				suggestedBrands: ["Knauf"],
			},
			{
				quality: "PREMIUM",
				specTypeKey: "gypsum_board_design",
				options: { boardType: "standard", includesPaint: true },
				suggestedBrands: ["Knauf"],
			},
			{
				quality: "LUXURY",
				specTypeKey: "gypsum_board_design",
				options: {
					boardType: "moisture_resistant",
					includesPaint: true,
				},
				suggestedBrands: ["Knauf"],
			},
		],
	},
};
