"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { orpc } from "@shared/lib/orpc-query-utils";
import { orpcClient } from "@shared/lib/orpc-client";
import { Button } from "@ui/components/button";
import { Badge } from "@ui/components/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@ui/components/card";
import {
	AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent,
	AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle,
} from "@ui/components/alert-dialog";
import { Textarea } from "@ui/components/textarea";
import { toast } from "sonner";
import {
	ArrowRight, Printer, Ban, Send, CheckCircle, XCircle, Pencil,
	FileMinus, Calendar, User, Building, CreditCard, Link2, ShieldCheck,
} from "lucide-react";
import { formatDate } from "@shared/lib/formatters";
import { Currency } from "../shared/Currency";
import { ListTableSkeleton } from "@saas/shared/components/skeletons";

interface PaymentVoucherDetailProps {
	organizationId: string;
	organizationSlug: string;
	voucherId: string;
}

const STATUS_COLORS: Record<string, string> = {
	DRAFT: "bg-gray-100 text-gray-700",
	PENDING_APPROVAL: "bg-amber-100 text-amber-700",
	ISSUED: "bg-green-100 text-green-700",
	CANCELLED: "bg-red-100 text-red-700",
};

export function PaymentVoucherDetail({
	organizationId,
	organizationSlug,
	voucherId,
}: PaymentVoucherDetailProps) {
	const t = useTranslations();
	const router = useRouter();
	const queryClient = useQueryClient();

	const [showCancelDialog, setShowCancelDialog] = useState(false);
	const [cancelReason, setCancelReason] = useState("");
	const [showRejectDialog, setShowRejectDialog] = useState(false);
	const [rejectionReason, setRejectionReason] = useState("");
	const [showApproveDialog, setShowApproveDialog] = useState(false);
	const [showSubmitDialog, setShowSubmitDialog] = useState(false);

	const basePath = `/app/${organizationSlug}/finance/payment-vouchers`;

	const { data: voucher, isLoading } = useQuery(
		orpc.finance.disbursements.getById.queryOptions({
			input: { organizationId, id: voucherId },
		}),
	);

	const invalidate = () => queryClient.invalidateQueries({ queryKey: ["finance", "disbursements"] });

	const submitMutation = useMutation({
		mutationFn: () => orpcClient.finance.disbursements.submit({ organizationId, id: voucherId }),
		onSuccess: () => { invalidate(); toast.success(t("finance.paymentVouchers.actions.submit")); setShowSubmitDialog(false); },
		onError: () => toast.error(t("common.error")),
	});

	const approveMutation = useMutation({
		mutationFn: () => orpcClient.finance.disbursements.approve({ organizationId, id: voucherId }),
		onSuccess: () => { invalidate(); toast.success(t("finance.paymentVouchers.actions.approve")); setShowApproveDialog(false); },
		onError: () => toast.error(t("common.error")),
	});

	const rejectMutation = useMutation({
		mutationFn: () => orpcClient.finance.disbursements.reject({ organizationId, id: voucherId, rejectionReason }),
		onSuccess: () => { invalidate(); toast.success(t("finance.paymentVouchers.actions.reject")); setShowRejectDialog(false); setRejectionReason(""); },
		onError: () => toast.error(t("common.error")),
	});

	const cancelMutation = useMutation({
		mutationFn: () => orpcClient.finance.disbursements.cancel({ organizationId, id: voucherId, cancelReason }),
		onSuccess: () => { invalidate(); toast.success(t("finance.paymentVouchers.actions.cancel")); setShowCancelDialog(false); setCancelReason(""); },
		onError: () => toast.error(t("common.error")),
	});

	const printMutation = useMutation({
		mutationFn: () => orpcClient.finance.disbursements.print({ organizationId, id: voucherId }),
		onSuccess: () => { invalidate(); window.print(); },
	});

	if (isLoading || !voucher) return <ListTableSkeleton rows={6} cols={2} />;

	const isManual = !voucher.expenseId && !voucher.subcontractPaymentId;

	return (
		<div className="space-y-6">
			{/* Header */}
			<div className="flex items-center justify-between">
				<div className="flex items-center gap-3">
					<Button variant="ghost" size="icon" onClick={() => router.push(basePath)}>
						<ArrowRight className="h-4 w-4" />
					</Button>
					<div>
						<div className="flex items-center gap-2">
							<h1 className="text-2xl font-bold font-mono">{voucher.voucherNo}</h1>
							<Badge className={STATUS_COLORS[voucher.status] ?? ""}>
								{t(`finance.paymentVouchers.statuses.${voucher.status}`)}
							</Badge>
						</div>
						<p className="text-sm text-muted-foreground">
							{isManual ? t("finance.paymentVouchers.manualVoucher") : t("finance.paymentVouchers.autoGenerated")}
						</p>
					</div>
				</div>

				<div className="flex gap-2">
					{voucher.status === "DRAFT" && (
						<>
							<Button variant="outline" onClick={() => router.push(`${basePath}/${voucherId}`)}>
								<Pencil className="me-2 h-4 w-4" />{t("finance.paymentVouchers.actions.edit")}
							</Button>
							<Button onClick={() => setShowSubmitDialog(true)}>
								<Send className="me-2 h-4 w-4" />{t("finance.paymentVouchers.actions.submit")}
							</Button>
						</>
					)}
					{voucher.status === "PENDING_APPROVAL" && (
						<>
							<Button variant="default" onClick={() => setShowApproveDialog(true)}>
								<CheckCircle className="me-2 h-4 w-4" />{t("finance.paymentVouchers.actions.approve")}
							</Button>
							<Button variant="destructive" onClick={() => setShowRejectDialog(true)}>
								<XCircle className="me-2 h-4 w-4" />{t("finance.paymentVouchers.actions.reject")}
							</Button>
						</>
					)}
					{voucher.status === "ISSUED" && (
						<Button variant="outline" onClick={() => printMutation.mutate()}>
							<Printer className="me-2 h-4 w-4" />{t("finance.paymentVouchers.actions.print")}
						</Button>
					)}
					{voucher.status !== "CANCELLED" && (
						<Button variant="destructive" onClick={() => setShowCancelDialog(true)}>
							<Ban className="me-2 h-4 w-4" />{t("finance.paymentVouchers.actions.cancel")}
						</Button>
					)}
				</div>
			</div>

			{/* Main Info */}
			<div className="grid grid-cols-1 gap-6 md:grid-cols-2">
				<Card>
					<CardHeader>
						<CardTitle className="flex items-center gap-2">
							<FileMinus className="h-5 w-5" />{t("finance.paymentVouchers.paymentVoucher")}
						</CardTitle>
					</CardHeader>
					<CardContent className="space-y-3">
						<InfoRow label={t("finance.paymentVouchers.date")} value={formatDate(voucher.date)} icon={<Calendar className="h-4 w-4" />} />
						<InfoRow label={t("finance.paymentVouchers.amount")} value={<Currency value={Number(voucher.amount)} />} />
						{voucher.amountInWords && <InfoRow label={t("finance.paymentVouchers.amountInWords")} value={voucher.amountInWords} />}
						<InfoRow label={t("finance.paymentVouchers.payeeName")} value={voucher.payeeName} icon={<User className="h-4 w-4" />} />
						<InfoRow label={t("finance.paymentVouchers.payeeType")} value={t(`finance.paymentVouchers.payeeTypes.${voucher.payeeType}`)} />
						<InfoRow label={t("finance.paymentVouchers.paymentMethod")} value={t(`finance.payments.methods.${voucher.paymentMethod}`)} icon={<CreditCard className="h-4 w-4" />} />
						{voucher.checkNumber && <InfoRow label={t("finance.paymentVouchers.checkNumber")} value={voucher.checkNumber} />}
						{voucher.transferRef && <InfoRow label={t("finance.paymentVouchers.transferRef")} value={voucher.transferRef} />}
						{voucher.sourceAccount && <InfoRow label={t("finance.paymentVouchers.sourceAccount")} value={voucher.sourceAccount.name} icon={<Building className="h-4 w-4" />} />}
					</CardContent>
				</Card>

				<div className="space-y-6">
					{/* Approval Info */}
					<Card>
						<CardHeader>
							<CardTitle className="flex items-center gap-2">
								<ShieldCheck className="h-5 w-5" />{t("finance.paymentVouchers.preparedBy")}
							</CardTitle>
						</CardHeader>
						<CardContent className="space-y-3">
							<InfoRow label={t("finance.paymentVouchers.preparedBy")} value={voucher.preparedBy?.name ?? "-"} />
							{voucher.approvedBy && (
								<>
									<InfoRow label={t("finance.paymentVouchers.approvedBy")} value={voucher.approvedBy.name} />
									{voucher.approvedAt && <InfoRow label={t("finance.paymentVouchers.approvedAt")} value={formatDate(voucher.approvedAt)} />}
								</>
							)}
							{voucher.rejectionReason && (
								<InfoRow label={t("finance.paymentVouchers.rejectReason")} value={<span className="text-red-600">{voucher.rejectionReason}</span>} />
							)}
						</CardContent>
					</Card>

					{/* Linked To */}
					<Card>
						<CardHeader>
							<CardTitle className="flex items-center gap-2">
								<Link2 className="h-5 w-5" />{t("finance.paymentVouchers.linkedTo")}
							</CardTitle>
						</CardHeader>
						<CardContent className="space-y-3">
							{voucher.project && <InfoRow label={t("finance.payments.selectProject")} value={voucher.project.name} />}
							{voucher.subcontractContract && <InfoRow label={t("finance.paymentVouchers.subcontractContract")} value={voucher.subcontractContract.name} />}
							{voucher.expense && <InfoRow label={t("finance.expenses.title")} value={voucher.expense.expenseNo} />}
							{voucher.subcontractPayment && <InfoRow label={t("finance.payments.title")} value={voucher.subcontractPayment.paymentNo} />}
							{voucher.description && <InfoRow label={t("finance.paymentVouchers.description")} value={voucher.description} />}
							{voucher.notes && <InfoRow label={t("finance.paymentVouchers.notes")} value={voucher.notes} />}
						</CardContent>
					</Card>
				</div>
			</div>

			{/* Audit Info */}
			<Card>
				<CardContent className="flex flex-wrap gap-6 pt-4 text-sm text-muted-foreground">
					<span>{t("common.createdAt")}: {formatDate(voucher.createdAt)}</span>
					<span>{t("finance.paymentVouchers.printCount")}: {voucher.printCount}</span>
					{voucher.status === "CANCELLED" && (
						<>
							<span className="text-red-600">{t("finance.paymentVouchers.cancelledAt")}: {voucher.cancelledAt ? formatDate(voucher.cancelledAt) : ""}</span>
							<span className="text-red-600">{t("finance.paymentVouchers.cancelReason")}: {voucher.cancelReason}</span>
						</>
					)}
				</CardContent>
			</Card>

			{/* Submit Dialog */}
			<AlertDialog open={showSubmitDialog} onOpenChange={setShowSubmitDialog}>
				<AlertDialogContent>
					<AlertDialogHeader>
						<AlertDialogTitle>{t("finance.paymentVouchers.actions.submit")}</AlertDialogTitle>
						<AlertDialogDescription>{t("finance.paymentVouchers.submitConfirm")}</AlertDialogDescription>
					</AlertDialogHeader>
					<AlertDialogFooter>
						<AlertDialogCancel>{t("common.cancel")}</AlertDialogCancel>
						<AlertDialogAction onClick={() => submitMutation.mutate()} disabled={submitMutation.isPending}>
							{t("finance.paymentVouchers.actions.submit")}
						</AlertDialogAction>
					</AlertDialogFooter>
				</AlertDialogContent>
			</AlertDialog>

			{/* Approve Dialog */}
			<AlertDialog open={showApproveDialog} onOpenChange={setShowApproveDialog}>
				<AlertDialogContent>
					<AlertDialogHeader>
						<AlertDialogTitle>{t("finance.paymentVouchers.actions.approve")}</AlertDialogTitle>
						<AlertDialogDescription>{t("finance.paymentVouchers.approveConfirm")}</AlertDialogDescription>
					</AlertDialogHeader>
					<AlertDialogFooter>
						<AlertDialogCancel>{t("common.cancel")}</AlertDialogCancel>
						<AlertDialogAction onClick={() => approveMutation.mutate()} disabled={approveMutation.isPending}>
							{t("finance.paymentVouchers.actions.approve")}
						</AlertDialogAction>
					</AlertDialogFooter>
				</AlertDialogContent>
			</AlertDialog>

			{/* Reject Dialog */}
			<AlertDialog open={showRejectDialog} onOpenChange={setShowRejectDialog}>
				<AlertDialogContent>
					<AlertDialogHeader>
						<AlertDialogTitle>{t("finance.paymentVouchers.rejectDialog.title")}</AlertDialogTitle>
						<AlertDialogDescription>{t("finance.paymentVouchers.rejectDialog.description")}</AlertDialogDescription>
					</AlertDialogHeader>
					<div className="py-4">
						<Textarea
							placeholder={t("finance.paymentVouchers.rejectDialog.reasonPlaceholder")}
							value={rejectionReason}
							onChange={(e) => setRejectionReason(e.target.value)}
							rows={3}
						/>
					</div>
					<AlertDialogFooter>
						<AlertDialogCancel>{t("common.cancel")}</AlertDialogCancel>
						<AlertDialogAction
							onClick={() => rejectMutation.mutate()}
							disabled={rejectMutation.isPending || !rejectionReason.trim()}
							className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
						>
							{t("finance.paymentVouchers.rejectDialog.confirm")}
						</AlertDialogAction>
					</AlertDialogFooter>
				</AlertDialogContent>
			</AlertDialog>

			{/* Cancel Dialog */}
			<AlertDialog open={showCancelDialog} onOpenChange={setShowCancelDialog}>
				<AlertDialogContent>
					<AlertDialogHeader>
						<AlertDialogTitle>{t("finance.paymentVouchers.cancelDialog.title")}</AlertDialogTitle>
						<AlertDialogDescription>{t("finance.paymentVouchers.cancelDialog.description")}</AlertDialogDescription>
					</AlertDialogHeader>
					<div className="py-4">
						<Textarea
							placeholder={t("finance.paymentVouchers.cancelDialog.reasonPlaceholder")}
							value={cancelReason}
							onChange={(e) => setCancelReason(e.target.value)}
							rows={3}
						/>
					</div>
					<AlertDialogFooter>
						<AlertDialogCancel>{t("common.cancel")}</AlertDialogCancel>
						<AlertDialogAction
							onClick={() => cancelMutation.mutate()}
							disabled={cancelMutation.isPending || !cancelReason.trim()}
							className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
						>
							{t("finance.paymentVouchers.cancelDialog.confirm")}
						</AlertDialogAction>
					</AlertDialogFooter>
				</AlertDialogContent>
			</AlertDialog>
		</div>
	);
}

function InfoRow({ label, value, icon }: { label: string; value: React.ReactNode; icon?: React.ReactNode }) {
	return (
		<div className="flex items-start justify-between gap-2">
			<span className="flex items-center gap-2 text-sm text-muted-foreground">{icon}{label}</span>
			<span className="text-sm font-medium text-end">{value}</span>
		</div>
	);
}
