// ═══════════════════════════════════════════════════════════════════════════
// Shared PDF Helpers (pdfkit)
// ═══════════════════════════════════════════════════════════════════════════

import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import type { PDFConfig } from "./pdf-generator";

// ─── Font Loading ────────────────────────────────────────────────────────
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const FONTS_DIR = path.join(__dirname, "..", "fonts");

let arabicRegularBuffer: Buffer | null = null;
let arabicBoldBuffer: Buffer | null = null;

function loadFonts() {
	if (!arabicRegularBuffer) {
		arabicRegularBuffer = fs.readFileSync(
			path.join(FONTS_DIR, "IBMPlexSansArabic-Regular.ttf"),
		);
	}
	if (!arabicBoldBuffer) {
		arabicBoldBuffer = fs.readFileSync(
			path.join(FONTS_DIR, "IBMPlexSansArabic-Bold.ttf"),
		);
	}
}

// ─── Constants ───────────────────────────────────────────────────────────
const PAGE_MARGIN = 40;
const PRIMARY_COLOR = "#2563EB";
const HEADER_BG = "#F9FAFB";
const BORDER_COLOR = "#E5E7EB";
const TEXT_COLOR = "#111827";
const TEXT_MUTED = "#6B7280";
const FONT_SIZE = {
	title: 16,
	subtitle: 12,
	body: 10,
	small: 9,
	footer: 8,
};

// ─── Document Creation ───────────────────────────────────────────────────
export function createPDFDocument(config: PDFConfig): typeof PDFDocument.prototype {
	loadFonts();

	const doc = new PDFDocument({
		size: "A4",
		layout: config.orientation === "landscape" ? "landscape" : "portrait",
		margins: {
			top: PAGE_MARGIN,
			bottom: PAGE_MARGIN + 20, // extra space for footer
			left: PAGE_MARGIN,
			right: PAGE_MARGIN,
		},
		info: {
			Title: config.title,
			Author: "Masar - مسار",
			Creator: "Masar Platform",
		},
		bufferPages: true,
	});

	// Register Arabic fonts
	doc.registerFont("Arabic", arabicRegularBuffer!);
	doc.registerFont("Arabic-Bold", arabicBoldBuffer!);

	// Set default font
	doc.font("Arabic").fontSize(FONT_SIZE.body);

	return doc;
}

// ─── Header ──────────────────────────────────────────────────────────────
export function renderHeader(
	doc: typeof PDFDocument.prototype,
	opts: {
		title: string;
		subtitle?: string;
		companyName: string;
		companyLogo?: string;
		language: "ar" | "en";
	},
): void {
	const pageWidth = doc.page.width - PAGE_MARGIN * 2;
	const isAr = opts.language === "ar";
	const align = isAr ? "right" : "left";

	// Company name
	doc
		.font("Arabic-Bold")
		.fontSize(FONT_SIZE.subtitle)
		.fillColor(TEXT_MUTED)
		.text(opts.companyName, PAGE_MARGIN, PAGE_MARGIN, {
			width: pageWidth,
			align: "center",
		});

	doc.moveDown(0.3);

	// Title
	doc
		.font("Arabic-Bold")
		.fontSize(FONT_SIZE.title)
		.fillColor(TEXT_COLOR)
		.text(opts.title, PAGE_MARGIN, doc.y, {
			width: pageWidth,
			align: "center",
		});

	// Subtitle
	if (opts.subtitle) {
		doc.moveDown(0.2);
		doc
			.font("Arabic")
			.fontSize(FONT_SIZE.subtitle)
			.fillColor(TEXT_MUTED)
			.text(opts.subtitle, PAGE_MARGIN, doc.y, {
				width: pageWidth,
				align: "center",
			});
	}

	// Divider line
	doc.moveDown(0.5);
	const lineY = doc.y;
	doc
		.strokeColor(PRIMARY_COLOR)
		.lineWidth(2)
		.moveTo(PAGE_MARGIN, lineY)
		.lineTo(PAGE_MARGIN + pageWidth, lineY)
		.stroke();

	doc.moveDown(0.8);
	doc.fillColor(TEXT_COLOR);
}

// ─── Footer (registered on all pages) ────────────────────────────────────
export function registerFooter(
	doc: typeof PDFDocument.prototype,
	opts: { companyName: string; language: "ar" | "en" },
): void {
	const isAr = opts.language === "ar";
	const generatedBy = isAr ? "تم التوليد بواسطة مسار" : "Generated by Masar";
	const now = formatDate(new Date(), opts.language);

	// We'll render footers at the end using buffered pages
	doc.on("end", () => {
		// Footer rendering happens in docToBuffer before end
	});

	// Store footer info on doc for later rendering
	(doc as any)._masarFooter = { generatedBy, now, companyName: opts.companyName, language: opts.language };
}

function renderFootersOnAllPages(doc: typeof PDFDocument.prototype): void {
	const footer = (doc as any)._masarFooter;
	if (!footer) return;

	const pageCount = doc.bufferedPageRange().count;
	const isAr = footer.language === "ar";
	const pageLabel = isAr ? "صفحة" : "Page";
	const ofLabel = isAr ? "من" : "of";

	for (let i = 0; i < pageCount; i++) {
		doc.switchToPage(i);
		const pageWidth = doc.page.width;
		const bottomY = doc.page.height - PAGE_MARGIN;

		// Footer divider line
		doc
			.strokeColor(BORDER_COLOR)
			.lineWidth(0.5)
			.moveTo(PAGE_MARGIN, bottomY - 15)
			.lineTo(pageWidth - PAGE_MARGIN, bottomY - 15)
			.stroke();

		// Left side: generated by
		doc
			.font("Arabic")
			.fontSize(FONT_SIZE.footer)
			.fillColor(TEXT_MUTED)
			.text(footer.generatedBy, PAGE_MARGIN, bottomY - 10, {
				width: (pageWidth - PAGE_MARGIN * 2) / 2,
				align: isAr ? "right" : "left",
			});

		// Right side: page number
		doc
			.font("Arabic")
			.fontSize(FONT_SIZE.footer)
			.fillColor(TEXT_MUTED)
			.text(
				`${pageLabel} ${i + 1} ${ofLabel} ${pageCount}`,
				pageWidth / 2,
				bottomY - 10,
				{
					width: (pageWidth - PAGE_MARGIN * 2) / 2,
					align: isAr ? "left" : "right",
				},
			);
	}
}

// ─── Section Title ───────────────────────────────────────────────────────
export function renderSectionTitle(
	doc: typeof PDFDocument.prototype,
	title: string,
	language: "ar" | "en",
): void {
	const pageWidth = doc.page.width - PAGE_MARGIN * 2;
	const isAr = language === "ar";

	doc.moveDown(0.5);
	doc
		.font("Arabic-Bold")
		.fontSize(FONT_SIZE.subtitle)
		.fillColor(PRIMARY_COLOR)
		.text(title, PAGE_MARGIN, doc.y, {
			width: pageWidth,
			align: isAr ? "right" : "left",
		});

	// Underline
	const lineY = doc.y + 2;
	doc
		.strokeColor(PRIMARY_COLOR)
		.lineWidth(1)
		.moveTo(PAGE_MARGIN, lineY)
		.lineTo(PAGE_MARGIN + pageWidth, lineY)
		.stroke();

	doc.moveDown(0.5);
	doc.fillColor(TEXT_COLOR).font("Arabic").fontSize(FONT_SIZE.body);
}

// ─── Key-Value Pairs ─────────────────────────────────────────────────────
export function renderKeyValuePairs(
	doc: typeof PDFDocument.prototype,
	pairs: [string, string][],
	language: "ar" | "en",
): void {
	const pageWidth = doc.page.width - PAGE_MARGIN * 2;
	const isAr = language === "ar";
	const labelWidth = 150;
	const valueWidth = pageWidth - labelWidth - 10;

	for (const [label, value] of pairs) {
		const startY = doc.y;

		// Check for page break
		if (startY > doc.page.height - PAGE_MARGIN - 40) {
			doc.addPage();
		}

		if (isAr) {
			// RTL: value on left, label on right
			doc
				.font("Arabic-Bold")
				.fontSize(FONT_SIZE.body)
				.fillColor(TEXT_MUTED)
				.text(label, PAGE_MARGIN + valueWidth + 10, doc.y, {
					width: labelWidth,
					align: "right",
				});

			doc
				.font("Arabic")
				.fontSize(FONT_SIZE.body)
				.fillColor(TEXT_COLOR)
				.text(value, PAGE_MARGIN, startY, {
					width: valueWidth,
					align: "right",
				});
		} else {
			doc
				.font("Arabic-Bold")
				.fontSize(FONT_SIZE.body)
				.fillColor(TEXT_MUTED)
				.text(label, PAGE_MARGIN, doc.y, {
					width: labelWidth,
					align: "left",
					continued: false,
				});

			doc
				.font("Arabic")
				.fontSize(FONT_SIZE.body)
				.fillColor(TEXT_COLOR)
				.text(value, PAGE_MARGIN + labelWidth + 10, startY, {
					width: valueWidth,
					align: "left",
				});
		}

		doc.moveDown(0.3);
	}
}

// ─── Table ───────────────────────────────────────────────────────────────
export function renderTable(
	doc: typeof PDFDocument.prototype,
	opts: {
		headers: string[];
		rows: string[][];
		columnWidths?: number[];
		language: "ar" | "en";
		highlightLastRow?: boolean;
	},
): void {
	const pageWidth = doc.page.width - PAGE_MARGIN * 2;
	const isAr = opts.language === "ar";
	const colCount = opts.headers.length;

	// Calculate column widths
	const colWidths = opts.columnWidths ||
		Array(colCount).fill(pageWidth / colCount);

	// Normalize widths to fit page
	const totalWidth = colWidths.reduce((a, b) => a + b, 0);
	const scale = pageWidth / totalWidth;
	const finalWidths = colWidths.map((w) => w * scale);

	const rowHeight = 25;
	const cellPadding = 5;

	// Reverse column order for RTL
	const displayHeaders = isAr ? [...opts.headers].reverse() : opts.headers;
	const displayWidths = isAr ? [...finalWidths].reverse() : finalWidths;

	function getColX(colIndex: number): number {
		let x = PAGE_MARGIN;
		for (let i = 0; i < colIndex; i++) {
			x += displayWidths[i];
		}
		return x;
	}

	function drawRow(y: number, cells: string[], isHeader: boolean, isHighlight: boolean): number {
		// Measure actual height needed
		let maxHeight = rowHeight;
		for (let i = 0; i < cells.length; i++) {
			const textHeight = doc
				.font(isHeader ? "Arabic-Bold" : "Arabic")
				.fontSize(isHeader ? FONT_SIZE.small : FONT_SIZE.body)
				.heightOfString(cells[i], { width: displayWidths[i] - cellPadding * 2 });
			maxHeight = Math.max(maxHeight, textHeight + cellPadding * 2);
		}

		// Background
		if (isHeader) {
			doc.rect(PAGE_MARGIN, y, pageWidth, maxHeight).fill(HEADER_BG);
		} else if (isHighlight) {
			doc.rect(PAGE_MARGIN, y, pageWidth, maxHeight).fill("#EEF2FF");
		}

		// Cell borders and text
		for (let i = 0; i < cells.length; i++) {
			const cellX = getColX(i);

			// Border
			doc
				.strokeColor(BORDER_COLOR)
				.lineWidth(0.5)
				.rect(cellX, y, displayWidths[i], maxHeight)
				.stroke();

			// Text
			doc
				.font(isHeader || isHighlight ? "Arabic-Bold" : "Arabic")
				.fontSize(isHeader ? FONT_SIZE.small : FONT_SIZE.body)
				.fillColor(isHeader ? TEXT_MUTED : TEXT_COLOR)
				.text(cells[i], cellX + cellPadding, y + cellPadding, {
					width: displayWidths[i] - cellPadding * 2,
					align: isAr ? "right" : "left",
				});
		}

		return maxHeight;
	}

	// Check if enough space for header + 1 row
	if (doc.y + rowHeight * 2 > doc.page.height - PAGE_MARGIN - 30) {
		doc.addPage();
	}

	// Draw header
	let currentY = doc.y;
	const headerHeight = drawRow(currentY, displayHeaders, true, false);
	currentY += headerHeight;

	// Draw rows
	for (let r = 0; r < opts.rows.length; r++) {
		// Page break check
		if (currentY + rowHeight > doc.page.height - PAGE_MARGIN - 30) {
			doc.addPage();
			currentY = PAGE_MARGIN;
			// Redraw header on new page
			const hh = drawRow(currentY, displayHeaders, true, false);
			currentY += hh;
		}

		const displayRow = isAr ? [...opts.rows[r]].reverse() : opts.rows[r];
		const isLast = r === opts.rows.length - 1 && (opts.highlightLastRow === true);
		const rh = drawRow(currentY, displayRow, false, isLast);
		currentY += rh;
	}

	doc.y = currentY;
	doc.moveDown(0.5);
}

// ─── Summary Boxes ───────────────────────────────────────────────────────
export function renderSummaryBoxes(
	doc: typeof PDFDocument.prototype,
	boxes: { label: string; value: string; color?: string }[],
	language: "ar" | "en",
): void {
	const pageWidth = doc.page.width - PAGE_MARGIN * 2;
	const boxCount = boxes.length;
	const gap = 10;
	const boxWidth = (pageWidth - gap * (boxCount - 1)) / boxCount;
	const boxHeight = 55;
	const isAr = language === "ar";
	const startY = doc.y;

	const displayBoxes = isAr ? [...boxes].reverse() : boxes;

	for (let i = 0; i < displayBoxes.length; i++) {
		const box = displayBoxes[i];
		const x = PAGE_MARGIN + i * (boxWidth + gap);

		// Box background
		doc
			.roundedRect(x, startY, boxWidth, boxHeight, 4)
			.fill(box.color || HEADER_BG);

		// Value (large)
		doc
			.font("Arabic-Bold")
			.fontSize(18)
			.fillColor(TEXT_COLOR)
			.text(box.value, x, startY + 8, {
				width: boxWidth,
				align: "center",
			});

		// Label
		doc
			.font("Arabic")
			.fontSize(FONT_SIZE.small)
			.fillColor(TEXT_MUTED)
			.text(box.label, x, startY + 32, {
				width: boxWidth,
				align: "center",
			});
	}

	doc.y = startY + boxHeight + 10;
}

// ─── Progress Bar ────────────────────────────────────────────────────────
export function renderProgressBar(
	doc: typeof PDFDocument.prototype,
	progress: number,
): void {
	const pageWidth = doc.page.width - PAGE_MARGIN * 2;
	const barHeight = 14;
	const y = doc.y;

	// Background track
	doc.roundedRect(PAGE_MARGIN, y, pageWidth, barHeight, 7).fill("#E5E7EB");

	// Progress fill
	if (progress > 0) {
		const fillWidth = Math.max(14, (pageWidth * Math.min(progress, 100)) / 100);
		doc.roundedRect(PAGE_MARGIN, y, fillWidth, barHeight, 7).fill("#22C55E");
	}

	// Percentage text
	doc
		.font("Arabic-Bold")
		.fontSize(FONT_SIZE.footer)
		.fillColor("#FFFFFF")
		.text(`${progress}%`, PAGE_MARGIN, y + 2, {
			width: pageWidth,
			align: "center",
		});

	doc.y = y + barHeight + 10;
	doc.fillColor(TEXT_COLOR).font("Arabic").fontSize(FONT_SIZE.body);
}

// ─── Status Badge ────────────────────────────────────────────────────────
export function getStatusLabel(status: string, language: "ar" | "en"): string {
	const labels: Record<string, { ar: string; en: string }> = {
		DRAFT: { ar: "مسودة", en: "Draft" },
		SUBMITTED: { ar: "مقدم", en: "Submitted" },
		APPROVED: { ar: "معتمد", en: "Approved" },
		PAID: { ar: "مدفوع", en: "Paid" },
		REJECTED: { ar: "مرفوض", en: "Rejected" },
		OPEN: { ar: "مفتوح", en: "Open" },
		IN_PROGRESS: { ar: "قيد المعالجة", en: "In Progress" },
		RESOLVED: { ar: "محلول", en: "Resolved" },
		CLOSED: { ar: "مغلق", en: "Closed" },
		OFFICIAL_UPDATE: { ar: "تحديث رسمي", en: "Official Update" },
	};

	const entry = labels[status];
	if (entry) return entry[language];
	return status;
}

// ─── Formatting Helpers ──────────────────────────────────────────────────
export function formatDate(date: Date, language: "ar" | "en"): string {
	return new Intl.DateTimeFormat(language === "ar" ? "ar-SA" : "en-US", {
		year: "numeric",
		month: "long",
		day: "numeric",
	}).format(date);
}

export function formatDateShort(date: Date, language: "ar" | "en"): string {
	return new Intl.DateTimeFormat(language === "ar" ? "ar-SA" : "en-US", {
		year: "numeric",
		month: "2-digit",
		day: "2-digit",
	}).format(date);
}

export function formatCurrency(
	amount: number,
	currency: string,
	language: "ar" | "en",
): string {
	return new Intl.NumberFormat("en-US", {
		minimumFractionDigits: 2,
		maximumFractionDigits: 2,
	}).format(amount) + (currency === "SAR" ? " ر.س" : ` ${currency}`);
}

export function formatNumber(amount: number): string {
	return new Intl.NumberFormat("en-US", {
		minimumFractionDigits: 2,
		maximumFractionDigits: 2,
	}).format(amount);
}

// ─── Document to Buffer ──────────────────────────────────────────────────
export function docToBuffer(doc: typeof PDFDocument.prototype): Promise<Buffer> {
	return new Promise<Buffer>((resolve, reject) => {
		const chunks: Buffer[] = [];
		doc.on("data", (chunk: Buffer) => chunks.push(chunk));
		doc.on("end", () => resolve(Buffer.concat(chunks)));
		doc.on("error", reject);

		// Render footers on all buffered pages before finalizing
		renderFootersOnAllPages(doc);

		doc.end();
	});
}
