"use client";

import { orpc } from "@shared/lib/orpc-query-utils";
import {
	useMutation,
	useQuery,
	useQueryClient,
} from "@tanstack/react-query";
import { Button } from "@ui/components/button";
import { Input } from "@ui/components/input";
import { cn } from "@ui/lib";
import {
	ChevronDown,
	ChevronLeft,
	LayoutGrid,
	Loader2,
	Save,
	Sparkles,
	Table2,
} from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { formatNum } from "@saas/pricing/lib/utils";

// ═══════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════

interface FinishingCostingTabProps {
	organizationId: string;
	studyId: string;
}

interface CostingItemFromAPI {
	id: string;
	section: string;
	description: string;
	unit: string;
	quantity: number;
	materialUnitCost: number | null;
	materialTotal: number | null;
	laborType: string | null;
	laborUnitCost: number | null;
	laborQuantity: number | null;
	laborTotal: number | null;
	storageCostPercent: number | null;
	storageCostFixed: number | null;
	storageTotal: number | null;
	otherCosts: number | null;
	totalCost: number | null;
	sourceItemId: string | null;
	sourceItemType: string | null;
}

/** Per-item pricing mode: detailed breakdown vs single lump sum */
type PricingMode = "detailed" | "lumpsum";

/** View mode: card layout vs quick entry table */
type ViewMode = "cards" | "quick";

interface LocalItemState {
	materialUnitCost: string;
	laborUnitCost: string;
	storageCostPercent: string;
	pricingMode: PricingMode;
	lumpSumTotal: string;
}

// ═══════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════

const toNum = (v: string | undefined | null): number =>
	v != null && v !== "" ? Number(v) : 0;

function calcItemTotal(
	quantity: number,
	materialUnitCost: number,
	laborUnitCost: number,
	storagePct: number,
): number {
	const materialTotal = materialUnitCost * quantity;
	const laborTotal = laborUnitCost * quantity;
	const subtotal = materialTotal + laborTotal;
	const storageTotal = subtotal * (storagePct / 100);
	return subtotal + storageTotal;
}

// ═══════════════════════════════════════════════════════════════
// COMPONENT
// ═══════════════════════════════════════════════════════════════

export function FinishingCostingTab({
	organizationId,
	studyId,
}: FinishingCostingTabProps) {
	const queryClient = useQueryClient();

	// ─── View & UI state ───
	const [viewMode, setViewMode] = useState<ViewMode>("cards");
	const [expandedItems, setExpandedItems] = useState<Record<string, boolean>>(
		{},
	);
	const [localState, setLocalState] = useState<
		Record<string, LocalItemState>
	>({});
	const [isDirty, setIsDirty] = useState(false);
	const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
	const hasAutoGenerated = useRef(false);

	// ─── Fetch costing items ───
	const {
		data: costingItems,
		isLoading: itemsLoading,
		isFetched,
	} = useQuery(
		orpc.pricing.studies.costing.getItems.queryOptions({
			input: { organizationId, studyId, section: "FINISHING" },
		}),
	);

	// ─── Generate mutation ───
	const generateMutation = useMutation(
		orpc.pricing.studies.costing.generate.mutationOptions({
			onSuccess: (data: any) => {
				if (data.generated > 0) {
					toast.success(`تم توليد ${data.generated} بند تشطيبات للتسعير`);
				} else {
					toast.info(data.message || "البنود موجودة مسبقاً");
				}
				queryClient.invalidateQueries({
					queryKey: [["pricing", "studies", "costing"]],
				});
			},
			onError: (e: any) => toast.error(e.message || "حدث خطأ أثناء توليد البنود"),
		}),
	);

	// ─── Bulk update mutation ───
	const bulkUpdateMutation = useMutation(
		orpc.pricing.studies.costing.bulkUpdate.mutationOptions({
			onSuccess: () => {
				toast.success("تم حفظ الأسعار بنجاح");
				setIsDirty(false);
				queryClient.invalidateQueries({
					queryKey: [["pricing", "studies", "costing"]],
				});
			},
			onError: (e: any) => toast.error(e.message || "حدث خطأ أثناء الحفظ"),
		}),
	);

	// ─── Single item update mutation ───
	const updateItemMutation = useMutation(
		orpc.pricing.studies.costing.updateItem.mutationOptions({
			onSuccess: () => {
				queryClient.invalidateQueries({
					queryKey: [["pricing", "studies", "costing"]],
				});
			},
			onError: (e: any) => toast.error(e.message || "حدث خطأ أثناء الحفظ"),
		}),
	);

	// ─── Auto-generate costing items on mount if none exist ───
	useEffect(() => {
		if (
			isFetched &&
			!hasAutoGenerated.current &&
			(((costingItems as any) ?? []) as any[]).length === 0
		) {
			hasAutoGenerated.current = true;
			(generateMutation as any).mutate({ organizationId, studyId });
		}
	}, [isFetched, costingItems, organizationId, studyId]); // eslint-disable-line react-hooks/exhaustive-deps

	// ─── Initialize local state from fetched data ───
	useEffect(() => {
		if (!costingItems || (costingItems as any).length === 0) return;

		setLocalState((prev) => {
			const next: Record<string, LocalItemState> = {};
			for (const item of costingItems as CostingItemFromAPI[]) {
				// Preserve user edits if they exist
				if (prev[item.id] && isDirty) {
					next[item.id] = prev[item.id];
				} else {
					next[item.id] = {
						materialUnitCost:
							item.materialUnitCost != null
								? String(item.materialUnitCost)
								: "",
						laborUnitCost:
							item.laborUnitCost != null
								? String(item.laborUnitCost)
								: "",
						storageCostPercent:
							item.storageCostPercent != null
								? String(item.storageCostPercent)
								: "2",
						pricingMode: "detailed",
						lumpSumTotal:
							item.totalCost != null ? String(item.totalCost) : "",
					};
				}
			}
			return next;
		});
	}, [costingItems]); // eslint-disable-line react-hooks/exhaustive-deps

	// ─── Typed costing items ───
	const items = useMemo(
		() => (costingItems ?? []) as CostingItemFromAPI[],
		[costingItems],
	);

	// ─── Update a single field in local state ───
	const updateField = useCallback(
		(itemId: string, field: keyof LocalItemState, value: string) => {
			setLocalState((prev) => ({
				...prev,
				[itemId]: {
					...prev[itemId],
					[field]: value,
				},
			}));
			setIsDirty(true);
		},
		[],
	);

	// ─── Save all items to backend ───
	const handleSave = useCallback(() => {
		const updateItems: Array<{
			id: string;
			materialUnitCost: number | null;
			laborType: "PER_SQM" | "PER_CBM" | "PER_UNIT" | "PER_LM" | "LUMP_SUM" | "SALARY";
			laborUnitCost: number | null;
			laborQuantity: number | null;
		}> = [];

		for (const item of items) {
			const ls = localState[item.id];
			if (!ls) continue;

			if (ls.pricingMode === "lumpsum") {
				// For lump sum, store everything via otherCosts through updateItem
				const lumpTotal = toNum(ls.lumpSumTotal);
				(updateItemMutation as any).mutate({
					organizationId,
					itemId: item.id,
					materialUnitCost: 0,
					laborUnitCost: 0,
					laborQuantity: 0,
					storageCostPercent: 0,
					otherCosts: lumpTotal,
				});
			} else {
				updateItems.push({
					id: item.id,
					materialUnitCost: toNum(ls.materialUnitCost) || null,
					laborType: "PER_UNIT" as const,
					laborUnitCost: toNum(ls.laborUnitCost) || null,
					laborQuantity: item.quantity,
				});
			}
		}

		if (updateItems.length > 0) {
			(bulkUpdateMutation as any).mutate({
				organizationId,
				studyId,
				items: updateItems,
			});
		}
	}, [
		items,
		localState,
		organizationId,
		studyId,
		bulkUpdateMutation,
		updateItemMutation,
	]);

	// ─── Debounced auto-save ───
	useEffect(() => {
		if (!isDirty) return;
		if (debounceRef.current) clearTimeout(debounceRef.current);
		debounceRef.current = setTimeout(() => {
			handleSave();
		}, 3000);
		return () => {
			if (debounceRef.current) clearTimeout(debounceRef.current);
		};
	}, [isDirty, localState]); // eslint-disable-line react-hooks/exhaustive-deps

	// ─── Compute grand total ───
	const grandTotal = useMemo(() => {
		let total = 0;
		for (const item of items) {
			const ls = localState[item.id];
			if (!ls) {
				total += Number(item.totalCost ?? 0);
				continue;
			}
			if (ls.pricingMode === "lumpsum") {
				total += toNum(ls.lumpSumTotal);
			} else {
				total += calcItemTotal(
					Number(item.quantity),
					toNum(ls.materialUnitCost),
					toNum(ls.laborUnitCost),
					toNum(ls.storageCostPercent),
				);
			}
		}
		return total;
	}, [items, localState]);

	// ─── Toggle card expansion ───
	const toggleItem = (id: string) => {
		setExpandedItems((prev) => ({ ...prev, [id]: !prev[id] }));
	};

	// ═══════════════════════════════════════════════════════════════
	// LOADING STATE
	// ═══════════════════════════════════════════════════════════════

	if (itemsLoading || generateMutation.isPending) {
		return (
			<div className="flex flex-col items-center justify-center py-12 gap-3">
				<Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
				<span className="text-sm text-muted-foreground">
					{generateMutation.isPending
						? "جاري توليد بنود التشطيبات..."
						: "جاري تحميل البنود..."}
				</span>
			</div>
		);
	}

	if (items.length === 0) {
		return (
			<div className="rounded-xl border border-border bg-card p-8 text-center space-y-4">
				<p className="text-muted-foreground">
					لا توجد بنود تشطيبات — يمكنك توليدها تلقائياً
				</p>
				<Button
					onClick={() =>
						(generateMutation as any).mutate({ organizationId, studyId })
					}
					disabled={generateMutation.isPending}
					className="gap-2"
				>
					<Sparkles className="h-4 w-4" />
					توليد بنود التسعير
				</Button>
			</div>
		);
	}

	// ═══════════════════════════════════════════════════════════════
	// RENDER
	// ═══════════════════════════════════════════════════════════════

	return (
		<div className="space-y-4" dir="rtl">
			{/* ─── Toolbar: View toggle + Save button ─── */}
			<div className="flex items-center justify-between">
				<div className="flex gap-1 rounded-lg border border-border bg-muted/30 p-1">
					<button
						type="button"
						onClick={() => setViewMode("cards")}
						className={cn(
							"flex items-center gap-1.5 rounded-md px-3 py-1.5 text-sm font-medium transition-all",
							viewMode === "cards"
								? "bg-background text-foreground shadow-sm"
								: "text-muted-foreground hover:text-foreground",
						)}
					>
						<LayoutGrid className="h-3.5 w-3.5" />
						بطاقات
					</button>
					<button
						type="button"
						onClick={() => setViewMode("quick")}
						className={cn(
							"flex items-center gap-1.5 rounded-md px-3 py-1.5 text-sm font-medium transition-all",
							viewMode === "quick"
								? "bg-background text-foreground shadow-sm"
								: "text-muted-foreground hover:text-foreground",
						)}
					>
						<Table2 className="h-3.5 w-3.5" />
						إدخال سريع
					</button>
				</div>

				<Button
					size="sm"
					onClick={handleSave}
					disabled={
						!isDirty ||
						bulkUpdateMutation.isPending ||
						updateItemMutation.isPending
					}
					className="gap-2"
				>
					{bulkUpdateMutation.isPending || updateItemMutation.isPending ? (
						<Loader2 className="h-4 w-4 animate-spin" />
					) : (
						<Save className="h-4 w-4" />
					)}
					حفظ الأسعار
				</Button>
			</div>

			{/* ─── Quick Entry Table Mode ─── */}
			{viewMode === "quick" && (
				<div className="rounded-xl border border-border bg-card overflow-hidden">
					<div className="overflow-x-auto">
						<table className="w-full text-sm">
							<thead>
								<tr className="border-b bg-muted/30 text-muted-foreground">
									<th className="px-3 py-2.5 text-right font-medium w-8">
										#
									</th>
									<th className="px-3 py-2.5 text-right font-medium min-w-[200px]">
										البند
									</th>
									<th className="px-3 py-2.5 text-center font-medium w-20">
										الكمية
									</th>
									<th className="px-3 py-2.5 text-center font-medium w-16">
										الوحدة
									</th>
									<th className="px-3 py-2.5 text-center font-medium w-16">
										النوع
									</th>
									<th className="px-3 py-2.5 text-center font-medium w-24">
										سعر المادة
									</th>
									<th className="px-3 py-2.5 text-center font-medium w-24">
										المصنعية
									</th>
									<th className="px-3 py-2.5 text-center font-medium w-20">
										التشوين%
									</th>
									<th className="px-3 py-2.5 text-center font-medium w-28">
										الإجمالي
									</th>
								</tr>
							</thead>
							<tbody>
								{items.map((item, idx) => {
									const ls = localState[item.id] ?? {
										materialUnitCost: "",
										laborUnitCost: "",
										storageCostPercent: "2",
										pricingMode: "detailed" as PricingMode,
										lumpSumTotal: "",
									};
									const isLumpSum = ls.pricingMode === "lumpsum";
									const rowTotal = isLumpSum
										? toNum(ls.lumpSumTotal)
										: calcItemTotal(
												Number(item.quantity),
												toNum(ls.materialUnitCost),
												toNum(ls.laborUnitCost),
												toNum(ls.storageCostPercent),
											);

									return (
										<tr
											key={item.id}
											className="border-b last:border-0 hover:bg-muted/20 transition-colors"
										>
											<td className="px-3 py-2 text-muted-foreground text-xs">
												{idx + 1}
											</td>
											<td className="px-3 py-2 font-medium text-xs">
												{item.description}
											</td>
											<td
												className="px-3 py-2 text-center tabular-nums"
												dir="ltr"
											>
												{formatNum(Number(item.quantity))}
											</td>
											<td className="px-3 py-2 text-center text-muted-foreground text-xs">
												{item.unit}
											</td>
											<td className="px-3 py-2 text-center">
												<button
													type="button"
													onClick={() =>
														updateField(
															item.id,
															"pricingMode",
															isLumpSum
																? "detailed"
																: "lumpsum",
														)
													}
													className={cn(
														"text-[10px] px-1.5 py-0.5 rounded-md border transition-colors",
														isLumpSum
															? "bg-amber-50 border-amber-200 text-amber-700 dark:bg-amber-900/20 dark:border-amber-700 dark:text-amber-400"
															: "bg-blue-50 border-blue-200 text-blue-700 dark:bg-blue-900/20 dark:border-blue-700 dark:text-blue-400",
													)}
												>
													{isLumpSum ? "مقطوعية" : "تفصيلي"}
												</button>
											</td>
											{isLumpSum ? (
												<>
													<td
														colSpan={3}
														className="px-3 py-2 text-center"
													>
														<Input
															type="number"
															className="h-8 w-32 mx-auto text-center rounded-lg"
															dir="ltr"
															placeholder="المبلغ الإجمالي"
															value={ls.lumpSumTotal}
															onChange={(e: any) =>
																updateField(
																	item.id,
																	"lumpSumTotal",
																	e.target.value,
																)
															}
														/>
													</td>
												</>
											) : (
												<>
													<td className="px-3 py-2">
														<Input
															type="number"
															className="h-8 w-20 mx-auto text-center rounded-lg"
															dir="ltr"
															placeholder="0"
															value={ls.materialUnitCost}
															onChange={(e: any) =>
																updateField(
																	item.id,
																	"materialUnitCost",
																	e.target.value,
																)
															}
														/>
													</td>
													<td className="px-3 py-2">
														<Input
															type="number"
															className="h-8 w-20 mx-auto text-center rounded-lg"
															dir="ltr"
															placeholder="0"
															value={ls.laborUnitCost}
															onChange={(e: any) =>
																updateField(
																	item.id,
																	"laborUnitCost",
																	e.target.value,
																)
															}
														/>
													</td>
													<td className="px-3 py-2">
														<Input
															type="number"
															className="h-8 w-16 mx-auto text-center rounded-lg"
															dir="ltr"
															placeholder="2"
															value={ls.storageCostPercent}
															onChange={(e: any) =>
																updateField(
																	item.id,
																	"storageCostPercent",
																	e.target.value,
																)
															}
														/>
													</td>
												</>
											)}
											<td
												className="px-3 py-2 text-center font-medium tabular-nums"
												dir="ltr"
											>
												{rowTotal > 0
													? formatNum(rowTotal) + " ر.س"
													: "—"}
											</td>
										</tr>
									);
								})}
							</tbody>
						</table>
					</div>
				</div>
			)}

			{/* ─── Cards / Detailed View Mode ─── */}
			{viewMode === "cards" && (
				<div className="space-y-3">
					{items.map((item, idx) => {
						const isExpanded = expandedItems[item.id] !== false;
						const ls = localState[item.id] ?? {
							materialUnitCost: "",
							laborUnitCost: "",
							storageCostPercent: "2",
							pricingMode: "detailed" as PricingMode,
							lumpSumTotal: "",
						};
						const isLumpSum = ls.pricingMode === "lumpsum";

						const materialTotal =
							toNum(ls.materialUnitCost) * Number(item.quantity);
						const laborTotal =
							toNum(ls.laborUnitCost) * Number(item.quantity);
						const storagePct = toNum(ls.storageCostPercent);
						const storageTotal =
							(materialTotal + laborTotal) * (storagePct / 100);
						const itemTotal = isLumpSum
							? toNum(ls.lumpSumTotal)
							: materialTotal + laborTotal + storageTotal;

						return (
							<div
								key={item.id}
								className="rounded-xl border border-border bg-card overflow-hidden"
							>
								{/* Card header */}
								<button
									type="button"
									onClick={() => toggleItem(item.id)}
									className="flex items-center justify-between w-full px-4 py-3 hover:bg-muted/50 transition-colors"
								>
									<div className="flex items-center gap-2">
										{isExpanded ? (
											<ChevronDown className="h-4 w-4 text-muted-foreground" />
										) : (
											<ChevronLeft className="h-4 w-4 text-muted-foreground" />
										)}
										<span className="text-xs text-muted-foreground">
											{idx + 1}.
										</span>
										<span className="font-medium text-sm">
											{item.description}
										</span>
										<span className="text-xs text-muted-foreground">
											({formatNum(Number(item.quantity))}{" "}
											{item.unit})
										</span>
										{isLumpSum && (
											<span className="text-[10px] px-1.5 py-0.5 rounded-md bg-amber-50 border border-amber-200 text-amber-700 dark:bg-amber-900/20 dark:border-amber-700 dark:text-amber-400">
												مقطوعية
											</span>
										)}
									</div>
									<span
										className="text-sm font-medium tabular-nums"
										dir="ltr"
									>
										{itemTotal > 0
											? formatNum(itemTotal) + " ر.س"
											: "—"}
									</span>
								</button>

								{isExpanded && (
									<div className="border-t border-border">
										{/* Pricing mode toggle */}
										<div className="px-4 py-3 flex items-center gap-3 bg-muted/10">
											<span className="text-xs text-muted-foreground">
												نوع التسعير:
											</span>
											<div className="flex gap-1 rounded-md border border-border p-0.5">
												<button
													type="button"
													onClick={() =>
														updateField(
															item.id,
															"pricingMode",
															"detailed",
														)
													}
													className={cn(
														"px-2.5 py-1 rounded text-xs font-medium transition-all",
														!isLumpSum
															? "bg-primary text-primary-foreground"
															: "text-muted-foreground hover:text-foreground",
													)}
												>
													تفصيلي
												</button>
												<button
													type="button"
													onClick={() =>
														updateField(
															item.id,
															"pricingMode",
															"lumpsum",
														)
													}
													className={cn(
														"px-2.5 py-1 rounded text-xs font-medium transition-all",
														isLumpSum
															? "bg-primary text-primary-foreground"
															: "text-muted-foreground hover:text-foreground",
													)}
												>
													مقطوعية
												</button>
											</div>
										</div>

										{isLumpSum ? (
											/* ─── Lump Sum Mode ─── */
											<div className="px-4 py-4 space-y-3">
												<div className="flex items-center gap-4">
													<span className="text-sm text-muted-foreground w-28">
														المبلغ الإجمالي:
													</span>
													<Input
														type="number"
														className="h-9 w-40 text-center rounded-lg"
														dir="ltr"
														placeholder="0"
														value={ls.lumpSumTotal}
														onChange={(e: any) =>
															updateField(
																item.id,
																"lumpSumTotal",
																e.target.value,
															)
														}
													/>
													<span className="text-xs text-muted-foreground">
														ر.س
													</span>
												</div>
											</div>
										) : (
											/* ─── Detailed Mode ─── */
											<div className="px-4 py-3 space-y-3">
												{/* Material cost */}
												<div className="flex items-center gap-4 text-sm">
													<span className="text-muted-foreground w-28">
														سعر المادة:
													</span>
													<div className="flex items-center gap-2">
														<Input
															type="number"
															className="h-8 w-24 text-center rounded-lg"
															dir="ltr"
															placeholder="0"
															value={
																ls.materialUnitCost
															}
															onChange={(e: any) =>
																updateField(
																	item.id,
																	"materialUnitCost",
																	e.target.value,
																)
															}
														/>
														<span className="text-xs text-muted-foreground">
															ر.س/{item.unit}
														</span>
														{materialTotal > 0 && (
															<span
																className="text-sm font-medium ml-2"
																dir="ltr"
															>
																={" "}
																{formatNum(
																	materialTotal,
																)}{" "}
																ر.س
															</span>
														)}
													</div>
												</div>

												{/* Labor cost */}
												<div className="flex items-center gap-4 text-sm">
													<span className="text-muted-foreground w-28">
														المصنعية:
													</span>
													<div className="flex items-center gap-2">
														<Input
															type="number"
															className="h-8 w-24 text-center rounded-lg"
															dir="ltr"
															placeholder="0"
															value={ls.laborUnitCost}
															onChange={(e: any) =>
																updateField(
																	item.id,
																	"laborUnitCost",
																	e.target.value,
																)
															}
														/>
														<span className="text-xs text-muted-foreground">
															ر.س/{item.unit}
														</span>
														{laborTotal > 0 && (
															<span
																className="text-sm font-medium ml-2"
																dir="ltr"
															>
																={" "}
																{formatNum(
																	laborTotal,
																)}{" "}
																ر.س
															</span>
														)}
													</div>
												</div>

												{/* Storage cost */}
												<div className="flex items-center gap-4 text-sm">
													<span className="text-muted-foreground w-28">
														التشوين:
													</span>
													<div className="flex items-center gap-2">
														<Input
															type="number"
															className="h-8 w-16 text-center rounded-lg"
															dir="ltr"
															placeholder="2"
															value={
																ls.storageCostPercent
															}
															onChange={(e: any) =>
																updateField(
																	item.id,
																	"storageCostPercent",
																	e.target.value,
																)
															}
														/>
														<span className="text-xs text-muted-foreground">
															%
														</span>
														{storageTotal > 0 && (
															<span
																className="text-sm font-medium ml-2"
																dir="ltr"
															>
																={" "}
																{formatNum(
																	storageTotal,
																)}{" "}
																ر.س
															</span>
														)}
													</div>
												</div>

												{/* Item total */}
												<div className="flex items-center gap-4 text-sm border-t border-border pt-3">
													<span className="font-medium w-28">
														إجمالي البند:
													</span>
													<span
														className="font-bold text-primary"
														dir="ltr"
													>
														{itemTotal > 0
															? formatNum(itemTotal) +
																" ر.س"
															: "—"}
													</span>
												</div>
											</div>
										)}
									</div>
								)}
							</div>
						);
					})}
				</div>
			)}

			{/* ─── Grand Total Footer ─── */}
			<div className="rounded-xl border-2 border-primary/30 bg-primary/5 px-5 py-4 flex items-center justify-between">
				<div className="flex items-center gap-2">
					<span className="font-bold text-base">
						إجمالي التشطيبات
					</span>
					<span className="text-xs text-muted-foreground">
						({items.length} بند)
					</span>
				</div>
				<span
					className="text-lg font-bold text-primary tabular-nums"
					dir="ltr"
				>
					{grandTotal > 0 ? formatNum(grandTotal) + " ر.س" : "—"}
				</span>
			</div>

			{/* ─── Dirty indicator ─── */}
			{isDirty && (
				<p className="text-xs text-muted-foreground text-center">
					لديك تغييرات غير محفوظة — سيتم الحفظ تلقائياً أو اضغط "حفظ
					الأسعار"
				</p>
			)}
		</div>
	);
}
