import type { CatalogEntry } from "../types";

// الأسقف المستعارة

export const CEILING_CATALOG: CatalogEntry[] = [
	{
		itemKey: "finishing.ceiling.gypsum_board",
		domain: "FINISHING",
		categoryKey: "ceiling",
		subcategoryKey: "gypsum_board",
		nameAr: "سقف جبس بورد",
		nameEn: "Gypsum Board Ceiling",
		descriptionAr: "سقف مستعار جبس بورد مع إنارة مدفونة",
		descriptionEn: "False gypsum board ceiling with recessed lighting",
		icon: "Layers3",
		color: "#94A3B8",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة السقف", unit: "m²", defaultSuggestion: "fromContext.totalFloorArea", min: 0 },
		},
		defaultMaterialUnitPrice: 55,
		defaultLaborUnitPrice: 30,
		commonMaterials: [
			{ nameAr: "Knauf لوح 9.5مم", nameEn: "Knauf 9.5mm", brand: "Knauf", grade: "عادي", suggestedPrice: 16, source: "imported" },
			{ nameAr: "Knauf مقاوم رطوبة", nameEn: "Knauf MR", brand: "Knauf", grade: "فاخر", suggestedPrice: 26, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 610,
	},
	{
		itemKey: "finishing.ceiling.metal_grid",
		domain: "FINISHING",
		categoryKey: "ceiling",
		subcategoryKey: "metal_grid",
		nameAr: "سقف مشبّك معدني (T-Bar)",
		nameEn: "Metal Grid Ceiling (T-Bar)",
		descriptionAr: "سقف مشبّك معدني للمكاتب والمحلات",
		descriptionEn: "Metal grid ceiling for offices and shops",
		icon: "Grid3x3",
		color: "#64748B",
		unit: "m²",
		defaultWastagePercent: 8,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة السقف", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 45,
		defaultLaborUnitPrice: 22,
		commonMaterials: [
			{ nameAr: "Armstrong Mineral Fiber", nameEn: "Armstrong Mineral Fiber", brand: "Armstrong", grade: "فاخر", suggestedPrice: 60, source: "imported" },
			{ nameAr: "USG ألواح صوتية", nameEn: "USG Acoustic Tiles", brand: "USG", grade: "فاخر", suggestedPrice: 55, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 620,
	},
	{
		itemKey: "finishing.ceiling.decorative",
		domain: "FINISHING",
		categoryKey: "ceiling",
		subcategoryKey: "decorative",
		nameAr: "سقف ديكوري (كورنيش/قوس/جزر)",
		nameEn: "Decorative Ceiling (Cornice / Tray)",
		descriptionAr: "أسقف ديكورية بمستويات وكورنيش",
		descriptionEn: "Decorative multi-level tray ceilings with cornices",
		icon: "Sparkles",
		color: "#A855F7",
		unit: "m²",
		defaultWastagePercent: 15,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة السقف الديكوري", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 95,
		defaultLaborUnitPrice: 55,
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 630,
	},
	{
		itemKey: "finishing.ceiling.acoustic",
		domain: "FINISHING",
		categoryKey: "ceiling",
		subcategoryKey: "acoustic",
		nameAr: "سقف عازل صوتي",
		nameEn: "Acoustic Ceiling",
		descriptionAr: "سقف بألواح عازلة للصوت (مكاتب، مدارس، عيادات)",
		descriptionEn: "Sound-absorbing ceiling tiles",
		icon: "Volume2",
		color: "#0E7490",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة السقف", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 80,
		defaultLaborUnitPrice: 30,
		commonMaterials: [
			{ nameAr: "Rockfon Mineral Wool", nameEn: "Rockfon Mineral Wool", brand: "Rockfon", grade: "فاخر", suggestedPrice: 95, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 640,
	},
];
