import type { CatalogEntry } from "../types";

// تكسيات الواجهات الخارجية

export const CLADDING_CATALOG: CatalogEntry[] = [
	{
		itemKey: "finishing.cladding.marble_facade",
		domain: "FINISHING",
		categoryKey: "cladding",
		subcategoryKey: "marble_facade",
		nameAr: "تكسية رخام للواجهات",
		nameEn: "Marble Facade Cladding",
		descriptionAr: "تكسية رخام طبيعي للواجهات الخارجية",
		descriptionEn: "Natural marble cladding for exterior facades",
		icon: "Gem",
		color: "#94A3B8",
		unit: "m²",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الواجهة", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 280,
		defaultLaborUnitPrice: 80,
		commonMaterials: [
			{ nameAr: "رخام تركي بيج فاتح", nameEn: "Turkish Light Beige", grade: "عادي", suggestedPrice: 240, source: "imported" },
			{ nameAr: "كرارا إيطالي للواجهات", nameEn: "Italian Carrara Facade", grade: "فاخر", suggestedPrice: 480, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "external",
		displayOrder: 910,
	},
	{
		itemKey: "finishing.cladding.natural_stone",
		domain: "FINISHING",
		categoryKey: "cladding",
		subcategoryKey: "natural_stone",
		nameAr: "تكسية حجر طبيعي للواجهات",
		nameEn: "Natural Stone Facade",
		descriptionAr: "تكسية حجر طبيعي رياضي/جدة للواجهات",
		descriptionEn: "Natural stone (Riyadh / Jeddah) facade cladding",
		icon: "Mountain",
		color: "#78716C",
		unit: "m²",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الواجهة", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 160,
		defaultLaborUnitPrice: 60,
		commonMaterials: [
			{ nameAr: "حجر رياض طبيعي", nameEn: "Riyadh Stone", grade: "عادي", suggestedPrice: 150, source: "local" },
			{ nameAr: "حجر جدة", nameEn: "Jeddah Stone", grade: "عادي", suggestedPrice: 145, source: "local" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "external",
		displayOrder: 920,
	},
	{
		itemKey: "finishing.cladding.alucobond",
		domain: "FINISHING",
		categoryKey: "cladding",
		subcategoryKey: "alucobond",
		nameAr: "ألوكوبوند",
		nameEn: "Aluminum Composite Panels (ACP)",
		descriptionAr: "ألواح ألمنيوم مركبة للواجهات الحديثة",
		descriptionEn: "Aluminum composite panels for modern facades",
		icon: "Square",
		color: "#0EA5E9",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الواجهة", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 220,
		defaultLaborUnitPrice: 90,
		commonMaterials: [
			{ nameAr: "Alucobond ألماني", nameEn: "Alucobond Germany", brand: "Alucobond", grade: "فاخر", suggestedPrice: 280, source: "imported" },
			{ nameAr: "Reynobond فرنسي", nameEn: "Reynobond France", brand: "Reynobond", grade: "فاخر", suggestedPrice: 260, source: "imported" },
			{ nameAr: "ACP صيني", nameEn: "Chinese ACP", grade: "اقتصادي", suggestedPrice: 140, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "external",
		displayOrder: 930,
	},
	{
		itemKey: "finishing.cladding.hpl",
		domain: "FINISHING",
		categoryKey: "cladding",
		subcategoryKey: "hpl",
		nameAr: "HPL (لوح ضغط عالي)",
		nameEn: "HPL (High-Pressure Laminate)",
		descriptionAr: "ألواح HPL مقاومة للعوامل الجوية",
		descriptionEn: "Weather-resistant HPL panels",
		icon: "Layers",
		color: "#475569",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الواجهة", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 260,
		defaultLaborUnitPrice: 100,
		commonMaterials: [
			{ nameAr: "Trespa HPL", nameEn: "Trespa HPL", brand: "Trespa", grade: "فاخر", suggestedPrice: 380, source: "imported" },
			{ nameAr: "Fundermax HPL", nameEn: "Fundermax HPL", brand: "Fundermax", grade: "فاخر", suggestedPrice: 360, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "external",
		displayOrder: 940,
	},
];
