import type { CatalogEntry } from "../types";

// الأبواب — تُحسب بالعدد (per_unit)
// السعر يشمل المصنعية والتركيب لباب جاهز كامل

export const DOORS_CATALOG: CatalogEntry[] = [
	{
		itemKey: "finishing.doors.interior_wood",
		domain: "FINISHING",
		categoryKey: "doors",
		subcategoryKey: "interior_wood",
		nameAr: "باب خشب داخلي",
		nameEn: "Interior Wood Door",
		descriptionAr: "باب خشبي داخلي 90×210 مع إطار وأكسسوار",
		descriptionEn: "Interior wood door 90×210 with frame and hardware",
		icon: "DoorOpen",
		color: "#92400E",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "عدد الأبواب", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 750,
		defaultLaborUnitPrice: 100,
		commonMaterials: [
			{ nameAr: "باب خشب محلي MDF", nameEn: "Local MDF Wood Door", grade: "عادي", suggestedPrice: 750, source: "local" },
			{ nameAr: "باب تركي صلب", nameEn: "Turkish Solid Wood Door", grade: "فاخر", suggestedPrice: 1400, source: "imported" },
			{ nameAr: "باب صيني اقتصادي", nameEn: "Chinese Economy Door", grade: "اقتصادي", suggestedPrice: 450, source: "imported" },
		],
		legacyDerivationType: "per_room",
		legacyScope: "per_floor",
		displayOrder: 710,
	},
	{
		itemKey: "finishing.doors.hdf",
		domain: "FINISHING",
		categoryKey: "doors",
		subcategoryKey: "hdf",
		nameAr: "باب HDF خفيف",
		nameEn: "HDF Light Door",
		descriptionAr: "باب HDF عازل خفيف للغرف الداخلية",
		descriptionEn: "Lightweight HDF interior door",
		icon: "DoorOpen",
		color: "#A16207",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "عدد الأبواب", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 450,
		defaultLaborUnitPrice: 80,
		legacyDerivationType: "per_room",
		legacyScope: "per_floor",
		displayOrder: 720,
	},
	{
		itemKey: "finishing.doors.exterior_steel",
		domain: "FINISHING",
		categoryKey: "doors",
		subcategoryKey: "exterior_steel",
		nameAr: "باب خارجي حديد/أمن",
		nameEn: "Exterior Steel / Security Door",
		descriptionAr: "باب رئيسي خارجي بحماية أمنية وعزل حراري",
		descriptionEn: "Exterior security door with thermal insulation",
		icon: "ShieldCheck",
		color: "#0F172A",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "عدد الأبواب", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 2200,
		defaultLaborUnitPrice: 200,
		commonMaterials: [
			{ nameAr: "باب أمن تركي", nameEn: "Turkish Security Door", grade: "فاخر", suggestedPrice: 2800, source: "imported" },
			{ nameAr: "باب حديد محلي", nameEn: "Local Steel Door", grade: "عادي", suggestedPrice: 1800, source: "local" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "external",
		displayOrder: 730,
	},
	{
		itemKey: "finishing.doors.fire_rated",
		domain: "FINISHING",
		categoryKey: "doors",
		subcategoryKey: "fire_rated",
		nameAr: "باب مقاوم حريق",
		nameEn: "Fire-Rated Door",
		descriptionAr: "باب مقاوم للحريق 60-90 دقيقة (سلالم، غرف كهرباء)",
		descriptionEn: "Fire-rated door (60-90 min) for stairs and electrical rooms",
		icon: "Flame",
		color: "#DC2626",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "عدد الأبواب", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 2500,
		defaultLaborUnitPrice: 250,
		legacyDerivationType: "per_unit",
		legacyScope: "per_floor",
		displayOrder: 740,
	},
	{
		itemKey: "finishing.doors.glass",
		domain: "FINISHING",
		categoryKey: "doors",
		subcategoryKey: "glass",
		nameAr: "باب زجاجي (سيكوريت/منزلق)",
		nameEn: "Glass Door (Tempered / Sliding)",
		descriptionAr: "باب زجاج سيكوريت أو منزلق (محلات، مكاتب)",
		descriptionEn: "Tempered or sliding glass door",
		icon: "RectangleVertical",
		color: "#0EA5E9",
		unit: "عدد",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "عدد الأبواب", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 1800,
		defaultLaborUnitPrice: 250,
		legacyDerivationType: "per_unit",
		legacyScope: "per_floor",
		displayOrder: 750,
	},
	{
		itemKey: "finishing.doors.aluminum",
		domain: "FINISHING",
		categoryKey: "doors",
		subcategoryKey: "aluminum",
		nameAr: "باب ألمنيوم (شرفات/خدمات)",
		nameEn: "Aluminum Door (Balcony / Service)",
		descriptionAr: "باب ألمنيوم لشرفات أو خدمات",
		descriptionEn: "Aluminum door for balcony or service areas",
		icon: "DoorOpen",
		color: "#94A3B8",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "عدد الأبواب", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 950,
		defaultLaborUnitPrice: 120,
		legacyDerivationType: "per_unit",
		legacyScope: "per_floor",
		displayOrder: 760,
	},
];
