import type { CatalogEntry } from "../types";

// أعمال الأرضيات

export const FLOORING_CATALOG: CatalogEntry[] = [
	{
		itemKey: "finishing.flooring.ceramic",
		domain: "FINISHING",
		categoryKey: "flooring",
		subcategoryKey: "ceramic",
		nameAr: "سيراميك أرضي",
		nameEn: "Ceramic Floor Tiles",
		descriptionAr: "سيراميك أرضي للغرف والممرات",
		descriptionEn: "Ceramic floor tiles for rooms and corridors",
		icon: "LayoutGrid",
		color: "#0891B2",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الأرضية", unit: "m²", defaultSuggestion: "fromContext.totalFloorArea", min: 0 },
		},
		defaultMaterialUnitPrice: 35,
		defaultLaborUnitPrice: 15,
		commonMaterials: [
			{ nameAr: "السعودي للسيراميك 60×60", nameEn: "Saudi Ceramic 60x60", brand: "Saudi Ceramic", grade: "عادي", suggestedPrice: 35, source: "local" },
			{ nameAr: "اليمامة 45×45", nameEn: "Al Yamamah 45x45", brand: "Al Yamamah", grade: "اقتصادي", suggestedPrice: 25, source: "local" },
			{ nameAr: "RAK Ceramics 60×60", nameEn: "RAK 60x60", brand: "RAK", grade: "فاخر", suggestedPrice: 55, source: "imported" },
			{ nameAr: "كليوباترا المصري", nameEn: "Cleopatra Egyptian", brand: "Cleopatra", grade: "عادي", suggestedPrice: 32, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 410,
	},
	{
		itemKey: "finishing.flooring.porcelain",
		domain: "FINISHING",
		categoryKey: "flooring",
		subcategoryKey: "porcelain",
		nameAr: "بورسلين",
		nameEn: "Porcelain Tiles",
		descriptionAr: "بلاط بورسلين عالي الكثافة للأرضيات",
		descriptionEn: "High-density porcelain floor tiles",
		icon: "LayoutGrid",
		color: "#0E7490",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الأرضية", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 75,
		defaultLaborUnitPrice: 22,
		commonMaterials: [
			{ nameAr: "السعودي بورسلين 80×80", nameEn: "Saudi Porcelain 80x80", brand: "Saudi Ceramic", grade: "عادي", suggestedPrice: 75, source: "local" },
			{ nameAr: "RAK Porcelain 60×120", nameEn: "RAK 60x120", brand: "RAK", grade: "فاخر", suggestedPrice: 110, source: "imported" },
			{ nameAr: "Florim إيطالي", nameEn: "Florim Italy", brand: "Florim", grade: "فاخر", suggestedPrice: 180, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 420,
	},
	{
		itemKey: "finishing.flooring.marble",
		domain: "FINISHING",
		categoryKey: "flooring",
		subcategoryKey: "marble",
		nameAr: "رخام",
		nameEn: "Marble Flooring",
		descriptionAr: "رخام طبيعي للأرضيات والمداخل",
		descriptionEn: "Natural marble for floors and entrances",
		icon: "Gem",
		color: "#94A3B8",
		unit: "m²",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الرخام", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 220,
		defaultLaborUnitPrice: 60,
		commonMaterials: [
			{ nameAr: "رخام تركي بيج", nameEn: "Turkish Beige Marble", grade: "عادي", suggestedPrice: 200, source: "imported" },
			{ nameAr: "رخام مصري شيلال", nameEn: "Egyptian Shellal", grade: "عادي", suggestedPrice: 180, source: "imported" },
			{ nameAr: "كرارا إيطالي", nameEn: "Italian Carrara", grade: "فاخر", suggestedPrice: 450, source: "imported" },
			{ nameAr: "كريما مارفيل إسباني", nameEn: "Spanish Crema Marfil", grade: "فاخر", suggestedPrice: 380, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 430,
	},
	{
		itemKey: "finishing.flooring.granite",
		domain: "FINISHING",
		categoryKey: "flooring",
		subcategoryKey: "granite",
		nameAr: "جرانيت",
		nameEn: "Granite Flooring",
		descriptionAr: "جرانيت طبيعي للأرضيات (سلالم، مداخل)",
		descriptionEn: "Natural granite for floors (stairs, entries)",
		icon: "Mountain",
		color: "#57534E",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الجرانيت", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 280,
		defaultLaborUnitPrice: 70,
		commonMaterials: [
			{ nameAr: "جرانيت برازيلي أسود", nameEn: "Brazilian Black", grade: "فاخر", suggestedPrice: 320, source: "imported" },
			{ nameAr: "جرانيت هندي ريد", nameEn: "Indian Red Granite", grade: "عادي", suggestedPrice: 250, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 440,
	},
	{
		itemKey: "finishing.flooring.parquet",
		domain: "FINISHING",
		categoryKey: "flooring",
		subcategoryKey: "parquet",
		nameAr: "باركيه",
		nameEn: "Parquet / Laminate",
		descriptionAr: "أرضيات خشبية باركيه أو لامينيت",
		descriptionEn: "Wood parquet or laminate flooring",
		icon: "TreePine",
		color: "#7C2D12",
		unit: "m²",
		defaultWastagePercent: 8,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الأرضية", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 90,
		defaultLaborUnitPrice: 25,
		commonMaterials: [
			{ nameAr: "Pergo لامينيت 8مم", nameEn: "Pergo Laminate 8mm", brand: "Pergo", grade: "فاخر", suggestedPrice: 130, source: "imported" },
			{ nameAr: "لامينيت محلي 8مم", nameEn: "Local Laminate 8mm", grade: "عادي", suggestedPrice: 75, source: "local" },
			{ nameAr: "باركيه خشب صلب", nameEn: "Solid Hardwood Parquet", grade: "فاخر", suggestedPrice: 250, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 450,
	},
	{
		itemKey: "finishing.flooring.epoxy",
		domain: "FINISHING",
		categoryKey: "flooring",
		subcategoryKey: "epoxy",
		nameAr: "أرضيات إيبوكسي",
		nameEn: "Epoxy Flooring",
		descriptionAr: "أرضيات إيبوكسي للمستودعات والمواقف والمختبرات",
		descriptionEn: "Epoxy floors for warehouses, parking, labs",
		icon: "Layers",
		color: "#1E40AF",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الأرضية", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 80,
		defaultLaborUnitPrice: 35,
		commonMaterials: [
			{ nameAr: "Sika Sikafloor 264", nameEn: "Sika Sikafloor 264", brand: "Sika", grade: "فاخر", suggestedPrice: 130, source: "imported" },
			{ nameAr: "Jotun Jotafloor", nameEn: "Jotun Jotafloor", brand: "Jotun", grade: "فاخر", suggestedPrice: 125, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 460,
	},
	{
		itemKey: "finishing.flooring.vinyl",
		domain: "FINISHING",
		categoryKey: "flooring",
		subcategoryKey: "vinyl",
		nameAr: "فينيل / PVC",
		nameEn: "Vinyl / PVC Flooring",
		descriptionAr: "أرضيات فينيل للمكاتب والعيادات",
		descriptionEn: "Vinyl flooring for offices and clinics",
		icon: "Disc",
		color: "#475569",
		unit: "m²",
		defaultWastagePercent: 8,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الأرضية", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 55,
		defaultLaborUnitPrice: 18,
		commonMaterials: [
			{ nameAr: "Tarkett Vinyl", nameEn: "Tarkett Vinyl", brand: "Tarkett", grade: "فاخر", suggestedPrice: 85, source: "imported" },
			{ nameAr: "LG Hausys", nameEn: "LG Hausys Vinyl", brand: "LG Hausys", grade: "فاخر", suggestedPrice: 75, source: "imported" },
			{ nameAr: "فينيل صيني", nameEn: "Chinese Vinyl", grade: "اقتصادي", suggestedPrice: 35, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 470,
	},
	{
		itemKey: "finishing.flooring.terrazzo",
		domain: "FINISHING",
		categoryKey: "flooring",
		subcategoryKey: "terrazzo",
		nameAr: "ترازو",
		nameEn: "Terrazzo Flooring",
		descriptionAr: "أرضيات ترازو مصبوب أو بلاط ترازو جاهز",
		descriptionEn: "Cast-in-place or pre-cast terrazzo",
		icon: "Sparkles",
		color: "#9CA3AF",
		unit: "m²",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الترازو", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 110,
		defaultLaborUnitPrice: 40,
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 480,
	},
];
