import type { CatalogEntry } from "../types";

// أعمال العزل الحراري والمائي والصوتي

export const INSULATION_CATALOG: CatalogEntry[] = [
	{
		itemKey: "finishing.insulation.thermal_roof",
		domain: "FINISHING",
		categoryKey: "insulation",
		subcategoryKey: "thermal_roof",
		nameAr: "عزل حراري للسقف",
		nameEn: "Roof Thermal Insulation",
		descriptionAr: "ألواح عزل حراري للسقف (فوم/صوف صخري)",
		descriptionEn: "Thermal insulation boards for roof",
		icon: "Snowflake",
		color: "#10B981",
		unit: "m²",
		defaultWastagePercent: 8,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة السطح", unit: "m²", defaultSuggestion: "fromContext.totalRoofArea", min: 0 },
		},
		defaultMaterialUnitPrice: 35,
		defaultLaborUnitPrice: 18,
		commonMaterials: [
			{ nameAr: "بوليسترين XPS 5سم", nameEn: "XPS Polystyrene 50mm", grade: "عادي", suggestedPrice: 32, source: "local" },
			{ nameAr: "Rockwool صوف صخري", nameEn: "Rockwool Stone Wool", brand: "Rockwool", grade: "فاخر", suggestedPrice: 45, source: "imported" },
			{ nameAr: "Foam Glass خلوي", nameEn: "Foam Glass", grade: "فاخر", suggestedPrice: 80, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "whole_building",
		displayOrder: 10,
	},
	{
		itemKey: "finishing.insulation.waterproof_roof",
		domain: "FINISHING",
		categoryKey: "insulation",
		subcategoryKey: "waterproof_roof",
		nameAr: "عزل مائي للسقف",
		nameEn: "Roof Waterproofing",
		descriptionAr: "عزل مائي للسقف (لفائف بيتومين أو دهان عازل)",
		descriptionEn: "Roof waterproofing (bitumen rolls or coating)",
		icon: "Droplets",
		color: "#06B6D4",
		unit: "m²",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة العزل", unit: "m²", defaultSuggestion: "fromContext.totalRoofArea", min: 0 },
		},
		defaultMaterialUnitPrice: 28,
		defaultLaborUnitPrice: 12,
		commonMaterials: [
			{ nameAr: "Sika Sikalastic", nameEn: "Sika Sikalastic", brand: "Sika", grade: "فاخر", suggestedPrice: 45, source: "imported" },
			{ nameAr: "بيتومين APP لفائف", nameEn: "APP Bitumen Membrane", grade: "عادي", suggestedPrice: 25, source: "local" },
			{ nameAr: "Mapei عزل بوليمر", nameEn: "Mapei Polymer", brand: "Mapei", grade: "فاخر", suggestedPrice: 50, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "whole_building",
		displayOrder: 20,
	},
	{
		itemKey: "finishing.insulation.thermal_walls",
		domain: "FINISHING",
		categoryKey: "insulation",
		subcategoryKey: "thermal_walls",
		nameAr: "عزل حراري للجدران الخارجية",
		nameEn: "Exterior Wall Thermal Insulation",
		descriptionAr: "عزل حراري للجدران الخارجية (فوم/صوف زجاجي)",
		descriptionEn: "Thermal insulation for exterior walls",
		icon: "Snowflake",
		color: "#06B6D4",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الجدران الخارجية", unit: "m²", defaultSuggestion: "fromContext.totalExteriorWallArea", min: 0 },
		},
		defaultMaterialUnitPrice: 30,
		defaultLaborUnitPrice: 15,
		legacyDerivationType: "direct_area",
		legacyScope: "external",
		displayOrder: 30,
	},
	{
		itemKey: "finishing.insulation.acoustic",
		domain: "FINISHING",
		categoryKey: "insulation",
		subcategoryKey: "acoustic",
		nameAr: "عزل صوتي للجدران/الأسقف",
		nameEn: "Acoustic Insulation",
		descriptionAr: "عزل صوتي للجدران الفاصلة أو الأسقف",
		descriptionEn: "Acoustic insulation for partitions or ceilings",
		icon: "Volume2",
		color: "#7C3AED",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة العزل", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 28,
		defaultLaborUnitPrice: 12,
		commonMaterials: [
			{ nameAr: "Rockwool 50مم صوتي", nameEn: "Rockwool 50mm Acoustic", brand: "Rockwool", grade: "فاخر", suggestedPrice: 38, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 40,
	},
	{
		itemKey: "finishing.insulation.foundation",
		domain: "FINISHING",
		categoryKey: "insulation",
		subcategoryKey: "foundation",
		nameAr: "عزل أساسات (مائي)",
		nameEn: "Foundation Waterproofing",
		descriptionAr: "عزل مائي للأساسات والقواعد قبل الردم",
		descriptionEn: "Foundation waterproofing before backfilling",
		icon: "Square",
		color: "#0E7490",
		unit: "m²",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة العزل", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 22,
		defaultLaborUnitPrice: 10,
		legacyDerivationType: "direct_area",
		legacyScope: "whole_building",
		displayOrder: 50,
	},
];
