import type { CatalogEntry } from "../types";

// المطابخ والكاونترات

export const KITCHEN_CATALOG: CatalogEntry[] = [
	{
		itemKey: "finishing.kitchen.cabinets",
		domain: "FINISHING",
		categoryKey: "kitchen",
		subcategoryKey: "cabinets",
		nameAr: "خزائن مطبخ",
		nameEn: "Kitchen Cabinets",
		descriptionAr: "خزائن مطبخ علوية وسفلية بالمتر الطولي",
		descriptionEn: "Upper and lower kitchen cabinets per meter",
		icon: "ChefHat",
		color: "#92400E",
		unit: "م.ط",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "length_only",
		requiredFields: {
			primary: { key: "length", label: "طول الخزائن", unit: "م.ط", min: 0 },
		},
		defaultMaterialUnitPrice: 1400,
		defaultLaborUnitPrice: 200,
		commonMaterials: [
			{ nameAr: "خشب MDF محلي مع HPL", nameEn: "Local MDF with HPL", grade: "عادي", suggestedPrice: 1300, source: "local" },
			{ nameAr: "خشب لاكيه فاخر", nameEn: "Premium Lacquer Finish", grade: "فاخر", suggestedPrice: 2500, source: "imported" },
			{ nameAr: "Ikea نظام METOD", nameEn: "Ikea METOD System", brand: "Ikea", grade: "عادي", suggestedPrice: 1800, source: "imported" },
		],
		legacyDerivationType: "length_only",
		legacyScope: "per_floor",
		displayOrder: 1110,
	},
	{
		itemKey: "finishing.kitchen.countertop",
		domain: "FINISHING",
		categoryKey: "kitchen",
		subcategoryKey: "countertop",
		nameAr: "كاونتر مطبخ",
		nameEn: "Kitchen Countertop",
		descriptionAr: "كاونتر مطبخ (كوارتز/جرانيت/سيراميك)",
		descriptionEn: "Kitchen countertop (quartz / granite / ceramic)",
		icon: "Square",
		color: "#1F2937",
		unit: "م.ط",
		defaultWastagePercent: 8,
		defaultCalculationMethod: "length_only",
		requiredFields: {
			primary: { key: "length", label: "طول الكاونتر", unit: "م.ط", min: 0 },
		},
		defaultMaterialUnitPrice: 650,
		defaultLaborUnitPrice: 100,
		commonMaterials: [
			{ nameAr: "كوارتز Caesarstone", nameEn: "Caesarstone Quartz", brand: "Caesarstone", grade: "فاخر", suggestedPrice: 950, source: "imported" },
			{ nameAr: "كوارتز Silestone", nameEn: "Silestone", brand: "Silestone", grade: "فاخر", suggestedPrice: 900, source: "imported" },
			{ nameAr: "جرانيت برازيلي", nameEn: "Brazilian Granite", grade: "عادي", suggestedPrice: 600, source: "imported" },
			{ nameAr: "كوارتز صيني", nameEn: "Chinese Quartz", grade: "اقتصادي", suggestedPrice: 400, source: "imported" },
		],
		legacyDerivationType: "length_only",
		legacyScope: "per_floor",
		displayOrder: 1120,
	},
	{
		itemKey: "finishing.kitchen.backsplash",
		domain: "FINISHING",
		categoryKey: "kitchen",
		subcategoryKey: "backsplash",
		nameAr: "Backsplash مطبخ ديكوري",
		nameEn: "Decorative Kitchen Backsplash",
		descriptionAr: "تكسية ديكورية بين الكاونتر والخزائن العلوية",
		descriptionEn: "Decorative tile between countertop and upper cabinets",
		icon: "Grid",
		color: "#EA580C",
		unit: "m²",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة Backsplash", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 80,
		defaultLaborUnitPrice: 35,
		commonMaterials: [
			{ nameAr: "موزاييك زجاج", nameEn: "Glass Mosaic", grade: "فاخر", suggestedPrice: 150, source: "imported" },
			{ nameAr: "Subway Tile سيراميك", nameEn: "Subway Tile", grade: "عادي", suggestedPrice: 70, source: "local" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 1130,
	},
];
