import type { CatalogEntry } from "../types";

// أعمال اللياسة (12 + 8 = ~20 ر.س/م² داخلي عادي)

export const PLASTER_CATALOG: CatalogEntry[] = [
	{
		itemKey: "finishing.plaster.interior",
		domain: "FINISHING",
		categoryKey: "plaster",
		subcategoryKey: "interior",
		nameAr: "لياسة داخلية",
		nameEn: "Interior Plaster",
		descriptionAr: "لياسة جدران الغرف والممرات الداخلية (3 طبقات)",
		descriptionEn: "Interior wall plaster (3 layers)",
		icon: "PaintBucket",
		color: "#F59E0B",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة اللياسة", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 12,
		defaultLaborUnitPrice: 8,
		commonMaterials: [
			{ nameAr: "أسمنت بورتلاند + رمل غسيل", nameEn: "Portland Cement + Washed Sand", grade: "عادي", suggestedPrice: 12, source: "local" },
			{ nameAr: "ماستر مونوكوت", nameEn: "Master Monocoat", brand: "Master Builders", grade: "فاخر", suggestedPrice: 22, source: "imported" },
			{ nameAr: "Knauf MP75", nameEn: "Knauf MP75 Gypsum Plaster", brand: "Knauf", grade: "فاخر", suggestedPrice: 25, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 110,
	},
	{
		itemKey: "finishing.plaster.exterior",
		domain: "FINISHING",
		categoryKey: "plaster",
		subcategoryKey: "exterior",
		nameAr: "لياسة خارجية",
		nameEn: "Exterior Plaster",
		descriptionAr: "لياسة الواجهات الخارجية المقاومة للعوامل الجوية",
		descriptionEn: "Weather-resistant exterior facade plaster",
		icon: "PaintBucket",
		color: "#D97706",
		unit: "m²",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة اللياسة الخارجية", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 18,
		defaultLaborUnitPrice: 12,
		commonMaterials: [
			{ nameAr: "أسمنت + رمل + إضافات مقاومة", nameEn: "Cement + Sand + Weather Additives", grade: "عادي", suggestedPrice: 18, source: "local" },
			{ nameAr: "Sika MonoTop", nameEn: "Sika MonoTop", brand: "Sika", grade: "فاخر", suggestedPrice: 30, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "external",
		displayOrder: 120,
	},
	{
		itemKey: "finishing.plaster.repair",
		domain: "FINISHING",
		categoryKey: "plaster",
		subcategoryKey: "repair",
		nameAr: "ترميم لياسة",
		nameEn: "Plaster Repair",
		descriptionAr: "إصلاح وترميم اللياسة المتشققة أو المتساقطة",
		descriptionEn: "Repair of cracked or damaged plaster",
		icon: "Wrench",
		color: "#A8A29E",
		unit: "m²",
		defaultWastagePercent: 15,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الترميم", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 15,
		defaultLaborUnitPrice: 18,
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 130,
	},
	{
		itemKey: "finishing.plaster.decorative",
		domain: "FINISHING",
		categoryKey: "plaster",
		subcategoryKey: "decorative",
		nameAr: "لياسة ديكور (ستوكو/منقّش)",
		nameEn: "Decorative Plaster (Stucco / Textured)",
		descriptionAr: "لياسة ذات تشطيب نهائي ديكوري بأنماط متنوعة",
		descriptionEn: "Plaster with decorative finish patterns",
		icon: "Sparkles",
		color: "#C026D3",
		unit: "m²",
		defaultWastagePercent: 15,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة اللياسة الديكورية", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 45,
		defaultLaborUnitPrice: 30,
		commonMaterials: [
			{ nameAr: "ستوكو إيطالي", nameEn: "Italian Stucco", grade: "فاخر", suggestedPrice: 70, source: "imported" },
			{ nameAr: "لياسة منقّشة محلية", nameEn: "Local Textured Plaster", grade: "عادي", suggestedPrice: 40, source: "local" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 140,
	},
];
