import type { CatalogEntry } from "../types";

// قوائم وكورنيش — تُحسب بالمتر الطولي

export const TRIM_CATALOG: CatalogEntry[] = [
	{
		itemKey: "finishing.trim.ceramic_skirting",
		domain: "FINISHING",
		categoryKey: "trim",
		subcategoryKey: "ceramic_skirting",
		nameAr: "وزرة سيراميك",
		nameEn: "Ceramic Skirting",
		descriptionAr: "وزرة سيراميك بارتفاع 8-10 سم على محيط الغرف",
		descriptionEn: "Ceramic skirting (8-10cm) along room perimeter",
		icon: "Minus",
		color: "#0891B2",
		unit: "m",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "length_only",
		requiredFields: {
			primary: { key: "length", label: "الطول", unit: "m", min: 0 },
		},
		defaultMaterialUnitPrice: 15,
		defaultLaborUnitPrice: 8,
		legacyDerivationType: "length_only",
		legacyScope: "per_floor",
		displayOrder: 1010,
	},
	{
		itemKey: "finishing.trim.wood_skirting",
		domain: "FINISHING",
		categoryKey: "trim",
		subcategoryKey: "wood_skirting",
		nameAr: "وزرة خشبية",
		nameEn: "Wood Skirting",
		descriptionAr: "وزرة خشبية MDF أو خشب صلب",
		descriptionEn: "Wood (MDF or solid) skirting",
		icon: "Minus",
		color: "#92400E",
		unit: "m",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "length_only",
		requiredFields: {
			primary: { key: "length", label: "الطول", unit: "m", min: 0 },
		},
		defaultMaterialUnitPrice: 22,
		defaultLaborUnitPrice: 10,
		legacyDerivationType: "length_only",
		legacyScope: "per_floor",
		displayOrder: 1020,
	},
	{
		itemKey: "finishing.trim.cornices",
		domain: "FINISHING",
		categoryKey: "trim",
		subcategoryKey: "cornices",
		nameAr: "كورنيش جبس",
		nameEn: "Gypsum Cornice",
		descriptionAr: "كورنيش جبس على محيط السقف",
		descriptionEn: "Gypsum ceiling cornice",
		icon: "MoreHorizontal",
		color: "#A855F7",
		unit: "m",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "length_only",
		requiredFields: {
			primary: { key: "length", label: "الطول", unit: "m", min: 0 },
		},
		defaultMaterialUnitPrice: 18,
		defaultLaborUnitPrice: 12,
		legacyDerivationType: "length_only",
		legacyScope: "per_floor",
		displayOrder: 1030,
	},
	{
		itemKey: "finishing.trim.molding",
		domain: "FINISHING",
		categoryKey: "trim",
		subcategoryKey: "molding",
		nameAr: "بروفايلات ديكورية",
		nameEn: "Decorative Moldings",
		descriptionAr: "بروفايلات ديكورية للجدران (Crown / Chair Rail)",
		descriptionEn: "Decorative wall moldings",
		icon: "Frame",
		color: "#C026D3",
		unit: "m",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "length_only",
		requiredFields: {
			primary: { key: "length", label: "الطول", unit: "m", min: 0 },
		},
		defaultMaterialUnitPrice: 30,
		defaultLaborUnitPrice: 18,
		legacyDerivationType: "length_only",
		legacyScope: "per_floor",
		displayOrder: 1040,
	},
];
