import type { CatalogEntry } from "../types";

// تكسيات الجدران (مطابخ، حمامات، جبس بورد، ورق جدران)

export const WALLS_CATALOG: CatalogEntry[] = [
	{
		itemKey: "finishing.walls.kitchen_ceramic",
		domain: "FINISHING",
		categoryKey: "walls",
		subcategoryKey: "kitchen_ceramic",
		nameAr: "سيراميك مطابخ",
		nameEn: "Kitchen Wall Ceramic",
		descriptionAr: "سيراميك جدران المطبخ (Splashback) فوق الكاونتر عادةً",
		descriptionEn: "Kitchen wall ceramic (splashback)",
		icon: "ChefHat",
		color: "#EA580C",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "length_x_height",
		requiredFields: {
			primary: { key: "length", label: "طول الجدار", unit: "m", min: 0 },
			secondary: { key: "height", label: "ارتفاع السيراميك", unit: "m", min: 0 },
		},
		defaultMaterialUnitPrice: 40,
		defaultLaborUnitPrice: 18,
		commonMaterials: [
			{ nameAr: "السعودي سيراميك جدار 30×60", nameEn: "Saudi Ceramic Wall 30x60", brand: "Saudi Ceramic", grade: "عادي", suggestedPrice: 40, source: "local" },
			{ nameAr: "RAK Wall Tiles 30×60", nameEn: "RAK Wall 30x60", brand: "RAK", grade: "فاخر", suggestedPrice: 60, source: "imported" },
		],
		legacyDerivationType: "kitchen_splashback",
		legacyScope: "per_floor",
		displayOrder: 510,
	},
	{
		itemKey: "finishing.walls.bathroom_ceramic",
		domain: "FINISHING",
		categoryKey: "walls",
		subcategoryKey: "bathroom_ceramic",
		nameAr: "سيراميك حمامات",
		nameEn: "Bathroom Wall Ceramic",
		descriptionAr: "سيراميك جدران الحمام كاملاً حتى السقف عادةً",
		descriptionEn: "Bathroom wall ceramic (full height)",
		icon: "Bath",
		color: "#0EA5E9",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "length_x_height",
		requiredFields: {
			primary: { key: "length", label: "محيط الجدران", unit: "m", min: 0 },
			secondary: { key: "height", label: "ارتفاع السيراميك", unit: "m", min: 0 },
		},
		defaultMaterialUnitPrice: 38,
		defaultLaborUnitPrice: 18,
		commonMaterials: [
			{ nameAr: "السعودي حمامات 25×40", nameEn: "Saudi Bath 25x40", brand: "Saudi Ceramic", grade: "عادي", suggestedPrice: 38, source: "local" },
			{ nameAr: "RAK Bath 30×60", nameEn: "RAK Bath 30x60", brand: "RAK", grade: "فاخر", suggestedPrice: 55, source: "imported" },
		],
		legacyDerivationType: "bathroom_walls",
		legacyScope: "per_floor",
		displayOrder: 520,
	},
	{
		itemKey: "finishing.walls.gypsum_board",
		domain: "FINISHING",
		categoryKey: "walls",
		subcategoryKey: "gypsum_board",
		nameAr: "جدار جبس بورد",
		nameEn: "Gypsum Board Partition",
		descriptionAr: "قواطع جبس بورد بإطار معدني وعازل صوتي",
		descriptionEn: "Gypsum board partition with metal frame + acoustic insulation",
		icon: "Square",
		color: "#94A3B8",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "length_x_height",
		requiredFields: {
			primary: { key: "length", label: "طول الجدار", unit: "m", min: 0 },
			secondary: { key: "height", label: "ارتفاع الجدار", unit: "m", min: 0 },
		},
		defaultMaterialUnitPrice: 65,
		defaultLaborUnitPrice: 30,
		commonMaterials: [
			{ nameAr: "Knauf لوح أبيض 12.5مم", nameEn: "Knauf Standard 12.5mm", brand: "Knauf", grade: "عادي", suggestedPrice: 18, source: "imported" },
			{ nameAr: "Knauf مقاوم رطوبة (أخضر)", nameEn: "Knauf Moisture Resistant", brand: "Knauf", grade: "فاخر", suggestedPrice: 28, source: "imported" },
			{ nameAr: "Knauf مقاوم حريق (أحمر)", nameEn: "Knauf Fire Rated", brand: "Knauf", grade: "فاخر", suggestedPrice: 32, source: "imported" },
		],
		legacyDerivationType: "length_x_height",
		legacyScope: "per_floor",
		displayOrder: 530,
	},
	{
		itemKey: "finishing.walls.wallpaper",
		domain: "FINISHING",
		categoryKey: "walls",
		subcategoryKey: "wallpaper",
		nameAr: "ورق جدران",
		nameEn: "Wallpaper",
		descriptionAr: "ورق جدران ديكوري بأنماط مختلفة",
		descriptionEn: "Decorative wallpaper",
		icon: "Image",
		color: "#DB2777",
		unit: "m²",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الجدران", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 55,
		defaultLaborUnitPrice: 20,
		commonMaterials: [
			{ nameAr: "ورق ألماني فينيل", nameEn: "German Vinyl Wallpaper", grade: "فاخر", suggestedPrice: 90, source: "imported" },
			{ nameAr: "ورق صيني عادي", nameEn: "Chinese Standard", grade: "اقتصادي", suggestedPrice: 35, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 540,
	},
	{
		itemKey: "finishing.walls.wood_panel",
		domain: "FINISHING",
		categoryKey: "walls",
		subcategoryKey: "wood_panel",
		nameAr: "ألواح خشبية للجدران",
		nameEn: "Wood Wall Panels",
		descriptionAr: "ألواح خشبية ديكورية للجدران الداخلية",
		descriptionEn: "Decorative wood panels for interior walls",
		icon: "TreePine",
		color: "#92400E",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الألواح", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 180,
		defaultLaborUnitPrice: 50,
		commonMaterials: [
			{ nameAr: "ألواح MDF مكسوة", nameEn: "Veneered MDF Panel", grade: "عادي", suggestedPrice: 150, source: "local" },
			{ nameAr: "ألواح بلوط طبيعي", nameEn: "Natural Oak Panel", grade: "فاخر", suggestedPrice: 320, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 550,
	},
	{
		itemKey: "finishing.walls.stone_cladding_interior",
		domain: "FINISHING",
		categoryKey: "walls",
		subcategoryKey: "stone_cladding_interior",
		nameAr: "تكسية حجر داخلية",
		nameEn: "Interior Stone Cladding",
		descriptionAr: "تكسية حجر طبيعي أو صناعي لجدار داخلي (حائط مميز)",
		descriptionEn: "Natural or artificial stone cladding (feature wall)",
		icon: "Mountain",
		color: "#78716C",
		unit: "m²",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة التكسية", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 140,
		defaultLaborUnitPrice: 50,
		commonMaterials: [
			{ nameAr: "حجر صناعي ستون", nameEn: "Artificial Stone", grade: "عادي", suggestedPrice: 120, source: "local" },
			{ nameAr: "حجر رياض طبيعي", nameEn: "Riyadh Natural Stone", grade: "عادي", suggestedPrice: 130, source: "local" },
			{ nameAr: "ترفيرتين تركي", nameEn: "Turkish Travertine", grade: "فاخر", suggestedPrice: 220, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "per_floor",
		displayOrder: 560,
	},
];
