import type { CatalogEntry } from "../types";

// النوافذ — تُحسب بالمساحة (m²)

export const WINDOWS_CATALOG: CatalogEntry[] = [
	{
		itemKey: "finishing.windows.aluminum",
		domain: "FINISHING",
		categoryKey: "windows",
		subcategoryKey: "aluminum",
		nameAr: "نوافذ ألمنيوم",
		nameEn: "Aluminum Windows",
		descriptionAr: "نوافذ ألمنيوم بزجاج عادي أو مزدوج",
		descriptionEn: "Aluminum windows with single or double glazing",
		icon: "RectangleHorizontal",
		color: "#94A3B8",
		unit: "m²",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة النوافذ", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 380,
		defaultLaborUnitPrice: 60,
		commonMaterials: [
			{ nameAr: "ألمنيوم تركي زجاج مزدوج", nameEn: "Turkish Aluminum Double-Glazed", grade: "فاخر", suggestedPrice: 480, source: "imported" },
			{ nameAr: "ألمنيوم محلي زجاج عادي", nameEn: "Local Aluminum Single-Glazed", grade: "عادي", suggestedPrice: 320, source: "local" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "external",
		displayOrder: 810,
	},
	{
		itemKey: "finishing.windows.upvc",
		domain: "FINISHING",
		categoryKey: "windows",
		subcategoryKey: "upvc",
		nameAr: "نوافذ UPVC",
		nameEn: "UPVC Windows",
		descriptionAr: "نوافذ UPVC عازلة للحرارة والصوت",
		descriptionEn: "UPVC windows with thermal and acoustic insulation",
		icon: "RectangleHorizontal",
		color: "#E5E7EB",
		unit: "m²",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة النوافذ", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 520,
		defaultLaborUnitPrice: 70,
		commonMaterials: [
			{ nameAr: "Rehau ألماني", nameEn: "Rehau Germany", brand: "Rehau", grade: "فاخر", suggestedPrice: 650, source: "imported" },
			{ nameAr: "Veka ألماني", nameEn: "Veka Germany", brand: "Veka", grade: "فاخر", suggestedPrice: 620, source: "imported" },
			{ nameAr: "UPVC تركي", nameEn: "Turkish UPVC", grade: "عادي", suggestedPrice: 450, source: "imported" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "external",
		displayOrder: 820,
	},
	{
		itemKey: "finishing.windows.steel_security",
		domain: "FINISHING",
		categoryKey: "windows",
		subcategoryKey: "steel_security",
		nameAr: "حماية حديد للنوافذ",
		nameEn: "Steel Window Bars / Security",
		descriptionAr: "شبك حديدي حماية للنوافذ",
		descriptionEn: "Steel security bars for windows",
		icon: "Shield",
		color: "#374151",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الحماية", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 180,
		defaultLaborUnitPrice: 50,
		legacyDerivationType: "direct_area",
		legacyScope: "external",
		displayOrder: 830,
	},
	{
		itemKey: "finishing.windows.shutters",
		domain: "FINISHING",
		categoryKey: "windows",
		subcategoryKey: "shutters",
		nameAr: "ستائر معدنية (Shutters)",
		nameEn: "Roller Shutters",
		descriptionAr: "ستائر معدنية متحركة للحماية والظل",
		descriptionEn: "Roller metal shutters for protection and shade",
		icon: "Blinds",
		color: "#475569",
		unit: "m²",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الستائر", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 320,
		defaultLaborUnitPrice: 60,
		legacyDerivationType: "direct_area",
		legacyScope: "external",
		displayOrder: 840,
	},
];
