import type { CatalogEntry } from "./types";

// أعمال خارجية (سور، بوابات، حدائق، مسبح)

export const EXTERIOR_CATALOG: CatalogEntry[] = [
	{
		itemKey: "exterior.boundary_wall",
		domain: "EXTERIOR",
		categoryKey: "exterior",
		subcategoryKey: "boundary",
		nameAr: "سور خارجي",
		nameEn: "Boundary Wall",
		descriptionAr: "سور خارجي بلوك مع لياسة وقاعدة (بالمتر الطولي)",
		descriptionEn: "Block boundary wall with plaster and footing (per meter)",
		icon: "RectangleVertical",
		color: "#78716C",
		unit: "م.ط",
		defaultWastagePercent: 8,
		defaultCalculationMethod: "length_only",
		requiredFields: {
			primary: { key: "length", label: "طول السور", unit: "م.ط", defaultSuggestion: "fromContext.fenceLength", min: 0 },
		},
		defaultMaterialUnitPrice: 280,
		defaultLaborUnitPrice: 90,
		legacyDerivationType: "length_only",
		legacyScope: "external",
		displayOrder: 110,
	},
	{
		itemKey: "exterior.main_gate",
		domain: "EXTERIOR",
		categoryKey: "exterior",
		subcategoryKey: "gates",
		nameAr: "بوابة رئيسية (سيارة)",
		nameEn: "Main Gate (Car)",
		descriptionAr: "بوابة رئيسية معدنية مزدوجة مع مفصلات وأكسسوار (موتور اختياري)",
		descriptionEn: "Main double metal gate with hinges and hardware (motor optional)",
		icon: "DoorOpen",
		color: "#475569",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 4500,
		defaultLaborUnitPrice: 600,
		commonMaterials: [
			{ nameAr: "بوابة معدن محلية", nameEn: "Local Metal Gate", grade: "عادي", suggestedPrice: 4200, source: "local" },
			{ nameAr: "بوابة معدن مع موتور", nameEn: "Metal Gate with Motor", grade: "فاخر", suggestedPrice: 8500, source: "local" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "external",
		displayOrder: 210,
	},
	{
		itemKey: "exterior.secondary_gate",
		domain: "EXTERIOR",
		categoryKey: "exterior",
		subcategoryKey: "gates",
		nameAr: "بوابة جانبية (مشاة)",
		nameEn: "Side Gate (Pedestrian)",
		descriptionAr: "بوابة جانبية مفردة للمشاة",
		descriptionEn: "Single pedestrian side gate",
		icon: "DoorOpen",
		color: "#64748B",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 1500,
		defaultLaborUnitPrice: 250,
		legacyDerivationType: "per_unit",
		legacyScope: "external",
		displayOrder: 220,
	},
	{
		itemKey: "exterior.driveway",
		domain: "EXTERIOR",
		categoryKey: "exterior",
		subcategoryKey: "driveway",
		nameAr: "ممر سيارات (ممر داخلي)",
		nameEn: "Driveway / Internal Path",
		descriptionAr: "ممر سيارات بلاط أو إنترلوك أو خرسانة مطبوعة",
		descriptionEn: "Driveway with tiles, interlock, or stamped concrete",
		icon: "Map",
		color: "#A8A29E",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الممر", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 110,
		defaultLaborUnitPrice: 35,
		commonMaterials: [
			{ nameAr: "إنترلوك محلي 6سم", nameEn: "Local Interlock 6cm", grade: "عادي", suggestedPrice: 95, source: "local" },
			{ nameAr: "بلاط حجر بازلت", nameEn: "Basalt Stone Tile", grade: "فاخر", suggestedPrice: 180, source: "imported" },
			{ nameAr: "خرسانة مطبوعة", nameEn: "Stamped Concrete", grade: "فاخر", suggestedPrice: 150, source: "local" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "external",
		displayOrder: 310,
	},
	{
		itemKey: "exterior.landscaping",
		domain: "EXTERIOR",
		categoryKey: "exterior",
		subcategoryKey: "landscaping",
		nameAr: "تنسيق حدائق",
		nameEn: "Landscaping",
		descriptionAr: "تنسيق حدائق (عشب صناعي/طبيعي + شجيرات + ري)",
		descriptionEn: "Landscaping (lawn + plants + irrigation)",
		icon: "Trees",
		color: "#16A34A",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة الحديقة", unit: "m²", defaultSuggestion: "fromContext.yardArea", min: 0 },
		},
		defaultMaterialUnitPrice: 90,
		defaultLaborUnitPrice: 50,
		commonMaterials: [
			{ nameAr: "عشب صناعي صيني", nameEn: "Chinese Artificial Grass", grade: "عادي", suggestedPrice: 60, source: "imported" },
			{ nameAr: "عشب طبيعي زراعة", nameEn: "Natural Grass + Soil", grade: "عادي", suggestedPrice: 85, source: "local" },
			{ nameAr: "تنسيق فاخر شامل ري آلي", nameEn: "Premium with Auto-Irrigation", grade: "فاخر", suggestedPrice: 220, source: "local" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "external",
		displayOrder: 410,
	},
	{
		itemKey: "exterior.swimming_pool",
		domain: "EXTERIOR",
		categoryKey: "exterior",
		subcategoryKey: "pool",
		nameAr: "مسبح",
		nameEn: "Swimming Pool",
		descriptionAr: "مسبح خرساني كامل (هيكل + عزل + سيراميك + فلتر)",
		descriptionEn: "Concrete pool (structure + insulation + tiles + filter)",
		icon: "Waves",
		color: "#0EA5E9",
		unit: "m²",
		defaultWastagePercent: 10,
		defaultCalculationMethod: "direct_area",
		requiredFields: {
			primary: { key: "area", label: "مساحة المسبح", unit: "m²", min: 0 },
		},
		defaultMaterialUnitPrice: 1800,
		defaultLaborUnitPrice: 700,
		commonMaterials: [
			{ nameAr: "مسبح خرساني عادي", nameEn: "Standard Concrete Pool", grade: "عادي", suggestedPrice: 1700, source: "local" },
			{ nameAr: "مسبح فاخر مع جاكوزي", nameEn: "Premium with Jacuzzi", grade: "فاخر", suggestedPrice: 3500, source: "local" },
		],
		legacyDerivationType: "direct_area",
		legacyScope: "external",
		displayOrder: 510,
	},
];
