import type { PresetEntry } from "./types";

// باقات جاهزة (Presets) — تُطبَّق على دراسة جديدة لتعبئة بنود متعددة دفعة واحدة

export const PRESETS: PresetEntry[] = [
	{
		key: "villa_standard",
		nameAr: "فيلا سكنية نموذجية",
		nameEn: "Standard Villa",
		descriptionAr: "تشطيب قياسي + كهرباء وسباكة وتكييف",
		icon: "Home",
		itemKeys: [
			"finishing.plaster.interior",
			"finishing.plaster.exterior",
			"finishing.paint.interior",
			"finishing.paint.exterior",
			"finishing.flooring.ceramic",
			"finishing.walls.kitchen_ceramic",
			"finishing.walls.bathroom_ceramic",
			"finishing.ceiling.gypsum_board",
			"finishing.doors.interior_wood",
			"finishing.doors.exterior_steel",
			"finishing.windows.aluminum",
			"finishing.insulation.thermal_roof",
			"finishing.insulation.waterproof_roof",
			"finishing.kitchen.cabinets",
			"mep.electrical.outlet_normal",
			"mep.electrical.lighting_ceiling",
			"mep.electrical.switch_single",
			"mep.electrical.main_panel",
			"mep.plumbing.cold_water_point",
			"mep.plumbing.drainage_bathroom",
			"mep.plumbing.water_heater_electric",
			"mep.plumbing.water_tank",
			"mep.hvac.split_unit",
		],
	},
	{
		key: "apartment_standard",
		nameAr: "شقة سكنية",
		nameEn: "Standard Apartment",
		descriptionAr: "تشطيب شقة كامل بدون أعمال خارجية",
		icon: "Building",
		itemKeys: [
			"finishing.plaster.interior",
			"finishing.paint.interior",
			"finishing.flooring.ceramic",
			"finishing.walls.kitchen_ceramic",
			"finishing.walls.bathroom_ceramic",
			"finishing.ceiling.gypsum_board",
			"finishing.doors.interior_wood",
			"finishing.kitchen.cabinets",
			"mep.electrical.outlet_normal",
			"mep.electrical.lighting_ceiling",
			"mep.electrical.switch_single",
			"mep.plumbing.cold_water_point",
			"mep.plumbing.drainage_bathroom",
			"mep.plumbing.water_heater_electric",
			"mep.hvac.split_unit",
		],
	},
	{
		key: "warehouse_minimal",
		nameAr: "مستودع تجاري",
		nameEn: "Commercial Warehouse",
		descriptionAr: "تشطيب مستودع بسيط مع كهرباء صناعية وإطفاء",
		icon: "Warehouse",
		itemKeys: [
			"finishing.plaster.interior",
			"finishing.paint.interior",
			"finishing.flooring.epoxy",
			"finishing.doors.exterior_steel",
			"mep.electrical.outlet_industrial",
			"mep.electrical.lighting_ceiling",
			"mep.electrical.main_panel",
			"mep.firefighting.sprinkler",
			"mep.firefighting.smoke_detector",
		],
	},
	{
		key: "shop_retail",
		nameAr: "محل تجاري",
		nameEn: "Retail Shop",
		descriptionAr: "محل تجاري بإنارة وتكييف وواجهة زجاجية",
		icon: "Store",
		itemKeys: [
			"finishing.plaster.interior",
			"finishing.paint.interior",
			"finishing.flooring.porcelain",
			"finishing.ceiling.gypsum_board",
			"finishing.doors.glass",
			"mep.electrical.outlet_normal",
			"mep.electrical.lighting_ceiling",
			"mep.electrical.switch_single",
			"mep.hvac.split_unit",
			"mep.firefighting.smoke_detector",
			"mep.firefighting.extinguisher",
			"mep.low_current.cctv_camera",
		],
	},
	{
		key: "office_standard",
		nameAr: "مكتب إداري",
		nameEn: "Standard Office",
		descriptionAr: "مكتب إداري بشبكة بيانات وتكييف مركزي",
		icon: "Briefcase",
		itemKeys: [
			"finishing.plaster.interior",
			"finishing.paint.interior",
			"finishing.flooring.vinyl",
			"finishing.ceiling.acoustic",
			"finishing.doors.interior_wood",
			"mep.electrical.outlet_normal",
			"mep.electrical.lighting_ceiling",
			"mep.electrical.switch_single",
			"mep.hvac.central_unit",
			"mep.low_current.internet_point",
			"mep.low_current.cctv_camera",
			"mep.firefighting.smoke_detector",
		],
	},
	{
		key: "paint_only",
		nameAr: "دهان فقط",
		nameEn: "Paint Only",
		descriptionAr: "تسعير سريع لأعمال دهان داخلي",
		icon: "Paintbrush",
		itemKeys: ["finishing.paint.interior"],
	},
	{
		key: "tiles_only",
		nameAr: "بلاط فقط",
		nameEn: "Tiles Only",
		descriptionAr: "تسعير سريع لأعمال بلاط أرضيات",
		icon: "LayoutGrid",
		itemKeys: ["finishing.flooring.ceramic"],
	},
	{
		key: "mep_only",
		nameAr: "كهروميكانيكا فقط",
		nameEn: "MEP Only",
		descriptionAr: "تسعير الأعمال الكهروميكانيكية الأساسية",
		icon: "Zap",
		itemKeys: [
			"mep.electrical.outlet_normal",
			"mep.electrical.lighting_ceiling",
			"mep.electrical.main_panel",
			"mep.plumbing.cold_water_point",
			"mep.plumbing.drainage_bathroom",
			"mep.hvac.split_unit",
		],
	},
];
