import type { CatalogEntry } from "./types";

// عناصر خاصة (مصعد، خزان، بيارة، طاقة شمسية)

export const SPECIAL_CATALOG: CatalogEntry[] = [
	{
		itemKey: "special.elevator",
		domain: "SPECIAL",
		categoryKey: "elevator",
		subcategoryKey: "passenger",
		nameAr: "مصعد",
		nameEn: "Elevator",
		descriptionAr: "مصعد ركاب 4-6 أشخاص (بئر + أبواب + أكسسوار)",
		descriptionEn: "Passenger elevator 4-6 persons (shaft + doors + cabin)",
		icon: "ArrowUpDown",
		color: "#475569",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 85000,
		defaultLaborUnitPrice: 12000,
		commonMaterials: [
			{ nameAr: "Otis 6 ركاب", nameEn: "Otis 6 Persons", brand: "Otis", grade: "فاخر", suggestedPrice: 110000, source: "imported" },
			{ nameAr: "Schindler 4 ركاب", nameEn: "Schindler 4 Persons", brand: "Schindler", grade: "فاخر", suggestedPrice: 95000, source: "imported" },
			{ nameAr: "Kone 6 ركاب", nameEn: "Kone 6 Persons", brand: "Kone", grade: "فاخر", suggestedPrice: 105000, source: "imported" },
			{ nameAr: "مصعد صيني 4 ركاب", nameEn: "Chinese 4 Persons", grade: "عادي", suggestedPrice: 65000, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "whole_building",
		displayOrder: 110,
	},
	{
		itemKey: "special.water_storage_tank",
		domain: "SPECIAL",
		categoryKey: "tank",
		subcategoryKey: "water_storage",
		nameAr: "خزان مياه أرضي مدفون",
		nameEn: "Buried Water Storage Tank",
		descriptionAr: "خزان مياه أرضي خرساني مع عزل (سعة بالمتر المكعب)",
		descriptionEn: "Buried concrete water tank with insulation (per m³)",
		icon: "Database",
		color: "#0284C7",
		unit: "m³",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "volume", label: "السعة", unit: "m³", min: 0 },
		},
		defaultMaterialUnitPrice: 850,
		defaultLaborUnitPrice: 250,
		legacyDerivationType: "per_unit",
		legacyScope: "whole_building",
		displayOrder: 210,
	},
	{
		itemKey: "special.septic_tank",
		domain: "SPECIAL",
		categoryKey: "tank",
		subcategoryKey: "septic",
		nameAr: "بيارة (خزان صرف)",
		nameEn: "Septic Tank",
		descriptionAr: "بيارة صرف صحي خرسانية (سعة بالمتر المكعب)",
		descriptionEn: "Concrete septic tank (per m³)",
		icon: "Box",
		color: "#92400E",
		unit: "m³",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "volume", label: "السعة", unit: "m³", min: 0 },
		},
		defaultMaterialUnitPrice: 950,
		defaultLaborUnitPrice: 280,
		legacyDerivationType: "per_unit",
		legacyScope: "whole_building",
		displayOrder: 220,
	},
	{
		itemKey: "special.solar_panels",
		domain: "SPECIAL",
		categoryKey: "solar",
		subcategoryKey: "pv",
		nameAr: "ألواح طاقة شمسية",
		nameEn: "Solar PV Panels",
		descriptionAr: "نظام ألواح شمسية كامل (لوحة + إنفرتر + تركيب)",
		descriptionEn: "Complete solar PV system (panel + inverter + installation)",
		icon: "Sun",
		color: "#EAB308",
		unit: "kW",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "kW", label: "القدرة (kW)", unit: "kW", min: 0 },
		},
		defaultMaterialUnitPrice: 3500,
		defaultLaborUnitPrice: 700,
		commonMaterials: [
			{ nameAr: "Canadian Solar 550W", nameEn: "Canadian Solar 550W", brand: "Canadian Solar", grade: "فاخر", suggestedPrice: 3800, source: "imported" },
			{ nameAr: "JinkoSolar Tiger Pro", nameEn: "JinkoSolar Tiger Pro", brand: "Jinko", grade: "فاخر", suggestedPrice: 4000, source: "imported" },
			{ nameAr: "Trina Solar Vertex", nameEn: "Trina Solar Vertex", brand: "Trina", grade: "فاخر", suggestedPrice: 3900, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "whole_building",
		displayOrder: 310,
	},
];
