import type { CatalogEntry } from "../types";

// الأعمال الكهربائية

export const ELECTRICAL_CATALOG: CatalogEntry[] = [
	{
		itemKey: "mep.electrical.outlet_normal",
		domain: "MEP",
		categoryKey: "electrical",
		subcategoryKey: "outlets",
		nameAr: "مقبس كهرباء عادي 220V",
		nameEn: "Normal Power Outlet 220V",
		descriptionAr: "مقبس كهرباء أحادي 220 فولت كامل (سلك + علبة + غطاء)",
		descriptionEn: "Single-phase 220V outlet (cable + box + cover plate)",
		icon: "Plug",
		color: "#F59E0B",
		unit: "نقطة",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "عدد المقابس", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 15,
		defaultLaborUnitPrice: 10,
		commonMaterials: [
			{ nameAr: "Schneider Asfora", nameEn: "Schneider Asfora", brand: "Schneider", grade: "عادي", suggestedPrice: 18, source: "imported" },
			{ nameAr: "Legrand Mosaic", nameEn: "Legrand Mosaic", brand: "Legrand", grade: "فاخر", suggestedPrice: 35, source: "imported" },
			{ nameAr: "ABB Niessen", nameEn: "ABB Niessen", brand: "ABB", grade: "عادي", suggestedPrice: 22, source: "imported" },
			{ nameAr: "Hager Berker", nameEn: "Hager Berker", brand: "Hager", grade: "فاخر", suggestedPrice: 30, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 110,
	},
	{
		itemKey: "mep.electrical.outlet_3phase",
		domain: "MEP",
		categoryKey: "electrical",
		subcategoryKey: "outlets",
		nameAr: "مقبس 3 فاز",
		nameEn: "3-Phase Outlet",
		descriptionAr: "مقبس 3 فاز للأجهزة الثقيلة (تكييف، طباخ)",
		descriptionEn: "3-phase outlet for heavy appliances",
		icon: "Plug2",
		color: "#D97706",
		unit: "نقطة",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 65,
		defaultLaborUnitPrice: 35,
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 120,
	},
	{
		itemKey: "mep.electrical.outlet_industrial",
		domain: "MEP",
		categoryKey: "electrical",
		subcategoryKey: "outlets",
		nameAr: "مقبس صناعي IP65",
		nameEn: "Industrial Outlet IP65",
		descriptionAr: "مقبس صناعي مضاد للماء والغبار",
		descriptionEn: "Industrial waterproof outlet IP65",
		icon: "Plug2",
		color: "#0F172A",
		unit: "نقطة",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 110,
		defaultLaborUnitPrice: 50,
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 130,
	},
	{
		itemKey: "mep.electrical.lighting_ceiling",
		domain: "MEP",
		categoryKey: "electrical",
		subcategoryKey: "lighting",
		nameAr: "نقطة إنارة سقف",
		nameEn: "Ceiling Lighting Point",
		descriptionAr: "نقطة إنارة سقف كاملة (سلك + علبة + مفتاح)",
		descriptionEn: "Complete ceiling lighting point (cable + box + switch)",
		icon: "Lightbulb",
		color: "#FCD34D",
		unit: "نقطة",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 18,
		defaultLaborUnitPrice: 12,
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 210,
	},
	{
		itemKey: "mep.electrical.lighting_wall",
		domain: "MEP",
		categoryKey: "electrical",
		subcategoryKey: "lighting",
		nameAr: "نقطة إنارة جدار (Wall Sconce)",
		nameEn: "Wall Lighting Point",
		descriptionAr: "نقطة إنارة جدار",
		descriptionEn: "Wall-mounted lighting point",
		icon: "Lamp",
		color: "#F59E0B",
		unit: "نقطة",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 16,
		defaultLaborUnitPrice: 12,
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 220,
	},
	{
		itemKey: "mep.electrical.lighting_outdoor",
		domain: "MEP",
		categoryKey: "electrical",
		subcategoryKey: "lighting",
		nameAr: "نقطة إنارة خارجية",
		nameEn: "Outdoor Lighting Point",
		descriptionAr: "نقطة إنارة خارجية مع كشاف LED مقاوم IP65",
		descriptionEn: "Outdoor lighting with weatherproof LED",
		icon: "Sun",
		color: "#0EA5E9",
		unit: "نقطة",
		defaultWastagePercent: 8,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 65,
		defaultLaborUnitPrice: 25,
		legacyDerivationType: "per_unit",
		legacyScope: "external",
		displayOrder: 230,
	},
	{
		itemKey: "mep.electrical.switch_single",
		domain: "MEP",
		categoryKey: "electrical",
		subcategoryKey: "switches",
		nameAr: "مفتاح إنارة مفرد",
		nameEn: "Single Light Switch",
		descriptionAr: "مفتاح إنارة 1-Way",
		descriptionEn: "Single 1-way light switch",
		icon: "ToggleLeft",
		color: "#94A3B8",
		unit: "نقطة",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 12,
		defaultLaborUnitPrice: 8,
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 310,
	},
	{
		itemKey: "mep.electrical.switch_double",
		domain: "MEP",
		categoryKey: "electrical",
		subcategoryKey: "switches",
		nameAr: "مفتاح إنارة مزدوج/2-Way",
		nameEn: "Double / 2-Way Switch",
		descriptionAr: "مفتاح إنارة مزدوج أو 2-Way (سلالم)",
		descriptionEn: "Double or 2-way switch (for stairs)",
		icon: "ToggleRight",
		color: "#64748B",
		unit: "نقطة",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 18,
		defaultLaborUnitPrice: 10,
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 320,
	},
	{
		itemKey: "mep.electrical.main_panel",
		domain: "MEP",
		categoryKey: "electrical",
		subcategoryKey: "panels",
		nameAr: "لوحة كهرباء رئيسية",
		nameEn: "Main Distribution Panel",
		descriptionAr: "لوحة كهرباء رئيسية مع قواطع رئيسية وفرعية",
		descriptionEn: "Main distribution board with breakers",
		icon: "LayoutGrid",
		color: "#7C3AED",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 1800,
		defaultLaborUnitPrice: 350,
		commonMaterials: [
			{ nameAr: "Schneider Acti9", nameEn: "Schneider Acti9", brand: "Schneider", grade: "عادي", suggestedPrice: 1800, source: "imported" },
			{ nameAr: "ABB SMissLine", nameEn: "ABB SMissLine", brand: "ABB", grade: "فاخر", suggestedPrice: 2400, source: "imported" },
			{ nameAr: "Hager Vector", nameEn: "Hager Vector", brand: "Hager", grade: "عادي", suggestedPrice: 1700, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "whole_building",
		displayOrder: 410,
	},
	{
		itemKey: "mep.electrical.sub_panel",
		domain: "MEP",
		categoryKey: "electrical",
		subcategoryKey: "panels",
		nameAr: "لوحة كهرباء فرعية",
		nameEn: "Sub-Panel",
		descriptionAr: "لوحة فرعية بدور أو بقسم كبير",
		descriptionEn: "Sub-panel per floor or zone",
		icon: "Layout",
		color: "#A78BFA",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 850,
		defaultLaborUnitPrice: 150,
		legacyDerivationType: "per_unit",
		legacyScope: "per_floor",
		displayOrder: 420,
	},
	{
		itemKey: "mep.electrical.cable_run",
		domain: "MEP",
		categoryKey: "electrical",
		subcategoryKey: "cables",
		nameAr: "كابل / مواسير شبكة كهرباء",
		nameEn: "Cable Run / Conduits",
		descriptionAr: "تمديد كابل بالمتر الطولي مع المواسير",
		descriptionEn: "Cable installation per meter with conduits",
		icon: "Cable",
		color: "#374151",
		unit: "م.ط",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "length_only",
		requiredFields: {
			primary: { key: "length", label: "الطول", unit: "م.ط", min: 0 },
		},
		defaultMaterialUnitPrice: 18,
		defaultLaborUnitPrice: 8,
		legacyDerivationType: "length_only",
		legacyScope: "whole_building",
		displayOrder: 510,
	},
	{
		itemKey: "mep.electrical.grounding_system",
		domain: "MEP",
		categoryKey: "electrical",
		subcategoryKey: "earthing",
		nameAr: "نظام تأريض",
		nameEn: "Grounding System",
		descriptionAr: "نظام تأريض كامل (قضيب نحاسي + توصيلات)",
		descriptionEn: "Complete grounding system (copper rod + connections)",
		icon: "Anchor",
		color: "#16A34A",
		unit: "نظام",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "lump_sum",
		requiredFields: {
			primary: { key: "count", label: "عدد الأنظمة", unit: "نظام", min: 0 },
		},
		defaultMaterialUnitPrice: 1500,
		defaultLaborUnitPrice: 500,
		legacyDerivationType: "lump_sum",
		legacyScope: "whole_building",
		displayOrder: 610,
	},
];
