import type { CatalogEntry } from "../types";

// أنظمة إطفاء الحريق

export const FIREFIGHTING_CATALOG: CatalogEntry[] = [
	{
		itemKey: "mep.firefighting.sprinkler",
		domain: "MEP",
		categoryKey: "firefighting",
		subcategoryKey: "sprinkler",
		nameAr: "رشاش إطفاء سقف",
		nameEn: "Ceiling Sprinkler Head",
		descriptionAr: "رشاش إطفاء سقف ضمن نظام إطفاء (تركيب + موسورة)",
		descriptionEn: "Ceiling sprinkler head with pipe",
		icon: "Droplets",
		color: "#DC2626",
		unit: "نقطة",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 95,
		defaultLaborUnitPrice: 35,
		commonMaterials: [
			{ nameAr: "Tyco Fire", nameEn: "Tyco Fire", brand: "Tyco", grade: "فاخر", suggestedPrice: 110, source: "imported" },
			{ nameAr: "Viking Sprinkler", nameEn: "Viking Sprinkler", brand: "Viking", grade: "فاخر", suggestedPrice: 105, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "per_floor",
		displayOrder: 110,
	},
	{
		itemKey: "mep.firefighting.smoke_detector",
		domain: "MEP",
		categoryKey: "firefighting",
		subcategoryKey: "detection",
		nameAr: "كاشف دخان",
		nameEn: "Smoke Detector",
		descriptionAr: "كاشف دخان فوتو-إلكتروني سقفي",
		descriptionEn: "Photoelectric ceiling smoke detector",
		icon: "AlertTriangle",
		color: "#EA580C",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 130,
		defaultLaborUnitPrice: 40,
		commonMaterials: [
			{ nameAr: "Honeywell Smoke", nameEn: "Honeywell Smoke", brand: "Honeywell", grade: "فاخر", suggestedPrice: 160, source: "imported" },
			{ nameAr: "Notifier System", nameEn: "Notifier", brand: "Notifier", grade: "فاخر", suggestedPrice: 180, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "per_floor",
		displayOrder: 210,
	},
	{
		itemKey: "mep.firefighting.heat_detector",
		domain: "MEP",
		categoryKey: "firefighting",
		subcategoryKey: "detection",
		nameAr: "كاشف حرارة",
		nameEn: "Heat Detector",
		descriptionAr: "كاشف حرارة للمطابخ والكراجات",
		descriptionEn: "Heat detector for kitchens and garages",
		icon: "Thermometer",
		color: "#DC2626",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 110,
		defaultLaborUnitPrice: 35,
		legacyDerivationType: "per_unit",
		legacyScope: "per_floor",
		displayOrder: 220,
	},
	{
		itemKey: "mep.firefighting.extinguisher",
		domain: "MEP",
		categoryKey: "firefighting",
		subcategoryKey: "manual",
		nameAr: "طفاية حريق يدوية",
		nameEn: "Manual Fire Extinguisher",
		descriptionAr: "طفاية حريق يدوية 6 كجم بودرة جافة",
		descriptionEn: "Manual fire extinguisher 6kg dry powder",
		icon: "Flame",
		color: "#B91C1C",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 180,
		defaultLaborUnitPrice: 30,
		legacyDerivationType: "per_unit",
		legacyScope: "per_floor",
		displayOrder: 310,
	},
	{
		itemKey: "mep.firefighting.fire_panel",
		domain: "MEP",
		categoryKey: "firefighting",
		subcategoryKey: "control",
		nameAr: "لوحة إنذار حريق",
		nameEn: "Fire Alarm Control Panel",
		descriptionAr: "لوحة إنذار حريق رئيسية مع بطارية احتياط",
		descriptionEn: "Main fire alarm panel with battery backup",
		icon: "AlertOctagon",
		color: "#7F1D1D",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 4500,
		defaultLaborUnitPrice: 800,
		legacyDerivationType: "per_unit",
		legacyScope: "whole_building",
		displayOrder: 410,
	},
];
