import type { CatalogEntry } from "../types";

// التكييف والتهوية

export const HVAC_CATALOG: CatalogEntry[] = [
	{
		itemKey: "mep.hvac.split_unit",
		domain: "MEP",
		categoryKey: "hvac",
		subcategoryKey: "split_units",
		nameAr: "وحدة تكييف سبليت 1.5 طن",
		nameEn: "Split AC Unit 1.5 Ton",
		descriptionAr: "وحدة سبليت داخلية + خارجية 1.5 طن مع التركيب",
		descriptionEn: "Split AC indoor + outdoor 1.5 ton with installation",
		icon: "Wind",
		color: "#0EA5E9",
		unit: "وحدة",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "عدد الوحدات", unit: "وحدة", min: 0 },
		},
		defaultMaterialUnitPrice: 1800,
		defaultLaborUnitPrice: 350,
		commonMaterials: [
			{ nameAr: "LG كوري 1.5 طن انفرتر", nameEn: "LG Korea 1.5T Inverter", brand: "LG", grade: "فاخر", suggestedPrice: 2200, source: "imported" },
			{ nameAr: "Samsung 1.5 طن", nameEn: "Samsung 1.5T", brand: "Samsung", grade: "فاخر", suggestedPrice: 2100, source: "imported" },
			{ nameAr: "Daikin Inverter 1.5T", nameEn: "Daikin Inverter 1.5T", brand: "Daikin", grade: "فاخر", suggestedPrice: 2600, source: "imported" },
			{ nameAr: "Carrier محلي 1.5T", nameEn: "Carrier KSA 1.5T", brand: "Carrier", grade: "عادي", suggestedPrice: 1900, source: "local" },
			{ nameAr: "York 1.5T", nameEn: "York 1.5T", brand: "York", grade: "عادي", suggestedPrice: 1850, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 110,
	},
	{
		itemKey: "mep.hvac.window_unit",
		domain: "MEP",
		categoryKey: "hvac",
		subcategoryKey: "window_units",
		nameAr: "تكييف شباك",
		nameEn: "Window AC Unit",
		descriptionAr: "تكييف شباك 1.5-2 طن",
		descriptionEn: "Window AC 1.5-2 ton",
		icon: "Square",
		color: "#06B6D4",
		unit: "وحدة",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "وحدة", min: 0 },
		},
		defaultMaterialUnitPrice: 1100,
		defaultLaborUnitPrice: 150,
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 120,
	},
	{
		itemKey: "mep.hvac.central_unit",
		domain: "MEP",
		categoryKey: "hvac",
		subcategoryKey: "central_units",
		nameAr: "تكييف مركزي / VRF",
		nameEn: "Central / VRF AC",
		descriptionAr: "نظام تكييف مركزي/VRF (تكلفة لكل طن تبريد)",
		descriptionEn: "Central / VRF AC system (cost per cooling ton)",
		icon: "Building",
		color: "#0E7490",
		unit: "طن",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "حمل التبريد (طن)", unit: "طن", min: 0 },
		},
		defaultMaterialUnitPrice: 4500,
		defaultLaborUnitPrice: 800,
		commonMaterials: [
			{ nameAr: "Daikin VRV", nameEn: "Daikin VRV", brand: "Daikin", grade: "فاخر", suggestedPrice: 5500, source: "imported" },
			{ nameAr: "LG Multi V", nameEn: "LG Multi V", brand: "LG", grade: "فاخر", suggestedPrice: 5000, source: "imported" },
			{ nameAr: "Carrier Aquazone", nameEn: "Carrier Aquazone", brand: "Carrier", grade: "عادي", suggestedPrice: 4200, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "whole_building",
		displayOrder: 130,
	},
	{
		itemKey: "mep.hvac.duct_run",
		domain: "MEP",
		categoryKey: "hvac",
		subcategoryKey: "ducts",
		nameAr: "مجاري هواء (Ducts)",
		nameEn: "HVAC Ducts",
		descriptionAr: "مجاري هواء صفائح أو فلكس بالمتر الطولي",
		descriptionEn: "Sheet metal or flex ducts per meter",
		icon: "Cylinder",
		color: "#94A3B8",
		unit: "م.ط",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "length_only",
		requiredFields: {
			primary: { key: "length", label: "الطول", unit: "م.ط", min: 0 },
		},
		defaultMaterialUnitPrice: 65,
		defaultLaborUnitPrice: 25,
		legacyDerivationType: "length_only",
		legacyScope: "whole_building",
		displayOrder: 210,
	},
	{
		itemKey: "mep.hvac.exhaust_fan",
		domain: "MEP",
		categoryKey: "hvac",
		subcategoryKey: "ventilation",
		nameAr: "مروحة شفط (حمام/مطبخ)",
		nameEn: "Exhaust Fan (Bath / Kitchen)",
		descriptionAr: "مروحة شفط هواء للحمام أو المطبخ",
		descriptionEn: "Exhaust fan for bathroom or kitchen",
		icon: "Fan",
		color: "#475569",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 180,
		defaultLaborUnitPrice: 50,
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 310,
	},
	{
		itemKey: "mep.hvac.ventilation_grille",
		domain: "MEP",
		categoryKey: "hvac",
		subcategoryKey: "ventilation",
		nameAr: "غرفة/فتحة تهوية (Grille)",
		nameEn: "Ventilation Grille",
		descriptionAr: "غرفة تهوية ألمنيوم للسقف أو الجدار",
		descriptionEn: "Aluminum ceiling/wall ventilation grille",
		icon: "Grid3x3",
		color: "#64748B",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 95,
		defaultLaborUnitPrice: 30,
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 320,
	},
];
