import type { CatalogEntry } from "../types";

// التيار الخفيف (CCTV / Intercom / Internet / TV)

export const LOW_CURRENT_CATALOG: CatalogEntry[] = [
	{
		itemKey: "mep.low_current.cctv_camera",
		domain: "MEP",
		categoryKey: "low_current",
		subcategoryKey: "cctv",
		nameAr: "كاميرا مراقبة CCTV",
		nameEn: "CCTV Camera",
		descriptionAr: "كاميرا مراقبة IP أو AHD مع التركيب والكابل",
		descriptionEn: "IP or AHD CCTV camera with installation",
		icon: "Camera",
		color: "#1E293B",
		unit: "عدد",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 380,
		defaultLaborUnitPrice: 100,
		commonMaterials: [
			{ nameAr: "Hikvision IP 4MP", nameEn: "Hikvision IP 4MP", brand: "Hikvision", grade: "عادي", suggestedPrice: 350, source: "imported" },
			{ nameAr: "Dahua IP 4MP", nameEn: "Dahua IP 4MP", brand: "Dahua", grade: "عادي", suggestedPrice: 340, source: "imported" },
			{ nameAr: "Axis IP HD", nameEn: "Axis IP HD", brand: "Axis", grade: "فاخر", suggestedPrice: 1200, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "whole_building",
		displayOrder: 110,
	},
	{
		itemKey: "mep.low_current.intercom",
		domain: "MEP",
		categoryKey: "low_current",
		subcategoryKey: "intercom",
		nameAr: "نظام إنترفون",
		nameEn: "Intercom System",
		descriptionAr: "نقطة إنترفون داخلية أو خارجية",
		descriptionEn: "Indoor or outdoor intercom point",
		icon: "Phone",
		color: "#7C3AED",
		unit: "نقطة",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 280,
		defaultLaborUnitPrice: 80,
		commonMaterials: [
			{ nameAr: "Aiphone IX-Series", nameEn: "Aiphone IX-Series", brand: "Aiphone", grade: "فاخر", suggestedPrice: 480, source: "imported" },
			{ nameAr: "Commax تايواني", nameEn: "Commax Taiwan", brand: "Commax", grade: "عادي", suggestedPrice: 220, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "whole_building",
		displayOrder: 210,
	},
	{
		itemKey: "mep.low_current.internet_point",
		domain: "MEP",
		categoryKey: "low_current",
		subcategoryKey: "data",
		nameAr: "نقطة إنترنت/شبكة (Cat6)",
		nameEn: "Network Point (Cat6)",
		descriptionAr: "نقطة شبكة Cat6 مع كابل وعلبة وغطاء",
		descriptionEn: "Cat6 network point with cable, box, faceplate",
		icon: "Wifi",
		color: "#0EA5E9",
		unit: "نقطة",
		defaultWastagePercent: 8,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 55,
		defaultLaborUnitPrice: 25,
		commonMaterials: [
			{ nameAr: "Schneider Cat6", nameEn: "Schneider Cat6", brand: "Schneider", grade: "عادي", suggestedPrice: 50, source: "imported" },
			{ nameAr: "Legrand Cat6", nameEn: "Legrand Cat6", brand: "Legrand", grade: "فاخر", suggestedPrice: 75, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 310,
	},
	{
		itemKey: "mep.low_current.tv_outlet",
		domain: "MEP",
		categoryKey: "low_current",
		subcategoryKey: "tv",
		nameAr: "نقطة تلفاز (CATV/Sat)",
		nameEn: "TV Outlet (CATV / Satellite)",
		descriptionAr: "نقطة تلفاز كابل أو ستلايت",
		descriptionEn: "TV outlet (cable or satellite)",
		icon: "Tv",
		color: "#1E40AF",
		unit: "نقطة",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 35,
		defaultLaborUnitPrice: 18,
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 410,
	},
	{
		itemKey: "mep.low_current.access_control",
		domain: "MEP",
		categoryKey: "low_current",
		subcategoryKey: "access_control",
		nameAr: "نقطة تحكم بالدخول (بطاقة/بصمة)",
		nameEn: "Access Control Point (Card / Biometric)",
		descriptionAr: "نقطة تحكم بالدخول للأبواب",
		descriptionEn: "Door access control point",
		icon: "Fingerprint",
		color: "#16A34A",
		unit: "نقطة",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 950,
		defaultLaborUnitPrice: 200,
		commonMaterials: [
			{ nameAr: "ZKTeco بصمة", nameEn: "ZKTeco Biometric", brand: "ZKTeco", grade: "عادي", suggestedPrice: 850, source: "imported" },
			{ nameAr: "HID Card Reader", nameEn: "HID Card Reader", brand: "HID", grade: "فاخر", suggestedPrice: 1500, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "whole_building",
		displayOrder: 510,
	},
];
