import type { CatalogEntry } from "../types";

// الأعمال الصحية / السباكة

export const PLUMBING_CATALOG: CatalogEntry[] = [
	{
		itemKey: "mep.plumbing.cold_water_point",
		domain: "MEP",
		categoryKey: "plumbing",
		subcategoryKey: "water_supply",
		nameAr: "نقطة مياه باردة",
		nameEn: "Cold Water Point",
		descriptionAr: "نقطة تغذية مياه باردة كاملة (مواسير + محبس + تركيب)",
		descriptionEn: "Cold water supply point (pipes + valve + installation)",
		icon: "Droplet",
		color: "#0EA5E9",
		unit: "نقطة",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "عدد النقاط", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 35,
		defaultLaborUnitPrice: 25,
		commonMaterials: [
			{ nameAr: "PPR ألماني Wefatherm", nameEn: "Wefatherm PPR", brand: "Wefatherm", grade: "فاخر", suggestedPrice: 45, source: "imported" },
			{ nameAr: "PEX Geberit", nameEn: "Geberit PEX", brand: "Geberit", grade: "فاخر", suggestedPrice: 55, source: "imported" },
			{ nameAr: "PPR محلي SaudiPipe", nameEn: "Saudi PPR", grade: "عادي", suggestedPrice: 30, source: "local" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 110,
	},
	{
		itemKey: "mep.plumbing.hot_water_point",
		domain: "MEP",
		categoryKey: "plumbing",
		subcategoryKey: "water_supply",
		nameAr: "نقطة مياه ساخنة",
		nameEn: "Hot Water Point",
		descriptionAr: "نقطة تغذية مياه ساخنة (مواسير معزولة + محبس)",
		descriptionEn: "Hot water point (insulated pipes + valve)",
		icon: "Flame",
		color: "#DC2626",
		unit: "نقطة",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "عدد النقاط", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 45,
		defaultLaborUnitPrice: 30,
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 120,
	},
	{
		itemKey: "mep.plumbing.drainage_kitchen",
		domain: "MEP",
		categoryKey: "plumbing",
		subcategoryKey: "drainage",
		nameAr: "صرف صحي مطبخ",
		nameEn: "Kitchen Drainage Point",
		descriptionAr: "نقطة صرف صحي مطبخ (سيفون + موسورة)",
		descriptionEn: "Kitchen drainage (trap + pipe)",
		icon: "ArrowDownToLine",
		color: "#475569",
		unit: "نقطة",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "نقطة", min: 0 },
		},
		defaultMaterialUnitPrice: 60,
		defaultLaborUnitPrice: 35,
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 210,
	},
	{
		itemKey: "mep.plumbing.drainage_bathroom",
		domain: "MEP",
		categoryKey: "plumbing",
		subcategoryKey: "drainage",
		nameAr: "صرف صحي حمام (مجموعة)",
		nameEn: "Bathroom Drainage Set",
		descriptionAr: "مجموعة صرف حمام كاملة (مرحاض + مغسلة + شطاف + بانيو)",
		descriptionEn: "Complete bathroom drainage set",
		icon: "Bath",
		color: "#0E7490",
		unit: "حمام",
		defaultWastagePercent: 5,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "عدد الحمامات", unit: "حمام", min: 0 },
		},
		defaultMaterialUnitPrice: 280,
		defaultLaborUnitPrice: 180,
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 220,
	},
	{
		itemKey: "mep.plumbing.water_heater_electric",
		domain: "MEP",
		categoryKey: "plumbing",
		subcategoryKey: "heaters",
		nameAr: "سخان كهرباء",
		nameEn: "Electric Water Heater",
		descriptionAr: "سخان كهربائي 50-100 لتر",
		descriptionEn: "Electric water heater 50-100L",
		icon: "Zap",
		color: "#F59E0B",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 750,
		defaultLaborUnitPrice: 100,
		commonMaterials: [
			{ nameAr: "Ariston 80L", nameEn: "Ariston 80L", brand: "Ariston", grade: "عادي", suggestedPrice: 720, source: "imported" },
			{ nameAr: "Ideal Standard 100L", nameEn: "Ideal Standard 100L", brand: "Ideal Standard", grade: "فاخر", suggestedPrice: 1100, source: "imported" },
			{ nameAr: "Bosch 80L", nameEn: "Bosch 80L", brand: "Bosch", grade: "فاخر", suggestedPrice: 950, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 310,
	},
	{
		itemKey: "mep.plumbing.water_heater_solar",
		domain: "MEP",
		categoryKey: "plumbing",
		subcategoryKey: "heaters",
		nameAr: "سخان شمسي",
		nameEn: "Solar Water Heater",
		descriptionAr: "نظام سخان شمسي (لوحة + خزان معزول)",
		descriptionEn: "Solar heater system (panel + insulated tank)",
		icon: "Sun",
		color: "#EAB308",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 4500,
		defaultLaborUnitPrice: 800,
		legacyDerivationType: "per_unit",
		legacyScope: "whole_building",
		displayOrder: 320,
	},
	{
		itemKey: "mep.plumbing.water_tank",
		domain: "MEP",
		categoryKey: "plumbing",
		subcategoryKey: "tanks",
		nameAr: "خزان مياه (1000-5000 لتر)",
		nameEn: "Water Tank (1000-5000L)",
		descriptionAr: "خزان مياه بلاستيك أو فايبرجلاس",
		descriptionEn: "Plastic or fiberglass water tank",
		icon: "Box",
		color: "#0284C7",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 1200,
		defaultLaborUnitPrice: 250,
		commonMaterials: [
			{ nameAr: "خزان تنوس 3000 لتر", nameEn: "Tanos Tank 3000L", grade: "عادي", suggestedPrice: 1100, source: "local" },
			{ nameAr: "Polytank 2000 لتر", nameEn: "Polytank 2000L", grade: "عادي", suggestedPrice: 850, source: "local" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "whole_building",
		displayOrder: 410,
	},
	{
		itemKey: "mep.plumbing.pump",
		domain: "MEP",
		categoryKey: "plumbing",
		subcategoryKey: "pumps",
		nameAr: "مضخة مياه (Booster)",
		nameEn: "Water Pump (Booster)",
		descriptionAr: "مضخة ضغط مياه للمبنى",
		descriptionEn: "Building booster pump",
		icon: "Activity",
		color: "#0F766E",
		unit: "عدد",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "العدد", unit: "عدد", min: 0 },
		},
		defaultMaterialUnitPrice: 1800,
		defaultLaborUnitPrice: 300,
		commonMaterials: [
			{ nameAr: "Pedrollo إيطالي", nameEn: "Pedrollo Italy", brand: "Pedrollo", grade: "فاخر", suggestedPrice: 2200, source: "imported" },
			{ nameAr: "Grundfos دنماركي", nameEn: "Grundfos Denmark", brand: "Grundfos", grade: "فاخر", suggestedPrice: 2800, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "whole_building",
		displayOrder: 510,
	},
	{
		itemKey: "mep.plumbing.pipe_run",
		domain: "MEP",
		categoryKey: "plumbing",
		subcategoryKey: "pipes",
		nameAr: "تمديد مواسير سباكة",
		nameEn: "Plumbing Pipe Run",
		descriptionAr: "تمديد مواسير سباكة بالمتر الطولي",
		descriptionEn: "Pipe installation per meter",
		icon: "Minus",
		color: "#0E7490",
		unit: "م.ط",
		defaultWastagePercent: 12,
		defaultCalculationMethod: "length_only",
		requiredFields: {
			primary: { key: "length", label: "الطول", unit: "م.ط", min: 0 },
		},
		defaultMaterialUnitPrice: 22,
		defaultLaborUnitPrice: 12,
		legacyDerivationType: "length_only",
		legacyScope: "whole_building",
		displayOrder: 610,
	},
	{
		itemKey: "mep.plumbing.fittings_set",
		domain: "MEP",
		categoryKey: "plumbing",
		subcategoryKey: "fixtures",
		nameAr: "أطقم صحية (مجموعة كاملة)",
		nameEn: "Sanitary Fixtures Set",
		descriptionAr: "أطقم صحية كاملة لحمام واحد (مرحاض + مغسلة + شطاف + خلاطات)",
		descriptionEn: "Complete sanitary set per bathroom",
		icon: "Bath",
		color: "#0EA5E9",
		unit: "حمام",
		defaultWastagePercent: 0,
		defaultCalculationMethod: "per_unit",
		requiredFields: {
			primary: { key: "count", label: "عدد الحمامات", unit: "حمام", min: 0 },
		},
		defaultMaterialUnitPrice: 1800,
		defaultLaborUnitPrice: 200,
		commonMaterials: [
			{ nameAr: "RAK Ceramics مجموعة كاملة", nameEn: "RAK Full Set", brand: "RAK", grade: "عادي", suggestedPrice: 1700, source: "imported" },
			{ nameAr: "Geberit + Hansgrohe", nameEn: "Geberit + Hansgrohe", brand: "Geberit", grade: "فاخر", suggestedPrice: 4500, source: "imported" },
			{ nameAr: "Ideal Standard مجموعة", nameEn: "Ideal Standard Set", brand: "Ideal Standard", grade: "عادي", suggestedPrice: 2200, source: "imported" },
		],
		legacyDerivationType: "per_unit",
		legacyScope: "per_room",
		displayOrder: 710,
	},
];
