import { z } from "zod";
import { registerTool } from "../registry";
import {
  db,
  getChartOfAccounts,
  getAccountingDashboard,
  getAccountLedger,
  getTrialBalance,
  getBalanceSheet,
  getJournalIncomeStatement,
  getAgedReceivables,
  getAgedPayables,
  getVATReport,
  getCostCenterByProject,
} from "@repo/database";

// Tool 1: queryAccounting
registerTool({
  name: "queryAccounting",
  description:
    "استعلام بيانات المحاسبة — دليل الحسابات، القيود اليومية، الفترات المحاسبية، لوحة المحاسبة. action=chart: دليل الحسابات. action=journals: القيود اليومية. action=periods: الفترات. action=dashboard: ملخص ومؤشرات المحاسبة.",
  moduleId: "accounting",
  parameters: z.object({
    action: z.enum(["chart", "journals", "periods", "dashboard"]),
    status: z.enum(["DRAFT", "POSTED", "REVERSED"]).optional(),
    limit: z.number().min(1).max(50).default(20),
    dateFrom: z.string().optional(),
    dateTo: z.string().optional(),
  }),
  execute: async (params, context) => {
    try {
      if (params.action === "chart") {
        const accounts = await getChartOfAccounts(db, context.organizationId);
        return {
          accounts: accounts.map((a) => ({
            id: a.id,
            code: a.code,
            nameAr: a.nameAr,
            type: a.type,
            normalBalance: a.normalBalance,
            level: a.level,
            isActive: a.isActive,
            isPostable: a.isPostable,
          })),
          total: accounts.length,
        };
      }

      if (params.action === "journals") {
        const whereClause: Record<string, unknown> = {
          organizationId: context.organizationId,
        };
        if (params.status) whereClause.status = params.status;
        if (params.dateFrom || params.dateTo) {
          const dateFilter: Record<string, unknown> = {};
          if (params.dateFrom) dateFilter.gte = new Date(params.dateFrom);
          if (params.dateTo) dateFilter.lte = new Date(params.dateTo);
          whereClause.date = dateFilter;
        }
        const entries = await db.journalEntry.findMany({
          where: whereClause,
          take: params.limit,
          orderBy: { date: "desc" },
          select: {
            id: true,
            entryNo: true,
            date: true,
            description: true,
            referenceType: true,
            referenceNo: true,
            status: true,
            totalAmount: true,
            isAutoGenerated: true,
          },
        });
        return {
          entries: entries.map((e) => ({
            ...e,
            totalAmount: e.totalAmount?.toString() ?? "0",
          })),
          total: entries.length,
        };
      }

      if (params.action === "periods") {
        const periods = await db.accountingPeriod.findMany({
          where: { organizationId: context.organizationId },
          orderBy: { startDate: "desc" },
          select: {
            id: true,
            name: true,
            periodType: true,
            startDate: true,
            endDate: true,
            isClosed: true,
          },
        });
        return { periods, total: periods.length };
      }

      if (params.action === "dashboard") {
        const dashboard = await getAccountingDashboard(
          db,
          context.organizationId,
        );
        return dashboard;
      }

      return { error: "إجراء غير معروف" };
    } catch (e) {
      return { error: `فشل استعلام المحاسبة: ${(e as Error).message}` };
    }
  },
});

// Tool 2: getAccountLedger
registerTool({
  name: "getAccountLedger",
  description:
    "دفتر أستاذ حساب محدد — عرض كل الحركات مع الرصيد التراكمي. يحتاج accountId.",
  moduleId: "accounting",
  parameters: z.object({
    accountId: z.string(),
    dateFrom: z.string().optional(),
    dateTo: z.string().optional(),
  }),
  execute: async (params, context) => {
    try {
      const result = await getAccountLedger(
        db,
        params.accountId,
        context.organizationId,
        {
          dateFrom: params.dateFrom ? new Date(params.dateFrom) : undefined,
          dateTo: params.dateTo ? new Date(params.dateTo) : undefined,
          pageSize: 30,
        },
      );
      return result;
    } catch (e) {
      return { error: `فشل جلب دفتر الأستاذ: ${(e as Error).message}` };
    }
  },
});

// Tool 3: getAccountingReports
registerTool({
  name: "getAccountingReports",
  description:
    "التقارير المحاسبية — ميزان المراجعة، الميزانية العمومية، قائمة الدخل، تقرير الضريبة، أعمار الذمم المدينة والدائنة، مراكز التكلفة.",
  moduleId: "accounting",
  parameters: z.object({
    report: z.enum([
      "trialBalance",
      "balanceSheet",
      "incomeStatement",
      "vatReport",
      "agedReceivables",
      "agedPayables",
      "costCenter",
    ]),
    dateFrom: z.string().optional(),
    dateTo: z.string().optional(),
    projectId: z.string().optional(),
  }),
  execute: async (params, context) => {
    try {
      const orgId = context.organizationId;

      if (params.report === "trialBalance") {
        return await getTrialBalance(db, orgId, {
          asOfDate: params.dateTo ? new Date(params.dateTo) : new Date(),
          dateFrom: params.dateFrom ? new Date(params.dateFrom) : undefined,
        });
      }

      if (params.report === "balanceSheet") {
        return await getBalanceSheet(
          db,
          orgId,
          params.dateTo ? new Date(params.dateTo) : undefined,
        );
      }

      if (params.report === "incomeStatement") {
        const now = new Date();
        return await getJournalIncomeStatement(db, orgId, {
          dateFrom: params.dateFrom
            ? new Date(params.dateFrom)
            : new Date(now.getFullYear(), 0, 1),
          dateTo: params.dateTo ? new Date(params.dateTo) : now,
        });
      }

      if (params.report === "vatReport") {
        const now = new Date();
        return await getVATReport(
          db,
          orgId,
          params.dateFrom
            ? new Date(params.dateFrom)
            : new Date(now.getFullYear(), now.getMonth() - 2, 1),
          params.dateTo ? new Date(params.dateTo) : now,
        );
      }

      if (params.report === "agedReceivables") {
        return await getAgedReceivables(db, orgId, {
          asOfDate: params.dateTo ? new Date(params.dateTo) : undefined,
          projectId: params.projectId,
        });
      }

      if (params.report === "agedPayables") {
        return await getAgedPayables(db, orgId, {
          asOfDate: params.dateTo ? new Date(params.dateTo) : undefined,
          projectId: params.projectId,
        });
      }

      if (params.report === "costCenter") {
        return await getCostCenterByProject(db, orgId, {
          dateFrom: params.dateFrom ? new Date(params.dateFrom) : undefined,
          dateTo: params.dateTo ? new Date(params.dateTo) : undefined,
          projectId: params.projectId,
        });
      }

      return { error: "تقرير غير معروف" };
    } catch (e) {
      return { error: `فشل جلب التقرير: ${(e as Error).message}` };
    }
  },
});
