"use client";

import { useState } from "react";
import { useTranslations } from "next-intl";
import { useQuery } from "@tanstack/react-query";
import { orpc } from "@shared/lib/orpc-query-utils";
import { Card, CardContent, CardHeader, CardTitle } from "@ui/components/card";
import { Button } from "@ui/components/button";
import { Input } from "@ui/components/input";
import { Badge } from "@ui/components/badge";
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from "@ui/components/table";
import { Plus, Search, Zap, FileEdit } from "lucide-react";
import { DashboardSkeleton } from "@saas/shared/components/skeletons";
import { formatAccounting } from "./formatters";
import Link from "next/link";

interface JournalEntriesPageProps {
	organizationId: string;
	organizationSlug: string;
}

const STATUS_BADGE: Record<string, { variant: "default" | "secondary" | "outline"; label: string }> = {
	DRAFT: { variant: "secondary", label: "مسودة" },
	POSTED: { variant: "default", label: "مرحّل" },
	REVERSED: { variant: "outline", label: "معكوس" },
};

const REF_TYPE_BADGE: Record<string, string> = {
	INVOICE: "فاتورة",
	INVOICE_PAYMENT: "تحصيل",
	EXPENSE: "مصروف",
	TRANSFER: "تحويل",
	SUBCONTRACT_PAYMENT: "مقاول باطن",
	PAYROLL: "رواتب",
	ORG_PAYMENT: "مقبوضات",
	CREDIT_NOTE: "إشعار دائن",
	ADJUSTMENT: "تسوية",
	REVERSAL: "عكس",
	MANUAL: "يدوي",
};

export function JournalEntriesPage({
	organizationId,
	organizationSlug,
}: JournalEntriesPageProps) {
	const t = useTranslations();
	const [search, setSearch] = useState("");
	const [status, setStatus] = useState<string>("");
	const basePath = `/app/${organizationSlug}/finance/journal-entries`;

	const { data, isLoading } = useQuery(
		orpc.accounting.journal.list.queryOptions({
			input: {
				organizationId,
				status: status as any || undefined,
				search: search || undefined,
				limit: 50,
			},
		}),
	);

	if (isLoading) return <DashboardSkeleton />;

	const entries = data?.entries ?? [];

	return (
		<div className="space-y-4">
			{/* Filters + Actions */}
			<div className="flex flex-wrap items-center justify-between gap-3">
				<div className="flex items-center gap-2">
					<div className="relative">
						<Search className="absolute start-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
						<Input
							placeholder={t("finance.accounting.search")}
							value={search}
							onChange={(e) => setSearch(e.target.value)}
							className="ps-9 rounded-xl w-64"
						/>
					</div>
					<select
						value={status}
						onChange={(e) => setStatus(e.target.value)}
						className="h-9 rounded-xl border border-slate-200 dark:border-slate-700 bg-transparent px-3 text-sm"
					>
						<option value="">{t("finance.accounting.draft")} / {t("finance.accounting.posted")} / {t("finance.accounting.reversed")}</option>
						<option value="DRAFT">{t("finance.accounting.draft")}</option>
						<option value="POSTED">{t("finance.accounting.posted")}</option>
						<option value="REVERSED">{t("finance.accounting.reversed")}</option>
					</select>
				</div>
				<div className="flex gap-2">
					<Link href={`${basePath}/new-adjustment`}>
						<Button variant="outline" size="sm" className="rounded-xl">
							<FileEdit className="h-4 w-4 me-1" />
							{t("finance.accounting.adjustments.newAdjustment")}
						</Button>
					</Link>
				</div>
			</div>

			{/* Table */}
			<Card className="rounded-2xl">
				<CardContent className="p-0">
					{entries.length === 0 ? (
						<div className="text-center py-12 text-slate-500">
							{t("finance.accounting.noEntries")}
						</div>
					) : (
						<Table>
							<TableHeader>
								<TableRow>
									<TableHead>{t("finance.accounting.entryNo")}</TableHead>
									<TableHead>{t("finance.accounting.entryDate")}</TableHead>
									<TableHead>{t("finance.accounting.description")}</TableHead>
									<TableHead>{t("finance.accounting.reference")}</TableHead>
									<TableHead className="text-end">{t("finance.accounting.amount")}</TableHead>
									<TableHead className="text-center">{t("finance.accounting.posted")}</TableHead>
								</TableRow>
							</TableHeader>
							<TableBody>
								{entries.map((entry) => {
									const statusInfo = STATUS_BADGE[entry.status] ?? STATUS_BADGE.DRAFT;
									return (
										<TableRow key={entry.id} className="cursor-pointer hover:bg-slate-50 dark:hover:bg-slate-800/50">
											<TableCell>
												<Link href={`${basePath}/${entry.id}`} className="font-mono text-sm text-primary hover:underline">
													{entry.entryNo}
												</Link>
											</TableCell>
											<TableCell className="text-sm text-slate-500">
												{new Date(entry.date).toLocaleDateString("en-SA")}
											</TableCell>
											<TableCell className="text-sm max-w-[250px] truncate">
												{entry.isAutoGenerated && (
													<Zap className="h-3 w-3 text-amber-500 inline me-1" />
												)}
												{entry.description}
											</TableCell>
											<TableCell>
												{entry.referenceType && (
													<Badge variant="outline" className="text-[10px]">
														{REF_TYPE_BADGE[entry.referenceType] ?? entry.referenceType}
													</Badge>
												)}
											</TableCell>
											<TableCell className="text-end font-medium">
												{formatAccounting(entry.totalAmount)}
											</TableCell>
											<TableCell className="text-center">
												<Badge variant={statusInfo.variant} className="text-[10px]">
													{statusInfo.label}
												</Badge>
											</TableCell>
										</TableRow>
									);
								})}
							</TableBody>
						</Table>
					)}
				</CardContent>
			</Card>
		</div>
	);
}
