"use client";

import { useTranslations } from "next-intl";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { orpc } from "@shared/lib/orpc-query-utils";
import { Card, CardContent, CardHeader, CardTitle } from "@ui/components/card";
import { Button } from "@ui/components/button";
import { Badge } from "@ui/components/badge";
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from "@ui/components/table";
import { Check, RotateCcw, Trash2, Zap } from "lucide-react";
import { DashboardSkeleton } from "@saas/shared/components/skeletons";
import { formatAccounting } from "./formatters";
import { useRouter } from "next/navigation";

interface JournalEntryDetailsProps {
	organizationId: string;
	organizationSlug: string;
	entryId: string;
}

export function JournalEntryDetails({
	organizationId,
	organizationSlug,
	entryId,
}: JournalEntryDetailsProps) {
	const t = useTranslations();
	const router = useRouter();
	const queryClient = useQueryClient();

	const { data: entry, isLoading } = useQuery(
		orpc.accounting.journal.getById.queryOptions({
			input: { organizationId, id: entryId },
		}),
	);

	const postMutation = useMutation({
		...orpc.accounting.journal.post.mutationOptions(),
		onSuccess: () => queryClient.invalidateQueries({ queryKey: ["accounting"] }),
	});

	const reverseMutation = useMutation({
		...orpc.accounting.journal.reverse.mutationOptions(),
		onSuccess: () => queryClient.invalidateQueries({ queryKey: ["accounting"] }),
	});

	const deleteMutation = useMutation({
		...orpc.accounting.journal.delete.mutationOptions(),
		onSuccess: () => {
			queryClient.invalidateQueries({ queryKey: ["accounting"] });
			router.push(`/app/${organizationSlug}/finance/journal-entries`);
		},
	});

	if (isLoading) return <DashboardSkeleton />;
	if (!entry) return <div className="text-center py-10 text-slate-500">Not found</div>;

	const statusColors: Record<string, string> = {
		DRAFT: "bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300",
		POSTED: "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300",
		REVERSED: "bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400",
	};

	const totalDebit = entry.lines.reduce((s: number, l: any) => s + l.debit, 0);
	const totalCredit = entry.lines.reduce((s: number, l: any) => s + l.credit, 0);

	return (
		<div className="space-y-6">
			{/* Header */}
			<Card className="rounded-2xl">
				<CardContent className="p-6">
					<div className="flex items-start justify-between">
						<div className="space-y-2">
							<div className="flex items-center gap-3">
								<h2 className="text-xl font-bold text-slate-900 dark:text-slate-100">
									{entry.entryNo}
								</h2>
								<span className={`px-2.5 py-0.5 rounded-full text-xs font-medium ${statusColors[entry.status]}`}>
									{t(`finance.accounting.${entry.status.toLowerCase()}`)}
								</span>
								{entry.isAutoGenerated && (
									<Badge variant="outline" className="text-[10px]">
										<Zap className="h-3 w-3 me-1 text-amber-500" />
										{t("finance.accounting.autoGenerated")}
									</Badge>
								)}
							</div>
							<p className="text-slate-600 dark:text-slate-400">{entry.description}</p>
							<div className="flex gap-4 text-sm text-slate-500">
								<span>{new Date(entry.date).toLocaleDateString("en-SA")}</span>
								{entry.referenceType && (
									<span>
										{entry.referenceType}{entry.referenceNo ? `: ${entry.referenceNo}` : ""}
									</span>
								)}
							</div>
						</div>

						{/* Actions */}
						<div className="flex gap-2">
							{entry.status === "DRAFT" && (
								<>
									<Button
										size="sm"
										onClick={() => {
											if (confirm(t("finance.accounting.confirmPost"))) {
												postMutation.mutate({ organizationId, id: entryId });
											}
										}}
										disabled={postMutation.isPending}
										className="rounded-xl"
									>
										<Check className="h-4 w-4 me-1" />
										{t("finance.accounting.postEntry")}
									</Button>
									<Button
										size="sm"
										variant="error"
										onClick={() => {
											if (confirm(t("finance.accounting.confirmDelete"))) {
												deleteMutation.mutate({ organizationId, id: entryId });
											}
										}}
										disabled={deleteMutation.isPending}
										className="rounded-xl"
									>
										<Trash2 className="h-4 w-4 me-1" />
										{t("finance.accounting.deleteEntry")}
									</Button>
								</>
							)}
							{entry.status === "POSTED" && (
								<Button
									size="sm"
									variant="outline"
									onClick={() => {
										if (confirm(t("finance.accounting.confirmReverse"))) {
											reverseMutation.mutate({ organizationId, id: entryId });
										}
									}}
									disabled={reverseMutation.isPending}
									className="rounded-xl"
								>
									<RotateCcw className="h-4 w-4 me-1" />
									{t("finance.accounting.reverseEntry")}
								</Button>
							)}
						</div>
					</div>
				</CardContent>
			</Card>

			{/* Lines Table */}
			<Card className="rounded-2xl">
				<CardHeader>
					<CardTitle className="text-sm">{t("finance.accounting.journalEntries")}</CardTitle>
				</CardHeader>
				<CardContent className="p-0">
					<Table>
						<TableHeader>
							<TableRow>
								<TableHead>{t("finance.accounting.accountCode")}</TableHead>
								<TableHead>{t("finance.accounting.accountName")}</TableHead>
								<TableHead>{t("finance.accounting.description")}</TableHead>
								<TableHead className="text-end">{t("finance.accounting.debit")}</TableHead>
								<TableHead className="text-end">{t("finance.accounting.credit")}</TableHead>
							</TableRow>
						</TableHeader>
						<TableBody>
							{entry.lines.map((line: any) => (
								<TableRow key={line.id}>
									<TableCell className="font-mono text-sm">{line.account?.code}</TableCell>
									<TableCell>{line.account?.nameAr}</TableCell>
									<TableCell className="text-sm text-slate-500">{line.description}</TableCell>
									<TableCell className="text-end">{formatAccounting(line.debit)}</TableCell>
									<TableCell className="text-end">{formatAccounting(line.credit)}</TableCell>
								</TableRow>
							))}
							{/* Totals */}
							<TableRow className="border-t-2 font-bold bg-slate-50 dark:bg-slate-800">
								<TableCell colSpan={3}>{t("finance.accounting.aging.total")}</TableCell>
								<TableCell className="text-end">{formatAccounting(totalDebit)}</TableCell>
								<TableCell className="text-end">{formatAccounting(totalCredit)}</TableCell>
							</TableRow>
						</TableBody>
					</Table>
				</CardContent>
			</Card>

			{entry.notes && (
				<Card className="rounded-2xl">
					<CardContent className="p-4">
						<p className="text-sm text-slate-600 dark:text-slate-400">{entry.notes}</p>
					</CardContent>
				</Card>
			)}
		</div>
	);
}
